### ISSUE TITLE
Does not trigger collision related events for existing mesh from Three.js scene!

### ISSUE THREAD

**Issue by Smithangshu** [enable3d/enable3d#10]
It's not triggering Collision related events if existing mesh is added to the Physic and its body is set to trigger the event. It reacts on collision correctly but it does not trigger the event. Also some issue with destroying the physics body for existing objects.

**Comment by yandeu** [comment]
Can you please post a code example?

**Comment by Smithangshu** [comment]
For example if you consider the following code it will not trigger collision event if something collides with it but the colliding body reacts as it is supposed to do on the occasion of collision. But event does not fire any of the bodies but if I would add these two bodies with physics.add.box(..) then it fires the event as same as in your example.

`var cube = new THREE.Mesh(new THREE.BoxBufferGeometry(10, 10, 10), material)
scene.add(cube)
physics.add.existing(cube)

cube.body.on.collision((otherObject, event) => {
    console.log('cube is experiencing collision')
  }
});`

**Comment by Smithangshu** [comment]
Please ignore the last code block, following one is much easier to reproduce the phenomenon,

```
// blue sphere existing
const bluegeo = new THREE.SphereBufferGeometry();
const bluemat = new THREE.MeshLambertMaterial({ color: 0x0000ff });
var bluesphere = new THREE.Mesh(bluegeo,bluemat );
bluesphere.position.set(0,10,0);
scene.add(bluesphere);
physics.add.existing(bluesphere);
//--------------------

//blue sphere new
//var bluesphere = physics.add.sphere({y:10}, { lambert: { color: 0x0000ff }});
//--------------------

bluesphere.body.on.collision((otherobject, event)=>{
  console.log('Blue cube is experiencing collision');
});
//green box existing
const greengeo = new THREE.BoxBufferGeometry();
const greenmat = new THREE.MeshLambertMaterial({ color: 0x00ff00 });
const greenbox = new THREE.Mesh(greengeo, greenmat);
greenbox.position.set(0, 5, 0);
scene.add(greenbox);
physics.add.existing(greenbox, {mass:100});
greenbox.body.setCollisionFlags(1);
greenbox.body.on.collision((otherobject, event)=>{
 console.log('Green cube is experiencing collision');
});
//ground
physics.add.ground({ width: 20, height: 20 });
```
If you keep the "// blue sphere existing" part uncommented it will not trigger any of the collision events but if you comment it and uncomment the "//blue sphere new" part so you can see that its triggering the both of the events. Hope with this you can reproduce the issue and fix it.

**Comment by yandeu** [comment]
Oh I see.

There are 2 ways to fix this.

```js
// 1) do this
const greenbox = new ExtendedMesh(greengeo, greenmat)
// instead of this
const greenbox = new THREE.Mesh(greengeo, greenmat)


// 2) add a unique name to your mesh
greenbox.name = 'your-unique-name'
```
The prefered way is to use ExtendedMesh, since it adds some additional functionalities to the default THREE.Mesh. It will be exported in the next version, but for now you can get it from the `@enable3d/common` module

---

And for a static object, prefer using a Mass of 0 instead of > 0.

```js
physics.add.existing(greenbox, {mass:0});
greenbox.body.setCollisionFlags(1);
```

**Comment by Smithangshu** [comment]
Great! I will try this out.

**Comment by yandeu** [comment]
I guess this has been resolved?
