### ISSUE TITLE
antialiasing

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#11]
Hello,

Is there any way to enable anti-aliasing? This method has been completely removed from the renderer method, I don't know if it's intentional on your part. ^^

**Comment by yandeu** [comment]
You still using the Phaser Extension I presume?

You can add it when you add the custom canvas to your Phaser config file.

```js
 ...Canvas({ antialias: true })
```

also in the Scene3D you can adjust the PixelRatio:

```js
 this.third.renderer.setPixelRatio(window.devicePixelRatio)
```

**Comment by Trusiak** [comment]
Yes, thank you - it works! ^^
