### ISSUE TITLE
Closure compilation failed with 1 errors

### ISSUE THREAD

**Issue by xf-salva** [enable3d/enable3d#112]
Hello, with  @enable3d/phaser-extension": "^0.21.0",  i'm getting :

Closure compilation failed with 1 errors
--- node_modules/@enable3d/three-wrapper/dist/index.js:3
Class names defined inside a function cannot be reassigned.

thanks

**Comment by yandeu** [comment]
Have you tried the [enable3d-phaser-project-template](https://github.com/enable3d/enable3d-phaser-project-template)?

**Comment by yandeu** [comment]
Upgrade to [npm@7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) and install the latest dev version:
`npm i @enable3d/phaser-extension@0.22.0-dev.0`

**Comment by xf-salva** [comment]
thank you, is solved
