### ISSUE TITLE
ApplyTorque Missing

### ISSUE THREAD

**Issue by DeeElGee** [enable3d/enable3d#12]
Hi,

Really like the project.

We were playing with enable3d but found that applyTorque hasn't been included from AmmoJS. Any reason why? And any thoughts to include it?

Thanks!

**Comment by yandeu** [comment]
Thanks :)

I guess I forgot it. Will add it in the next version.

But you can already access it via 
```js
object.body.ammo.applyTorque( btVector3 )
```

**Comment by DeeElGee** [comment]
Many thanks for the tip 👍
