### ISSUE TITLE
Standardized cache system

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#13]
hello, i'm using Phaser Extension

the problem is that the phaser.JS processes the cache differently than three.JS - mean loading assets.
F.E:

When using the load method, the phaser will first check in the cache memory if the object exists. If so, it will not execute the request to the server for the file again. 
The opposite is true for THREE.js, because trying to load an object results in the request being executed anyway, wasting the time and resources.

Is it possible to unify it somehow to make THREE load also work this way? or should I just use external libraries and do it on my own?

**Comment by yandeu** [comment]
I have changed the loaders a lot (in the v18 branch) and also added a caching system. Once v18 is available, please check the examples to adapt your code.

**Comment by yandeu** [comment]
The new version is available. The loaders have a cache now and always return a promise.

(If you use phaser, use `this.third.`)

You can do: 

```js
async create() {
  // cache the file
  await this.load.gltf( 'cacheKey', '/path/to/file' )

  // access from cache
  const gltf = this.cache.get( 'cacheKey' )
}
 ```
or
```js
create() {
  // without caching
  this.third.load.gltf( '/assets/glb/robot.glb' ).then(gltf => {
    ...
  })
}
```
Take a look at the [new examples](https://enable3d.io/examples.html).
