### ISSUE TITLE
physics.add.existing shape concaveMesh integer overflow error

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#136]
**Describe the bug**

when use multi CylinderGeometry to construct a object, example a rect panel (the pink one)
![2021-03-19 14_46_31-Window](https://user-images.githubusercontent.com/6566869/111741787-07279680-88c2-11eb-986c-7752eccc4e0e.png)

create 4 Cylinder pip and move the pos to be a rect:
```ts
const createPipe = (len: number,
                    rectanglePipePanel: Required<TemplateBarrier>['rectanglePipePanel']) => {
    const geometry = new THREE.CylinderGeometry(
        rectanglePipePanel.radius,
        rectanglePipePanel.radius,
        len,
        rectanglePipePanel.radialSegments,
        1,
        false,
        0,
        Math.PI * 2,
    );
    return new ExtendedMesh(geometry, material);
};
const A1 = createPipe(T.template.rectanglePipePanel.x, T.template.rectanglePipePanel);
A1.position.y = -T.template.rectanglePipePanel.y / 2;
const A2 = createPipe(T.template.rectanglePipePanel.x, T.template.rectanglePipePanel);
A2.position.y = T.template.rectanglePipePanel.y / 2;
const B1 = createPipe(T.template.rectanglePipePanel.y, T.template.rectanglePipePanel);
B1.position.x = -T.template.rectanglePipePanel.x / 2;
const B2 = createPipe(T.template.rectanglePipePanel.y, T.template.rectanglePipePanel);
B2.position.x = T.template.rectanglePipePanel.x / 2;
A1.rotateZ(Math.PI / 2);
A2.rotateZ(Math.PI / 2);
TT = new ExtendedObject3D();
TT.add(A1, A2, B1, B2);

```

then , add it to physics:
```ts
try {
     this.physics.add.existing(TT as unknown as ExtendedObject3D, {
         mass: 0,
         collisionFlags: 1,
         shape: 'concaveMesh',
         collisionGroup: collideConfig.barrier.group,
         collisionMask: collideConfig.barrier.mask,
     },);
 } catch (e) {
     console.error(e);
 }
```

then i get a "integer overflow" error:
![2021-03-19 14_46_45-Window](https://user-images.githubusercontent.com/6566869/111741812-0ee73b00-88c2-11eb-94a5-117011fe9815.png)

```
RuntimeError: integer overflow
    _emscripten_bind_btBvhTriangleMeshShape_btBvhTriangleMeshShape_3 ammo.wasm.js:84
    aw ammo.wasm.js:455
    createTriMeshShape three-to-ammo.js:493
    createCollisionShape physics.js:642
    addExisting physics.js:703
........
```

---

the convexMesh not throw error but not generate physics body.
the hacd work very slow on my other use case and will "index out of bounds" error on this case.
```
RuntimeError: index out of bounds
    _emscripten_bind_HACD_Compute_0 ammo.wasm.js:62
    Compute ammo.wasm.js:388
    createHACDShapes three-to-ammo.js:292
    createCollisionShape physics.js:633
    addExisting physics.js:703
......
```
the hull seems like not work on Concave polyhedron .
 do i have any way to fix this ?
can i use compound body ?

**Comment by Lyoko-Jeremie** [comment]
in the document say: "Enable3d does automatically recognize the shape of simple three.js object when adding it via `physics.add.existing(object)` "

but it only work on position move, but if three object be rotate in object space, the auto generate shape will wrong. and seems like the manual shape add way (the `compound` field) also not have rotate prop same as auto gen way.

you can see it follow:

![2021-03-19 15_41_03-Window](https://user-images.githubusercontent.com/6566869/111746894-971d0e80-88c9-11eb-94f7-bd28eaa9b0aa.png)
![2021-03-19 15_41_24-Window](https://user-images.githubusercontent.com/6566869/111746900-997f6880-88c9-11eb-8b36-814dcce41c1a.png)

**Comment by yandeu** [comment]
I have fixed it! (I just forgot to add it 😅)

This works now:
```ts
const mat = new THREE.MeshLambertMaterial()

const createPipe = () => {
  const geometry = new THREE.CylinderGeometry(0.5, 0.5, 5)
  return new THREE.Mesh(geometry, mat)
}

const A1 = createPipe()
A1.position.y = -2

const A2 = createPipe()
A2.position.y = +2

const B1 = createPipe()
B1.position.x = +2

const B2 = createPipe()
B2.position.x = -2

A1.rotateZ(Math.PI / 2)
A2.rotateZ(Math.PI / 2)

const obj = new ExtendedObject3D()
obj.add(A1, A2, B1, B2)
obj.position.y += 3

this.scene.add(obj)
this.physics.add.existing(obj)
```

Will be available in the next version.

**Comment by Lyoko-Jeremie** [comment]
Oh, i'm wating the next version online~🤣
When can i have it ?
