### ISSUE TITLE
Physics Body and Mesh not in sync

### ISSUE THREAD

**Issue by DeeElGee** [enable3d/enable3d#14]
Hey @yandeu ,

I've uploaded a video of the syncing issue. I've re-enabled phaser, which means that the mesh no longer "snaps" into place when the body realigns with the mesh, but as you can see there's still some odd syncing problems.

[https://youtu.be/Wugs0axGZ0w](https://youtu.be/Wugs0axGZ0w)

I've used your examples to build this - just applying setVelocity and setAngularVelocity for movement. But otherwise it's a standard scene. Found that removing Vue doesn't change the behaviour, so definitely something in how the scene is updating that's causing the problem.

Any help gratefully received!

**Comment by yandeu** [comment]
The objects are rendered using interpolation, but the debug drawer not. 
I have verified it, by rendering my scene with the non-interpolated values, and the debug drawer and the objects where perfectly in sync.

So, what you are experiencing is completely normal :)

---

From the bullet physics manual:

> **Interpolation**
Bullet knows how to interpolate body movement for you. As mentioned, implemention of 
interpolation is handled through MotionStates. If you attempt to ask a body for its position through btCollisionObject::getWorldTransform or btRigidBody::getCenterOfMassTransform, it will return the position at the end of the last physics tick. That's useful for many things, but for rendering you will want some interpolation. Bullet interpolates the transform of the body before passing the value to setWorldTransform. If you want the non-interpolated position of a body [which will be the position as it was calculated at the end of the last physics tick], use btRigidBody::getWorldTransform() and query the body directly.
