### ISSUE TITLE
Strange errors after update to 0.18.0-alpha.0

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#15]
I've just updated enable3d to check the new cache system and such:
https://i.imgur.com/suWgZTd.png

I didn't touch anything except for the update, everything was going without errors. 

ps. i didn't use any 'water module' or similar in my project.

**Comment by yandeu** [comment]
Thanks! Yes, this is a bug. It loads all these files from the src folder instead of the dist folder. I have fixed it [here](https://github.com/enable3d/enable3d/commit/93a2a864d8c364511f0c88d8eefaea0e017b9ea5).

Will quickly upload it to npm, test it, and close this issue if it has been resolved :)

**Comment by yandeu** [comment]
It did work!

Also make sure you update this
```js
import enable3d, { Canvas } from '@enable3d/phaser-extension'
```
to this
```js
import { enable3d, Canvas } from '@enable3d/phaser-extension'
```

And take a look at the [new examples](https://enable3d.io/examples.html). A lot has changed in version 0.18.0.
