### ISSUE TITLE
How to load light in v0.18?

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#16]
Hello, im using phaser3-extension

I rewrote a lot of code for the new version of the library using examples (as you mentioned), but I can't handle the light (and I didn't find an example either). 

it has worked so far:

 ```
this.light_test = this.third.add.pointLight({
            color: 0xF77C3F,
            intensity: 5.5
        }); 
this.light_test.position.set(...pos)
``` 

what should i change now?

PS. you should add some examples about light into your collection ^^

https://i.imgur.com/A6EBtX2.png

**Comment by yandeu** [comment]
Light is now part of a plugin which has its own namespace. 

Try:
```js
this.third.lights.pointLight()
```

---

> PS. you should add some examples about light into your collection ^^

Yes, I will let this issue open until I have added a lights example :)

**Comment by yandeu** [comment]
I just added a [spotlight example](https://enable3d.io/examples/spotlight.html). While I did it, I noticed that I really have not implemented many lights features yet. I guess you have to wait until the next release to see more lights examples.

**Comment by yandeu** [comment]
I have updated the [spotlight example](https://enable3d.io/examples/spotlight.html) to the new API. You should be able to create every light like this. And for those who have a helper, add it via `this.lights.helper.xxxxLightHelper()`

**Comment by yandeu** [comment]
There are now two lights examples:
- https://enable3d.io/examples/lights.html
- https://enable3d.io/examples/spotlight.html

I guess I can close this issue now.
