### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by Maryasych** [enable3d/enable3d#17]
**ver. 0.18.0-alpha.0**

How to update physics body size after scaling? Works fine only with three meshes.
- gltf model
from [examples](https://github.com/enable3d/enable3d-website/blob/master/src/examples/compare-physics-body-shapes.html)
### 
      const suzanne = gltf.scene.children[0]
      suzanne.scale.set(0.5, 0.5, 0.5)

[**result:**](http://i.piccy.info/i9/3350a509f03978d898bc5167916e1f91/1590247233/103719/1379776/Zn_mok_ekrana_2020_05_23_o_18_13_55.jpg)

- Enalbe3d mesh:
### 
    let torus = physics.add.torus({
        x: 7,
        y: 5,
        shape: 'hacd',
        mass: 0
    },{
        basic: {color: 0xff0000, transparent: true, opacity: 0.5}
    })
    torus.scale.set(3, 3, 3)

[**result**](http://i.piccy.info/i9/b87b0a2d92e457acb24af12f9f69ba4e/1590249260/17958/1379776/Zn_mok_ekrana_2020_05_23_o_18_41_54.png)

- THREE Mesh:
### 
    var torus = new THREE.Mesh(geo, mat);
    torus.scale.set(3, 3, 3)
    scene.add(torus);
    physics.add.existing(torus, {
        shape: 'hacd',
        mass: 0
    });

[**result**](http://i.piccy.info/i9/6c3c46022e4bd316884f085bd657de54/1590248800/40249/1379776/Zn_mok_ekrana_2020_05_23_o_18_41_40.png)

**Comment by yandeu** [comment]
You can't scale a physics body after added to the world. Erwin Coumans, the creator of Bullet [once wrote](https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=9216):

> Before you make any change to the collision shape (replace shape, resize etc) you need to 
> 1) remove the rigid body from the world
> 2) make the change (resize etc)
> 3) re-insert the body into the world

So scale your object before adding a physics body.

---

In the [compare-physics-body-shapes](https://enable3d.io/examples/compare-physics-body-shapes.html) use:
```js
object.add(suzanne.clone())
object.scale.set(0.5, 0.5, 0.5) // <--
object.position.set(i * 3 - 7.5, 1.2, 0)
```

For the torus, do:
```js
// add torus (without physics)
let torus = physics.factory.add.torus({ x: 7, y: 5 }, { basic: { color: 0xff0000, transparent: true, opacity: 0.5 } })
// scale torus
torus.scale.set(3, 3, 3)
// add a rigid body to it
physics.add.existing(torus, {
  shape: 'hacd',
  mass: 0
})
```

---

You could also destroy the physics body `physics.destroy(torus.body)` and add a new one with `physics.add.existing()`.

---

Btw, I see you use `mass: 0`. Maybe you also want to make it a Static Body with `collisionFlags: 1`

**Comment by Maryasych** [comment]
Thanks for the answer.

> In the compare-physics-body-shapes use:

> object.scale.set(0.5, 0.5, 0.5) // <--

nothing has changed, result is the same.
Enable3d torus now woks fine, but model not.

**Comment by yandeu** [comment]
I just added a "Position, Rotation and Scale" section to the [documentation](https://enable3d.io/docs.html).

**Comment by Maryasych** [comment]
> You could also destroy the physics body `physics.destroy(torus.body)` and add a new one with `physics.add.existing()`.

Destroyed bodies only factory created objects. Three objects body - not.
How to?

###### https://enable3d.io/examples/camera-lerping-and-player-controls.html - error

**Comment by yandeu** [comment]
I see. This example uses the `THREE.Group()` which I haven't created an extended version for yet. I have updated the example to make it compatible for destroying and adding new bodies.

```js
// uncomment this, to destroy the body and create a new one (for testing)
setTimeout(() => {
   this.third.physics.destroy(this.player.body)
}, 1000)

setTimeout(() => {
   this.third.physics.add.existing(this.player)
}, 2000)
```

---

Btw, you can look at the [source code](https://github.com/enable3d/enable3d/tree/master/packages/common/src) for the extended objects. They don't do much more than providing TypeScript typings and adding a default name. Setting the name is essential for the physics engine.
