### ISSUE TITLE
Open Option for OffscreenCanvas

### ISSUE THREAD

**Issue by DeeElGee** [enable3d/enable3d#18]
As a performance improvement, it would be great to have support for OffscreenCanvas (where supported).

See example here: https://threejs.org/examples/webgl_worker_offscreencanvas.html

**Comment by yandeu** [comment]
I have never heard of it. Can you quickly explain what it is and for what it can be useful for enable3d?

**Comment by DeeElGee** [comment]
Basically it means you can render to canvas without needing to have access to the DOM. As a result, you can implement a webworker to do your rendering (like the example above) which means it can be multithreaded. See https://developers.google.com/web/updates/2018/08/offscreen-canvas

> Until now, canvas drawing capabilities were tied to the <canvas> element, which meant it was directly depending on the DOM. OffscreenCanvas, as the name implies, decouples the DOM and the Canvas API by moving it off-screen.

> Thanks to this decoupling, rendering of OffscreenCanvas is fully detached from the DOM and therefore offers some speed improvements over the regular canvas as there is no synchronization between the two. What is more, though, is that it can be used in a Web Worker, even though there is no DOM available. This enables all kinds of interesting use cases.

**Comment by yandeu** [comment]
I see. It seems not to be [as well supported](https://caniuse.com/#search=OffscreenCanvas) as normal Web Workers. But I'll see what I can do :)

**Comment by DeeElGee** [comment]
Yeah, support isn't as strong yet, but I'm sure it'll come. I think you would still have to implement a webworker to get the most out of it. But the Three example I've shared seems relatively straight forward.

Also, in terms of supprt, Chrome seems to oddly be the most affected browser, from what we've seen, and it has the most to gain. Thanks, would be super helpful, I believe.
