### ISSUE TITLE
Issue with Object created from SVG

### ISSUE THREAD

**Issue by madis12345** [enable3d/enable3d#182]
I extruded an SVG to generate a flower shape and tried to hang a torus from one of the petal. I tried to follow Wrecking ball with metal chain example for the same. However, torus fall on the ground and does not hold on to the petal. Is it possible for objects created from SVG or imported STL objects to hold on to each other, the way torus holds on in the Wrecking ball example?

**Comment by yandeu** [comment]
It is possible but **very** inefficient. The torus is actually a compound of multiple cylinders. This is why it works so well.

You could achieve something similar using convex mesh. But unfortunately, 2 convex mesh can't collide with each other.

Maybe the [hollow cylinder](https://enable3d.io/examples/hollow-cylinder.html) example helps?

Or maybe you want to share your repo or some snippets?

**Comment by madis12345** [comment]
https://www.cgtrader.com/free-3d-print-models/jewelry/pendants/pendant-set-good-looking-light-weight

I need to hold the 2 pendants/elements shown here with the help of a torus. Torus passes through the vertical structures (placed at equal distances in these pendants) one from each pendent, which ensures that they hold on to each other. Any optimal way other than creating physics object of the same geometry? I would be connecting 10 to 12 such elements to form a chain.

**Comment by yandeu** [comment]
I hope this [new example](https://enable3d.io/examples/carousel.html) helps!
