### ISSUE TITLE
Add Option for WebWorker for AmmoJS

### ISSUE THREAD

**Issue by DeeElGee** [enable3d/enable3d#19]
Where supported, it would be a real performance improvement to include a webworker for the Ammo JS calculations.

See example here: https://playground.babylonjs.com/#N7PGG3#2

**Comment by yandeu** [comment]
I plan definitively to add it, once the project becomes more popular. I have never used the Web Workers API, so I would first have to make some tests.

For now I have no performance issues, since enable3d loads the wasm build if the client browsers allows it.

---

Btw, I see you reference babylonjs. I have already played around rewriting the `@enable3d/ammo-physics` to use with babylonjs. This is also on my todo list.

**Comment by DeeElGee** [comment]
We've been playing around with Enable3D - it's really great. But with any Ammo.JS project (presumably other physics engines too) when the FPS starts to drop due to other processes (e.g. running a Teams video call, which has a big impact on the GPU), or it's a low performance machine, then the Physics start to jank or glitch. 

So any performance tweaks you can include would be very helpful going forwards. The Babylon reference I included shows how to implement Ammo JS with an inline webworker. It looks relatively straight forward.

**Comment by yandeu** [comment]
> We've been playing around with Enable3D - it's really great.

Thanks :smiley: 

I guess I will start trying to put the physics update loop in a worker. It seems to be [well supported](https://caniuse.com/#search=Web%20Workers). I'll see what I can do :)

**Comment by DeeElGee** [comment]
Thanks! Look forward to seeing what you come up with :-)

**Comment by yandeu** [comment]
I just looked into Web Workers + Ammo.js. It looks very promising, but it requires a lot of refactoring. I will definitely try to implement it :)

**Comment by DeeElGee** [comment]
So glad you agree it's worth trying. Think it could be hugely beneficial.

**Comment by yandeu** [comment]
I'm making progress:
https://youtu.be/p1iVl1p89SA

**Comment by DeeElGee** [comment]
Looking really promising

**Comment by DeeElGee** [comment]
@yandeu just wondering how progress was with this?  Am keeping my fingers tightly crossed for awesome news...

**Comment by yandeu** [comment]
Sorry not finished yet. My guess is that it take 2 month to add it (at my current speed, since it is not a top priority). But I will definitively add it. All my test where successful. 👍

**Comment by nipmarsh** [comment]
Hi,

Great lib, easy to use ;-)
I work on complex scenes with many objects and in my case the current implementation run slow.
Maybe, it will be much better with workers.
How far are you to integrate it ?

Sincerely
