### ISSUE TITLE
Positional values not working for compound shapes

### ISSUE THREAD

**Issue by wiledal** [enable3d/enable3d#198]
### Problem
Setting `x`, `y`, or `z` in a compound shape object does not change their position. They always end up at `0, 0, 0`.

### Expected
The compound shapes to be positioned according to their `x, y, z` values, relative to to their parent object, as outlined in the documentation.

 --- 

The issue can be observed in the official example as well:
https://enable3d.io/examples/compare-physics-body-shapes.html

**Comment by yandeu** [comment]
Thanks for reporting. The fix will be in the next release :)
