### ISSUE TITLE
add THREE.CSS3DRenderer support

### ISSUE THREAD

**Issue by HexaField** [enable3d/enable3d#20]
Hello, I've recently picked up enable3d for my own project, and hope I can continue to use it going forward.

It would be fantastic to add support for css element renderers, they are rather powerful and I am finding myself needing them for my project. Three's CSS renderers allow you to take html elements and put them into the 3d 'world' interactively.

Some links that may be useful
https://threejs.org/examples/?q=you#css3d_youtube
https://threejs.org/examples/?q=css#css3d_periodictable
https://stackoverflow.com/questions/24681170/three-js-properly-blending-css3d-and-webgl
https://stackoverflow.com/questions/37446746/threejs-how-to-use-css3renderer-and-webglrenderer-to-render-2-objects-on-the-sa

I have a lot of questions and some other suggestions, though this is the most pressing. Is there somewhere I can reach you directly? Thanks, Josh.

**Comment by yandeu** [comment]
> I have a lot of questions and some other suggestions, though this is the most pressing. Is there somewhere I can reach you directly? Thanks, Josh.

I have an email address, but I really just prefer open conversation on github. It's easier for me to manage. Simply open new issues :)

**Comment by HexaField** [comment]
I have figured out how to do this. I will try to create an example for you to include. Thanks.

**Comment by yandeu** [comment]
> I will try to create an example for you to include.

Would be great! Thanks a lot :smiley:
