### ISSUE TITLE
Low FPS rate on nvidia cards 

### ISSUE THREAD

**Issue by Myziak** [enable3d/enable3d#204]
I have a strange problem that only on computers with nvidia cards: my enable3d project has max 25 frames,
while on radeon graphics i have 60 fps. 

You can see example here: https://drop-editor.pl/gra2/  and check your FPS

on radeon hd 6850 (12 years GPU): 60 FPS
on rtx 3060 Ti: 20 FPS 

why is that happening?

**Comment by yandeu** [comment]
Your code looks wrong. Inside `Scene3D` you call `requestAnimationFrame()`.

Please take a look at [this example](https://enable3d.io/examples/post-processing.html).

Also, your assets are huuuge. Try https://squoosh.app/.
