### ISSUE TITLE
Upgrade Three.js to latest version

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#224]
**Describe the bug**

i 'm using [puppeteer](https://github.com/puppeteer/puppeteer) to make a headless game render

i fond a bug in the `THREE.FileLoader` , when i use FontLoader to load a font file , it will hang at the  `puppeteer`'s `headless` mode.

i manual copy-past the code from newgest version (now is r134) to rewrite a copy of the `FileLoader` `Loader` `FontLoader`, then it is work !!!

so i think the bundled threejs version need upgrade now.

**Comment by yandeu** [comment]
I have update enable3d to three r133.1

Still the same issue?

**Comment by yandeu** [comment]
Btw, you should not mix different versions of three.js. If enable3d uses three r133.1 you can't import and use r134.
