### ISSUE TITLE
Fix TypeScript errors

### ISSUE THREAD

**Issue by yandeu** [enable3d/enable3d#227]
Hello,

Im wondering if I'm doing something wrong. Im getting errors like these:

![image](https://user-images.githubusercontent.com/19927333/144712431-148b96f1-385e-4d84-9374-ebfa1c41a68c.png)

When I check node_modules, there is no src folder.

![image](https://user-images.githubusercontent.com/19927333/144712453-a6363e74-891c-4f4d-9870-7cd80cf2c89a.png)

I got a couple of other errors like these. But maybe I'm doing something wrong.

_Originally posted by @thijsvandrongelen in https://github.com/enable3d/enable3d/discussions/226_

**Comment by yandeu** [comment]
I will try to refactor/stricten all `tsconfig.json` and `webpack configs` to avoid these kind of errors.

**Comment by yandeu** [comment]
I'm working on it in the [refactoring branch](https://github.com/enable3d/enable3d/tree/refactoring).

**Comment by thijsvandrongelen** [comment]
Thank you

For now I added `"skipLibCheck": true,` to my `ts-config`

Sofar everything else is going great. Im converting my 2d game to 3d.

**Comment by yandeu** [comment]
After 12 commits today, I have released v0.24.1 with all fixes :)
