### ISSUE TITLE
Collision and displayed shape do not match in position/rotation

### ISSUE THREAD

**Issue by aboyobam** [enable3d/enable3d#233]
When I use `physics.add.box(...)` and then add the box to the scene, the hitbox and displayed box are not the same

The `mesh` is a arbitrary `THREE.Mesh` with a `BufferGeometry`, but this mesh is never added to the scene. Instead, the returned box is then added to the scene.
`collisionFlags` is set to static and the `collisionGroup` is unset.

Code:
```typescript
mesh.geometry.computeBoundingBox();
const bb = mesh.geometry.boundingBox;

const box = physics.add.box({
    width:  (bb.max.x - bb.min.x) * mesh.scale.x,
    height: (bb.max.y - bb.min.y) * mesh.scale.y,
    depth:  (bb.max.z - bb.min.z) * mesh.scale.z,
    x: mesh.position.x,
    y: mesh.position.y,
    z: mesh.position.z,
    collisionFlags,
    collisionGroup
});

scene.add(box);
```

The gray box is what gets rendered, the red box is how the collisions are detected
![Screenshot_7](https://user-images.githubusercontent.com/29310516/146288064-d2704462-e542-468f-a95e-4646911a0875.png)

I've also tried to do it with `physics.add.existing(...)` and tried all possible shapes there. Only convex and concave achieved a similar result, the other didnt detect collisions at all

All libraries (THREE, Ammo, Enable3d) were updated to the latest version on npm at the time.

**Comment by aboyobam** [comment]
Update: It works as intendet when I use:
```typescript
class MainScene extends Scene3D {
    create() { ... }
}
PhysicsLoader('/lib/ammo/kripken', () => new Project({ scenes: [MainScene], antialias: true }));
```

But not when I use the physics in headless mode with my custom scene.
I now switched to the standalone version wich should also do the job for me. But maybe consider investigating / tell me what I did wrong there.

**Comment by yandeu** [comment]
Hi @aboyobam 

I'm happy to help but need more information.

Can you please publish a simplified version of your game to github, where I can see the issue?

**Comment by aboyobam** [comment]
I found the culprit. The issue is not directly related to enable3d but more to Ammo.js

I forked [Ammo.js](https://github.com/kripken/ammo.js/) and compiled it myself. If i use the prebuilt version of Ammo.js it works as intended, but with the own compiled it fails. The only changes i made though are on `RaycastVehicle.cpp` to improve the friction calculation.

The issue is therefore on my side.

You could delete this issue if you want.
