### ISSUE TITLE
Allow access to custom canvas properties

### ISSUE THREAD

**Issue by DeeElGee** [enable3d/enable3d#24]
Hi,

Could you open up the custom canvas properties? Currently I believe only antialias is available to modify, the rest are swallowed up by defaults:

https://github.com/enable3d/enable3d/blob/81ff34751f9721d8ef24d53efec743b2607a043c/packages/common/src/customCanvas.ts#L35

Unless I'm misunderstanding how you pass these values in?

Thanks again!

**Comment by yandeu** [comment]
Antialias is the only parameter you can pass.

The customCanvas is only used for Phaser games. It takes the Phaser config default and adds support for three.js elements.

You can easily add your own canvas and context to your phaser games using:
```js
const config = {
  type: Phaser.WEBGL,
  scene: [MainScene],
  canvas: yourCustomCanvas,
  context: yourCustomContext
}
```
Also see this [Phaser 3 example](https://labs.phaser.io/edit.html?src=src\game%20config\custom%20webgl2%20canvas.js).
