### ISSUE TITLE
BufferGeometry Error

### ISSUE THREAD

**Issue by jeremyblalock** [enable3d/enable3d#244]
### Describe the bug

I am building a scene with physics for a robotics simulation project using ThreeJS and Enable3d. I have successfully setup several basic meshes (cubes, cylinders, spheres), and added physics for them using Enable3d's `physics.add.existing`, however I'm running into issues with more complex shapes that use BufferGeometry. I've tried importing a .glb file, as well as manually creating a BufferGeometry.

### Current Behavior:

1. Kinematic bodies refuse to move (they jitter but then snap back to their original positions, like a non-kinematic body would)
2. Debug mode does not show any bounding boxes around objects (tried 'hacd', 'convexMesh', 'concaveMesh' and other shapes)
3. 'box' shape works but results in a box that is just 1x1x1 positioned at the origin

So my question is, does Enable3d support BufferGeometry currently? Or alternatively is there another way to import models from Blender etc. in a way that Enable3d is able to understand.

### Code Example w/ Explicit `BufferGeometry`

```js
const geom = new Three.BufferGeometry()

const rawVertices = new Float32Array(
  _.flatten([
    [-1.0, 1.0, -1.0],
    [-1.0, -1.0, 1.0],
    [1.0, 1.0, 1.0],
    //  
    [1.0, 1.0, 1.0],
    [1.0, -1.0, -1.0],
    [-1.0, 1.0, -1.0],
    //  
    [-1.0, -1.0, 1.0],
    [1.0, -1.0, -1.0],
    [1.0, 1.0, 1.0],
    //  
    [-1.0, 1.0, -1.0],
    [1.0, -1.0, -1.0],
    [-1.0, -1.0, 1.0],
  ])  
)   

// itemSize = 3 because there are 3 values (components) per vertex
geom.setAttribute(
  'position',
  new Three.BufferAttribute(rawVertices, 3)
)   

geom.computeVertexNormals()

const mesh = new Three.Mesh(geom, material)

scene.add(mesh)
physics.add.existing(mesh,  { shape: 'hacd', collisionFlags: 2 })
```

Also, if this is not the right forum for these types of questions, I apologize in advance. Happy to take this elsewhere.

**Comment by yandeu** [comment]
Normally everything shoud work. Do you see some errors or warning in your browser's console?

**Comment by yandeu** [comment]
This works perfectly in my testing:
```ts
import { ExtendedMesh, PhysicsLoader, Project, Scene3D } from 'enable3d'
import * as Three from 'three'
import * as _ from 'lodash'

class MainScene extends Scene3D {
  async create() {
    this.warpSpeed()
    this.physics.debug?.enable()

    const geom = new Three.BufferGeometry()

    const rawVertices = new Float32Array(
      _.flatten([
        [-1.0, 1.0, -1.0],
        [-1.0, -1.0, 1.0],
        [1.0, 1.0, 1.0],
        //
        [1.0, 1.0, 1.0],
        [1.0, -1.0, -1.0],
        [-1.0, 1.0, -1.0],
        //
        [-1.0, -1.0, 1.0],
        [1.0, -1.0, -1.0],
        [1.0, 1.0, 1.0],
        //
        [-1.0, 1.0, -1.0],
        [1.0, -1.0, -1.0],
        [-1.0, -1.0, 1.0]
      ])
    )

    geom.setAttribute('position', new Three.BufferAttribute(rawVertices, 3))
    geom.computeVertexNormals()

    const material = new Three.MeshBasicMaterial({ color: 0x00ff00 })
    const mesh = new ExtendedMesh(geom, material) as any
    mesh.position.y = 2

    this.add.existing(mesh)
    this.physics.add.existing(mesh, { shape: 'hacd' })
  }
}

PhysicsLoader('/lib', () => new Project({ scenes: [MainScene] }))
```

**Comment by jeremyblalock** [comment]
This is what I get—no red lines & the object just falls right through the ground plane.

What version of ThreeJS & Enable3D did you get this to work with?

![image](https://user-images.githubusercontent.com/955154/151909439-07d09b00-8531-4063-bf7d-2e29e6771ebf.png)

There are no console errors currently, but it just does not seem to be getting the shape of the `BufferGeometry`.

**Comment by jeremyblalock** [comment]
This is my `package.json`:

```json
{
  "name": "arm",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "enable3d": "^0.25.1",
    "lodash": "^4.17.21",
    "matter-js": "^0.18.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6",
    "react-scripts": "4.0.3",
    "redux": "^4.1.2",
    "redux-form": "^8.3.8",
    "three": "^0.136.0",
    "web-vitals": "^1.0.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.16.7",
    "@babel/preset-env": "^7.16.11",
    "customize-cra": "^1.0.0",
    "eslint": "^7.11.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.1.2",
    "prettier": "^2.1.1",
    "react-app-rewired": "^2.1.11"
  },
  "scripts": {
    "start": "PORT=7000 react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "prettier": "prettier --write src/*.js \"src/**/*.js\"",
    "lint": "eslint src --max-warnings=0 --ext .js",
    "test:all": "CI=1 yarn test && yarn lint"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

And I also have this symlink setup, I'm not sure if this may be causing issues:

```
public/static/js -> ../../node_modules/three/examples/js/libs/
```

**Comment by jeremyblalock** [comment]
Ok, it looks like the issue was that symlink. I think we should maybe think about a better way of loading `ammo.wasm.wasm` / `ammo.wasm.js` directly from node_modules, as opposed to copy / pasted or symlinked. This wasn't explained very well in the docs.

**Comment by yandeu** [comment]
I don't want to distribute the ammo file via npm. (There are currently 2 popular ammo.js builds).

But I could offer a cdn to download both builds and write better docs.
