### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by rossmarinaro** [enable3d/enable3d#253]
phaser.js:107829 Uncaught TypeError: Cannot read properties of undefined (reading 'style')

This happens when I try to create  a new dom element by calling "this.add.dom(0, 0);".
 I did specify "dom: {createContainer: true} in config as well.

**Comment by yandeu** [comment]
Looks more like a Phaser issue. Please check the Phaser forum instead.

**Comment by rossmarinaro** [comment]
I had to use the template in order for this to work. Just npm i
@enable3d-phaser/extension caused problems like this.

**Comment by yandeu** [comment]
So now it is working?
