### ISSUE TITLE
Model mesh is inaccurate/simplified?

### ISSUE THREAD

**Issue by krpaul** [enable3d/enable3d#254]
**Describe the bug**
I created a model roulette table in Blender, exported to GLTF, and imported to enable3d.
This is the weird behavior I'm getting when add a ball with gravity to the scene:

https://user-images.githubusercontent.com/34616839/157124632-a3899ade-7ce5-4bac-82a7-4cd4866bc3d9.mp4

Essentially, the white ball falls along an imaginary line, one not defined by the mesh?  [blue line depicted here](https://user-images.githubusercontent.com/34616839/157124601-8f106d71-7308-4da1-8563-3028f44a2409.png)

Here is the example source with the compressed glb file included:

[src.zip](https://github.com/enable3d/enable3d/files/8201144/src.zip)

Any ideas why the true mesh isn't the red one that is depicted?

**Comment by yandeu** [comment]
You have to use another physics shape. Have a look at https://enable3d.io/examples/compare-physics-body-shapes.html.
