### ISSUE TITLE
Problem with loading same model twice or more

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#26]
Hello, im using phaser3 extension.

Since you introduced the model cache, there have been problems with displaying objects, that is:

I can't use the same 3d model more than once. 
If I create a new object that reads the same model to other object, it will not be displayed. 

If I have a character which I attach a sword and armor, if this sword has already been used by another object (player), it will not be displayed on the next one.

**Comment by yandeu** [comment]
Do you use the `clone()` method?

The code below will add 3 monkeys on the scene:
```js
async preload() {
  await this.load.gltf('suzanne', '/assets/glb/suzanne.glb')
}

create() {
  this.warpSpeed()

  const gltf = this.cache.get('suzanne')
  const suzanne = gltf.scene.children[0]

  const add = (x, y, z) => {
    const object = new ExtendedObject3D()
    object.position.set(x, y, z)
    object.add(suzanne.clone())
    this.add.existing(object)
    return object
  }

  add(3, 1, 0)
  add(0, 1, 0)
  add(-3, 1, 0)
}
```

**Comment by Trusiak** [comment]
hmm it doesnt not work. Maybe it's just because im using v0.18 version?


```
export class Player extends ExtendedObject3D {
    constructor(scene, playerInformation) {
        super()

        this.scene = scene;
        this.model = scene.third.cache.get(playerInformation.model).children[0]

        this.weapon = scene.third.cache.get(playerInformation.weapon)
        this.hair = scene.third.cache.get(playerInformation.hair)
        this.animationIdle = scene.third.cache.get(playerInformation.animationIdle)
        this.skills = playerInformation.skills;

        this.setPossitionOnScene();
        this.attachObjectIntoCharacter();
        this.runAnimation();

        this.add(this.model.clone())
        scene.third.add.existing(this);
    }
```

and this code throw me an error: Cannot read property 'frame' of undefined

**Comment by yandeu** [comment]
I guess you are using fbx models then. I believe fbx models can't be used more than once. `this.load.fbx()` does not only load the fbx model, it does also parse it. So if it gets cached, you can't use it twice.

I guess I will have to implement a new cache logic specifically for fbx models.

Just do something like this for the moment. (this.load.fbx returns a promise)
```js
// robot 1
const robot1 = await this.load.fbx('/assets/fbx/Idle.fbx')
robot1.scale.set(0.05, 0.05, 0.05)
robot1.position.set(5, 2, 0)
this.add.existing(robot1)

// robot 2
const robot2 = await this.load.fbx('/assets/fbx/Idle.fbx')
robot2.scale.set(0.05, 0.05, 0.05)
robot2.position.set(-5, 2, 0)
this.add.existing(robot2)
```

**Comment by yandeu** [comment]
Actually, I think, I will make `this.load.fbx('/assets/fbx/Idle.fbx')` the default way to load things again. The models are cached internally. It does not matter if you call `this.load.fbx('/assets/fbx/Idle.fbx')` once or 10 times, the browser request your model only once.

**Comment by yandeu** [comment]
I just simplified the code a lot. In version 0.19.1, you will be able to do the following. Works with texture, svg, fbx and gltf/glb files. _Sorry for always changing the api, but since it is in a very early stage, I sometimes have to._

```js
async preload() {
  // does just preload the files but not parsing it.
  await this.load.preload('robot', '/assets/Idle.fbx')
  await this.load.preload('grass', '/assets/grass.jpg')
}

async create() {
  this.warpSpeed()

  this.load.texture('grass').then(grass => {
    this.add.box({}, { phong: { map: grass, transparent: true } })
  })

  // robot1 - parse with async/await
  const robot1 = await this.load.fbx('robot')
  robot1.scale.set(0.05, 0.05, 0.05)
  robot1.position.set(5, 0, 0)
  this.add.existing(robot1)

  // robot2 - parse with callback
  this.load.fbx('robot').then(robot2 => {
    robot2.scale.set(0.05, 0.05, 0.05)
    robot2.position.set(-5, 0, 0)
    this.add.existing(robot2)
  })
}
```

_Btw, don't upgrade to v0.19.0 just yet. There is a nasty bug :/_

**Comment by Trusiak** [comment]
Did you implement the final version of this loader? Cause before moment i updated enable to 0.19.1 version, and this code: 

`temp_loader(){
         this.preload.fbx('player', '/assets/sura_1.fbx')
    }
`

does not work - throws me error: this.load.preload is not a function.
So i looked up to examples and everything works there on 0.19.1 old API.

**Comment by yandeu** [comment]
If you are using phaser, use `this.third.load.preload()`. (Has to be after `this.accessThirdDimension()`)

**Comment by Myziak** [comment]
I refresh the topic, unfortunately on versioni 0.23.0 it does not work well - after loading gltf it gives such an error: `THREE.Object3D.add: object not an instance of THREE.Object3D. `

This is because the preloaded model looks like a non-model:

![image](https://user-images.githubusercontent.com/75075069/195441813-2ef7c9b9-52be-49e3-85c2-adb29debf250.png)

co się zmieniło w API?
