### ISSUE TITLE
Error after npm install (Cannot find namespace 'Ammo')

### ISSUE THREAD

**Issue by ViROscar** [enable3d/enable3d#27]
Greetings.

Im trying this library to implement physics on my current three.js 

After running "npm i enable3d" and trying to run my page, the console mark errors in "@enable3d/ammo-physics" about not finding Ammo.

i dont know how to work arround this or if i miss something.

![imagen](https://user-images.githubusercontent.com/8218404/85240784-07603780-b3ff-11ea-8951-da8f335d0111.png)

**Comment by yandeu** [comment]
Hmm. Not sure what causes it. But if you only want to add physics to your three.js scene, you do not need `enable3d`, only `@enable3d/ammo-physics`.

I made a starter template 3 days ago using typescript, three.js and @enable3d/ammo-physics.
You could use it as a reference to fix it.
https://github.com/yandeu/three-project-template.

Please tell me if this helped, otherwise I will have a closer look tomorrow.

**Comment by ViROscar** [comment]
thank, i will try to use it.

perhaps the problem is my current enviroment. I'm installing enable3D on an Angular enviroment.  Even if i create a class similar to the one in the "Getting Started" page from zero, i still get the message.

**Comment by yandeu** [comment]
Maybe try to manually include the [ammo.d.ts](https://github.com/enable3d/enable3d/tree/master/types) types to your project.

**Comment by ViROscar** [comment]
Hi. Sorry for taking some time to answer.

As you said, i include ammo.d.ts in the project but i will try to explain what i did.

- I copy **ammo.d.ts** into the "**src**" folder in the project
- I copy the files "**ammo.js**", "**ammo.wasm.js**" and "**ammo.wasm.wasm**" into the "**asset**" folder in the project (so instead of **PhysicsLoader('/lib', () => new Project(config))**  i use **PhysicsLoader('/assets', () => new Project(config))**)
- I modify the way that some of the file in @enable3d import EventEmitter  ( instead of **import  EventEmitter from 'eventemitter3';** i use **import * as EventEmitter from 'eventemitter3';** )

By doing  that i was finally able to run the example exercise.

![imagen](https://user-images.githubusercontent.com/8218404/85362850-25a06300-b4e5-11ea-98fe-996e903b15f5.png)

Many thanks!!

**Comment by yandeu** [comment]
Thanks for letting me know the steps you took to make it work!

- In the next version, ammo.d.ts will be integrated into the library (see d62ebbd519ed6d2a4c9d354a156e47e9f5807a8d)
- Yes, the PhysicsLoader has to point to your ammo files. Was it hard to figure it out? Do I have to document it better?
- I already had issues with EventEmitter3 in another library. I think there was a bug between versions 4.0.0 and 4.0.4. I have updated it to the latest version. `import * as EventEmitter from 'eventemitter3'` and `import {EventEmitter} from 'eventemitter3'` throws an error when I compile it. Hopefully by simple upgrade it to the latest version will fix it. (see 83dae7c834285c3237d8ee3483bf7a49fafc3e72 and 8e02f722fc5715526ed194721f4ada05c352bdd3)

**Comment by ViROscar** [comment]
About the PhysicsLoader, i just noticed that i need to point to ammo because the browser throws an error related to those. As i said, this look like a problem with my environment having in mind that i need a different configuration for an angular application, it will be cool if i dont need to configure that but for now that is not a problem and i think that i can work around this (Maybe could be great to specify the environments where enable3D is already tested) 

One more thing. In my case the example from getting started is a little bit different to the actual demonstration on "https://enable3d.io/examples/standalone-mode.html" since in the one of the example i think is missing the "box" declaration and initialization, however is easy to figure out.

Many Thank!!, i think i can close the issue. i will let you know if something else happens.
