### ISSUE TITLE
Hi is attach available?

### ISSUE THREAD

**Issue by EfimSafonov** [enable3d/enable3d#270]
I want to attach sword or bow to hand, but can’t find attach function, is this feature released? If attach not available now could you give link for attach algorithms? After good performance and render I will make merge request to your project

**Comment by vitalspace** [comment]
MAYBE 

https://enable3d.io/examples/fbx-loader-and-animations-hitbox.html

Or 

https://enable3d.io/examples/types-of-constraints.html

or 

`          this.player = new THREE.Group()
          this.player.name = 'player' // <-- set a name if you haven't already
          this.player.position.setY(2)
          const body = this.third.add.box(
            { height: 0.8, y: 1, width: 0.4, depth: 0.4 },
            { lambert: { color: 0xffff00 } }
          )
          const head = this.third.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0xffff00 } })
          this.player.add(body, head)
          this.player.position.setY(5)
          this.third.add.existing(this.player)
          this.third.physics.add.existing(this.player)
          this.player.body.setAngularFactor(0, 0, 0)
          this.player.body.setFriction(0.8)
`

https://enable3d.io/examples/camera-lerping-and-player-controls.html

**Comment by EfimSafonov** [comment]
Thank you so much, first links is currently that i looking for

**Comment by yandeu** [comment]
I have improved the hitbox example. Please have a look:
https://enable3d.io/examples/fbx-loader-and-animations-hitbox.html
