### ISSUE TITLE
Preloading assets and using them in multiple scenes

### ISSUE THREAD

**Issue by CurtisGreen** [enable3d/enable3d#28]
## Issue preloading assets
 This example [here](https://github.com/enable3d/enable3d-website/blob/master/src/examples/load-and-use-textures.html) works and lets you load textures. However, reloading the scene, or going to a scene that also uses this texture will throw an error:
`[object%20HTMLImageElement]:1 GET http://localhost:8000/[object%20HTMLImageElement] 404 (File not found)`

I believe this is because it is trying to load the same file twice. 

I tried using the method of preloading shown in this example [here](https://github.com/enable3d/enable3d-website/blob/master/src/examples/project-options-and-multiple-scenes.html) but I wasn't able to get it to work. `Project` is undefined and `this.load.preload` says it doesn't exist. 

Also, the same error happens for `this.third.warpSpeed("ground");` when you load it for the second time.

Thanks in advance.

**Comment by yandeu** [comment]
You are using enable3d with Phaser, I guess?

I have updated the 2 examples below, to show how it works:
- https://enable3d.io/examples/texture-cube.html
- https://enable3d.io/examples/load-and-use-textures.html

Hope this helps :)

**Comment by CurtisGreen** [comment]
Yes, I am using enable3d with phaser. Thanks for the quick response!

If I have questions in the future that are not yet covered by the examples/documentation should I make another issue like this or do you have another preferred method? 

Thanks for your work so far, it looks very nice 👍

**Comment by yandeu** [comment]
You're welcome :)

Yes, just open a new issue. Or a new topic in the Phaser Forum mentioning `@yannick`.
