### ISSUE TITLE
enable3d 0.25 fails to build with esbuild

### ISSUE THREAD

**Issue by brianpeiris** [enable3d/enable3d#287]
**Describe the bug**
When using esbuild to build the simplest enable3D example, the build fails with the following error:
```
✘ [ERROR] Could not resolve "three/examples/jsm/deprecated/Geometry"               
                                                                                   
    node_modules/@enable3d/three-graphics/jsm/plugins/heightmap.js:9:25:           
      9 │ import { Geometry } from 'three/examples/jsm/deprecated/Geometry';       
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
                                                                                   
  The module "./examples/jsm/deprecated/Geometry" was not found on the file system:
                                                                                   
    node_modules/three/package.json:14:24:                                         
      14 │     "./examples/jsm/*": "./examples/jsm/*",                             
         ╵                         ~~~~~~~~~~~~~~~~~~                              
```

There are several other errors with resolving imports that are similar. This was not an issue with enable3d 0.24. 

I'm unsure if the root cause is in three.js, or esbuild, or enable3d, but this three.js issue implies that enable3d should include the file extension in the import to avoid this issue. https://github.com/mrdoob/three.js/issues/23696
That is 
`import { Geometry } from 'three/examples/jsm/deprecated/Geometry';` 
should be 
`import { Geometry } from 'three/examples/jsm/deprecated/Geometry.js';`. 
I tested this temporarily by editing the problematic files in node_modules, and that seemed to resolve it.

I've got a simple reproduction in this repo. Just run `npm install` and `npm run build`. https://github.com/brianpeiris/test-enable3d/

**Comment by brianpeiris** [comment]
My guess is webpack assumes a .js extension by default. The three.js issue implies that the esmodule standard is to include the file extension. By omitting it, you will run into issue like this, where the behavior of bundler implementations differ. That said, the behavior around the "exports" section in three.js' package.json file is not standardized, as far as I can tell, so I'm not sure what the correct solution is here.
Do you think I should file a bug against esbuild instead?

**Comment by brianpeiris** [comment]
Here is node.js' documentation stating that file extensions should be included: https://nodejs.org/api/esm.html#mandatory-file-extensions

**Comment by yandeu** [comment]
Has been fixed in 62e00afe7995cbfc15b6183db52aebf7d11e538b, ef649817a6ad28060505ac20026922406877e43c and fb9ec72201312d7add33527c6aaa3e0721dde8f6.

**Comment by brianpeiris** [comment]
Great! Thanks. I'll close this now, since this should be resolved with the next release.

**Comment by yandeu** [comment]
You're welcome :)
