### ISSUE TITLE
Problems adding physics to a .glb object

### ISSUE THREAD

**Issue by ViROscar** [enable3d/enable3d#29]
Hello Again.

I’m trying to load an object into a scene. based on the code that is used for the example of the medieval book i manage to load it

_Code_:
```
let model = this.load.preload('model', '/assets/sceneseria.glb');
    let object = await this.load.gltf('model');
    object.scenes[0].scale.set(100, 100, 100);
    const modddl = new ExtendedObject3D()
    modddl.name = 'scene'
    modddl.add(object.scenes[0])
    this.add.existing(modddl);
```
_Result (is a boring and generic office 🙁)_:
![imagen](https://user-images.githubusercontent.com/8218404/85819400-2a5d5500-b739-11ea-824a-d1bf0368c8cb.png)

Now I’m trying to add physics but if i try to use the code like the one of the example, i got compilation error.

_Using this_:
```
modddl.traverse(child => {
      this.physics.add.existing(child, {
        autoCenter: false,
        collisionFlags: 1,
        offset:{x:0,y:0,z:0}
      })
    })
```
_i got this_:
![imagen](https://user-images.githubusercontent.com/8218404/85819709-2bdb4d00-b73a-11ea-863b-18ee694de24b.png)

if i ignore that compliation error, the model is loaded but the browser (firefox) throws this error:

![imagen](https://user-images.githubusercontent.com/8218404/85820027-fc791000-b73a-11ea-959c-ecbe1fb7fb1b.png)

im testing the collisions with a generic sphere

```
this.player = this.physics.add.sphere({ y: 200, x: 4, z:30, radius: 1 })
    this.player.body.setAngularFactor(0, 1, 0)
    this.player.body.setFriction(0); 
```

the collision is detected only in the test area provided by enable3d but not in the model.
i dont know what to do to fix

**Comment by yandeu** [comment]
The child can be anything (use type `any`) and check if it is an mesh.

Try:
```ts
// debug the physics
this.physics.debug.enable()

// add physics to the model
model.traverse((child:any) => {
  if (child.isMesh) {
    // maybe you do not want to add all children? You can filter them by name.
    console.log(child.name)

    this.physics.add.existing(child), {
      shape: 'concave',
      mass: 0,
      collisionFlags: 1,
      autoCenter: false,
      offset:{x:0,y:0,z:0}
    })
  }
})
```

**Comment by ViROscar** [comment]
Im working with your recomendation. 
I will try to give a fedback as soon as posible. Thanks.

**Comment by ViROscar** [comment]
As i said, I’m going to describe the situation.

It Works. Using your code recommendation it was possible to detect the model and fix the compilation error.

Also I had to modify some of the way that I use to change the scale of the model. If I scale the model outside the “traverse” method, the model and the physic area will not match. To change the scale of the model and preserve the physic area is necessary to do inside the “traverse” method.

Here is my code and the result.

```
let model = this.load.preload('model', '/assets/sceneseria.glb');
    let object = await this.load.gltf('model');
    const modddl = new ExtendedObject3D()
    modddl.name = 'scene'
    modddl.add(object.scenes[0]);
    this.add.existing(modddl);

    modddl.traverse((child: any) => {
      if (child.isMesh) {
        child.scale.set(0.5,0.5,0.5);
        this.physics.add.existing(child, {
          shape: 'concave',
          mass: 0,
          collisionFlags: 1,
          autoCenter: false,
          offset: { x: 0, y: 0, z: 0 }
        }
        );
      }
    });
```

![giffi2](https://user-images.githubusercontent.com/8218404/85929083-8e863300-b877-11ea-8ee7-9c4ec74b123e.gif)

**Many thanks for your help!**

**Comment by yandeu** [comment]
Looks great!

**Comment by ViROscar** [comment]
If you wanna see it running. im hosting the example here:

https://viroscar.github.io/Enable3Dexample1/

**Comment by yandeu** [comment]
Thanks for sharing. Runs pretty smooth :smiley: I'm happy to see programmers using my tools :smiling_face_with_three_hearts:
