### ISSUE TITLE
[Q/A] How and Why questions

### ISSUE THREAD

**Issue by RollinSafary** [enable3d/enable3d#3]
Hi, this project looks very interesting for me, I'm experienced Phaser 3 developer, and I've some questions about this project, and I think many people would be interested, so everybody can ask questions here. Of course if you'll have a time to answer them.
So let's start.

1) I haven't read your code, but need to ask, what was the reason to attach this project to Phaser 3. In other words, I want to understand how Phaser 3 helps you in rendering.
2) I've saw just one example and there you've created MainScene from Scene3D. Does Scene3D extends from Phaser.Scene and is this logic true for other 3D game objects ?
3) I'm understanding that it's a mix of Phaser 3 (2D framework) and Three JS (3D framework), but why it's better than main Three JS. What makes need of creating this kind project.

P.S. I'm just trying to understand how and when I can use this tool.
P.S.S. I think answers of these questions can be very interesting for everyone. I'm using TypeScript as main development language, so maybe I can help you later with this project, but I want to be sure, that it costs for that, of course if you need for help.)

Thank you for your work.

**Comment by yandeu** [comment]
I'm glad that you are interested in my project :)

- I did not attach the project to Phaser. This project was specifically designed for Phaser.
- Phaser 3 does not help with the rendering.
- Yes, Scene3D extends from Phaser.Scene. No, Scene3D is the only class based on a Phaser class. Everything else extends from three.js or ammo.js.
- Phaser 3 is a 2D game framework. Three.js is a 3D graphics library. Phaser 3 provides everything a game framework  needs. DataManager, TweenManager, SceneManager, InputManager, Loaders, SoundManager and more. Three.js provides 3D graphics. And there is also ammo.js, which provides all the 3D physics.

It is just a great combination. Phaser, three.js and ammo.js combined can compete with other frameworks like Babylon.js or PlayCanvas.

The great thing about enable3d, is that is aims to use a similar api like Phaser. So everyone who knows Phaser, can easily get started with 3D object and physics.

Hope this helps :)

**Comment by RollinSafary** [comment]
@yandeu thank you for the answer. Yea mostly I've got what you've done, and it's amazing.
And last one question. Must user (I mean developer), know Three.js and ammo.js to use, or you're planning to have own docs?

**Comment by yandeu** [comment]
I do not think you have to know much about three.js to get started. You will certainly have to take a look at [Vector3](https://threejs.org/docs/#api/en/math/Vector3) and learn few things about the different materials.

Same for ammo.js. Everything is handled very well by enable3d. The only thing to know is when to use [which shape](https://enable3d.io/examples/compare-physics-body-shapes.html) and what the differences about dynamic, static, kinematic and ghost (aka sensor or NO_CONTACT_RESPONSE) objects are.

I'm a bad writer, so hopefully I do not have to write docs if I continue to publish [great examples](https://enable3d.io/examples.html). I guess a simple "how to get started" video is easier to do than writing docs.

**Comment by yandeu** [comment]
You can now post questions in the discussion section: https://github.com/enable3d/enable3d/discussions
