### ISSUE TITLE
Custom THREE.ObjectLoader for Extended Objects

### ISSUE THREAD

**Issue by HexaField** [enable3d/enable3d#30]
It would be great to extend the Object3D .toJSON() and JSON parser for threejs (THREE.ObjectLoader) to work with the extended objects. If there is a way to save and load to json already I apologise, I did spend some time looking. Thanks.

**Comment by yandeu** [comment]
I will implement the ObjectLoader.

But you should already be able to make it work manually. The ExtendedObject3D already extends all Object3D functionalities.

Maybe you want to share your code?

**Comment by yandeu** [comment]
I have implemented the ObjectLoader (e32baa89122be730f7e76a7dbd8fe427d36c21a0).

This is how you will be able to do it:
```js
async preload() {
  this.load.preload('plane', '/assets/plane.json')
}

async crete() {
  this.load.object('plane').then((obj: any) => {
    // in most cases ExtendedObject3D is not needed
    // to be able to add physics, just add a name
    obj.name = `object-${obj.id}`
    this.scene.add(obj)
  })
}

// or without preloading
this.load.object('/assets/plane.json').then((obj: any) => { ... }

// async/await is of course also supported
const obj = await this.load.object('/assets/plane.json')
```

If you do already have a THREE.ObjectLoader in your project and want to add physics to it, just set the name as in the example above.

Hope this helps :)

**Comment by HexaField** [comment]
This won't save and load the information specific to Extended objects though (physics body velocity for example), that's more what I'm looking for.

**Comment by yandeu** [comment]
Well it will not be 100% an ExtendedObject3D, but most of the code of the ExtendedObject3D is only related to animations anyways. When you use `this.physics.add.existing(obj)`, the object will receive a physics body. Of course if you use TypeScript, you won't get the fancy IntelliSense. Fortunately, you can add the ExtendedObject3D type to any object you want.

Try this:  
_(everything, except animations, should work)_

```ts
// add ExtendedObject3D as the type
this.load.object('plane').then((obj: ExtendedObject3D) => {

  // add a name (this is required for physics)
  obj.name = `object-${obj.id}`

  this.scene.add(obj)

  // add a physics body
  this.physics.add.existing(obj, { shape: 'convex' })

  // use the physics body with IntelliSense
  obj.body.applyForceY(5)
})
```

**Comment by yandeu** [comment]
Actually, if you look at the examples, I always use the following approach:

```ts
// preload the object
this.load.preload('plane', '/assets/plane.json')

// parse the object
this.load.object('plane').then(obj => {

  // create the extendedObject3D
  const plane = new ExtendedObject3D()

  // add the object as a child
  plane.add(obj)

  // add plane to the scene
  this.scene.add(plane)

  // add a physics body
  this.physics.add.existing(plane, { shape: 'convex' })

  // use the physics body with IntelliSense
  plane.body.applyForceY(5)
})
```

**Comment by HexaField** [comment]
I've solved this by storing the physics body data in userData for each object. It would be nice to have a native loader for saving/loading aspects of a physics body such as shape, velocity, collision flags etc but I can manage doing this manually for now. Thanks for your help.
