### ISSUE TITLE
Objects floating above floor

### ISSUE THREAD

**Issue by HexaField** [enable3d/enable3d#32]
<img width="1440" alt="Screen Shot 2020-07-18 at 12 58 17" src="https://user-images.githubusercontent.com/10372036/87843358-5b274900-c8f7-11ea-97e1-4428c4095ba1.png">

Pictured here is a character model and two boxes with the camera sitting at y=0 in a room made of plane geometries. While the boxes sit flush with eachother, neither the boxes nor the character sit flush on the ground.

Below are the settings each for the floor, box and character.

Floor
`this.physics.add.existing(this.floor, {shape:'plane', collisionFlags:1, mass:0})`

Box
`this.physics.add.existing(this.box, {shape:'box', collisionFlags:0, mass:1})` 

Character
 ```

this.collider = this.physics.add.existing(this.group, {
    shape: 'box',
    width: 0.6,
    depth: 0.4,
    height: this.modelHeight,
    offset: { x : 0, y: -this.modelHeight / 2, z:0},
    autoCenter: false,
    mass: 1
})
this.group.body.setCollisionFlags(0);
this.group.body.setFriction(0.8)
this.group.body.setBounciness(0)
this.group.body.setAngularFactor(0, 0, 0)
this.group.body.setLinearFactor(1, 1, 1)

```

**Comment by yandeu** [comment]
Try to use a thin box for the floor Instead of a plane.

**Comment by HexaField** [comment]
I've found the culprit. Ammo/Bullet have a margin setting for collision shapes that scales with the extents of a mesh, though I don't see a way to access this setting currently with enable3d. I will work on a PR that allows you to send custom options through to the [createCollisionShapes](https://github.com/enable3d/enable3d/blob/master/packages/ammoPhysics/src/three-to-ammo.js#L45) function, as right now it is simply hardcoded to be the type and concave or not.
