### ISSUE TITLE
The error that "require" cannot be used in rollup packaging occurs!

### ISSUE THREAD

**Issue by xqsh** [enable3d/enable3d#329]
**Describe the bug**

**Have a question?**
Join the [discussions](https://github.com/enable3d/enable3d/discussions) instead.
<img width="405" alt="image" src="https://user-images.githubusercontent.com/30945109/193082778-c41922ef-0e94-4181-baed-7130fda7fbff.png">

**Comment by xqsh** [comment]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/30945109/193084113-7d381b86-0597-4807-bafd-56c5056e84aa.png">
If this is done, it will be used normally

**Comment by xqsh** [comment]
> 

I don't think "import" and "require" should be used together. Of course, this is my personal opinion   ~haha

**Comment by yandeu** [comment]
Already fixed in https://github.com/enable3d/enable3d/commit/47d40544b11c4869a9544bfce73935da89f492bd.

Before releasing a new version, I would love to update to a three.js version higher than 0.141.0 first.

**Comment by xqsh** [comment]
threejs just updated 0.145.0 10 hours ago~

**Comment by xqsh** [comment]
> Already fixed in [47d4054](https://github.com/enable3d/enable3d/commit/47d40544b11c4869a9544bfce73935da89f492bd).
> 
> Before releasing a new version, I would love to update to a three.js version higher than 0.141.0 first.

threejs just updated 0.145.0 10 hours ago~

**Comment by yandeu** [comment]
I have just release a new version.
