### ISSUE TITLE
ObjectLoader does not work when used after preloading model files

### ISSUE THREAD

**Issue by PtrBld** [enable3d/enable3d#333]
**Describe the bug**
There is a problem in the loader plugins that the ObjectLoader is not working anymore if any model file (ending with `/\.fbx$|\.glb$|\.gltf$/`) was preloaded before. 

The problem seems to originate in the [loaders.ts](https://github.com/enable3d/enable3d/blob/370da7c44d2168b981dca06c33698fc8a82a4ef0/packages/threeGraphics/src/plugins/loaders.ts) preload function, where once such a file is loaded the FileLoader responsetype is set to 'arraybuffer' for all files that are preloaded afterwards (``line 66``).

I think in the else-case the responsetype should be set to `undefined` to make the behavior more error-proof and obvious. The order in which objects are preloaded would make no difference in this scenario. What do you think?

**Comment by yandeu** [comment]
Thanks for reporting. I will have a closer look once in my office.

**Comment by yandeu** [comment]
I could not reproduce this error. The code below works fine.

```ts
class MainScene extends Scene3D {
  async preload() {
    await this.load.preload('man', '/assets/box_man.glb')
  }

  async create() {
    this.warpSpeed()

    this.load.gltf('man').then(gltf => {
      const child = gltf.scene.children[0]
      child.position.setX(-1)
      this.scene.add(child)
    })

    this.load.gltf('man').then(gltf => {
      const child = gltf.scene.children[0]
      child.position.setX(1)
      this.scene.add(child)
    })
  }
}
```

**Comment by PtrBld** [comment]
Hi, sorry this is not what I meant. See example code below:

Working:
``` typescript
this.third.load.preload('ground', 'assets/ground.json');
this.third.load.preload('robot', 'assets/robot.glb');

this.third.load.object('ground').then((object) => {
  //anything
});
```

Not working:
``` typescript
this.third.load.preload('robot', 'assets/robot.glb');
this.third.load.preload('ground', 'assets/ground.json');

this.third.load.object('ground').then((object) => {
  //anything
});
```

Error message:
``THREE:ObjectLoader: Can't parse assets/OBJ/ground.json. Unexpected token 'o', "[object ArrayBuffer]" is not valid JSON``

As I said this is because line 66 in [loaders.ts](https://github.com/enable3d/enable3d/blob/370da7c44d2168b981dca06c33698fc8a82a4ef0/packages/threeGraphics/src/plugins/loaders.ts) the responsetype is set to 'arraybuffer' for all files that are preloaded afterwards (in this case after `robot.glb`).

**Comment by yandeu** [comment]
I see. I guess this would fix it?

```diff
public async preload(key: string, url: string) {
  this.cache.add(key, url)

  return new Promise(resolve => {
    const isModel = /\.fbx$|\.glb$|\.gltf$/.test(url)
    const isTexture = /\.jpe?g$|\.png$/.test(url)

    if (isTexture) {
      this.textureLoader.load(url, texture => {
        return resolve(texture)
      })
    } else {
      if (isModel) this.fileLoader.setResponseType('arraybuffer')
+     else this.fileLoader.setResponseType('undefined')
      this.fileLoader.load(url, file => {
        return resolve(file)
      })
    }
  })
}
```

**Comment by PtrBld** [comment]
Yes, that should do it. However, I think `undefined` without quotations would be better.

**Comment by yandeu** [comment]
The `responseType` can be `undefined` or `string`, but `setResponseType` only takes a `string`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/src/loaders/FileLoader.d.ts

**Comment by PtrBld** [comment]
True. Thanks for your help!

**Comment by psociety** [comment]
This also seems to happen if you use load twice for the same fbx:
```js

let object;
const key = 'assets/fbx/Male.fbx'

object = await this.third.load.fbx(key);
object = await this.third.load.fbx(key);
```

It cries with a:
```
three.module.js:43861 Uncaught (in promise) TypeError: url.lastIndexOf is not a function
    at LoaderUtils.extractUrlBase (three.module.js:43861:1)
    at FBXLoader.load (FBXLoader.js:79:51)
    at loaders.js:157:1
    at new Promise (<anonymous>)
    at Loaders.fbx (loaders.js:156:1)
```

enable3d v0.25.4
Phaser v3.55.2 (WebGL | Web Audio)

**Comment by yandeu** [comment]
Try to preload your fbx file first.

**Comment by psociety** [comment]
I cannot preload it, because the file to be loaded is dynamic (the name i set was an example).
Ex: multiplayer with 50 different avatars, not going to preload all of them.

I just added my own cache as workaround:
```js
// enable3d has a bug where FBXs can't be loaded more than once
  // as they are saved as ArrayBuffers on cache
  async loadFBX (key) {
    if (this.fbxs[key]) {
        return this.fbxs[key];
    }
    this.fbxs[key] = await this.currentScene.third.load.fbx(key);

    return this.fbxs[key];
  }
```
