### ISSUE TITLE
How to trigger 'finished' event on new enable version?

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#34]
Hello, im using phaser3 extension.

1. How can i trigger 'finished' event on animation mixer in new library version?
The last time, we could did the following: 

```
this.mixer = this.scene.third.animationMixers.create(this)
        this.mixer.timeScale = 1;
        this.mixer.addEventListener('finished', () => {
            this.setAction('Idle')
        });
```

now we have: 

`this.third.animationMixers.add(robot.animation.mixer)`

and trigger like this: 

`this.animation.mixer.addEventListener('finished', () => {
            console.log("it's working!")
        });`

does not working. 

2. How we now can setLoop of the animation? ^^

**Comment by Trusiak** [comment]
We need to change the "animation loop flag" on false, because default is true. 
We can do that, during trigger play method on animation:

` player.animation.play("animation_key", 500, false);`

of course, the "finished" event we should trigger from this.animation.mixer not this.mixer like in old version

**Comment by yandeu** [comment]
Ok. Thanks :)
