### ISSUE TITLE
Hide Powered by Enable3D?

### ISSUE THREAD

**Issue by yandeu** [enable3d/enable3d#351]
Can we avoid showing in console about Powered by Enable3D?

_Originally posted by @Smithangshu in https://github.com/enable3d/enable3d/discussions/350_

**Comment by jpguzman** [comment]
Depending on how you are importing Enable3D, you can look for this in your enable3d.js or enable3d.min.js file and remove it.

`console.log("%c %c %c %c %c Powered by enable3d v0.25.3 %c https://enable3d.io/","background: #ff0000","background: #ffff00","background: #00ff00","background: #00ffff","color: #fff; background: #000000;","background: none");`
