### ISSUE TITLE
Heightmap with Texture

### ISSUE THREAD

**Issue by georgzoeller** [enable3d/enable3d#36]
First off, congratulations, this looks great and is really easy to use.

Haven't been able to find documentation yet on this - is it possible to map a texture the heightmap?

**Comment by HexaField** [comment]
Check out the website, it has some basic docs, and lots of examples. https://enable3d.io/

**Comment by yandeu** [comment]
Thanks! Glad you like it :)

I have just updated the [heightmap example](https://enable3d.io/examples/create-3d-geometry-from-png-file.html). 

Hope it helps :)

**Comment by georgzoeller** [comment]
thank you, super helpful!

**Comment by yandeu** [comment]
You're welcome.

And here is an example how you would do it using shaders http://stemkoski.github.io/Three.js/Shader-Heightmap-Textures.html.  
(I have not tested it, but it looks nice)

**Comment by georgzoeller** [comment]
:) Thanks, 
![image](https://user-images.githubusercontent.com/2640999/89068548-0d551b00-d3a4-11ea-962e-9e22653bbbbf.png)

**Comment by yandeu** [comment]
Looks nice :)
