### ISSUE TITLE
Water issue on phaser 3.25.beta0

### ISSUE THREAD

**Issue by georgzoeller** [enable3d/enable3d#37]
Adding water to my scene 

```
      waterTextures = await Promise.all([
        this.third.load.texture('/dev_assets/Water_1_M_Normal.jpg'),
        this.third.load.texture('/dev_assets/Water_2_M_Normal.jpg')
        ])

      water = this.third.misc.water({
        y: 1,

        normalMap0: waterTextures[0],
        normalMap1: waterTextures[1]
      })
```

Causes all other game objects (sprites, texts) the become a rendertarget forr the entire sceene...
![image](https://user-images.githubusercontent.com/2640999/89069572-f9aab400-d3a5-11ea-9ec6-951279a1ae12.png)
![image](https://user-images.githubusercontent.com/2640999/89069690-37a7d800-d3a6-11ea-80ed-a88aac69113e.png)

This may be related to rendering optimizations made in phaser 3.25-beta

**Comment by yandeu** [comment]
I don't know if it is related to v3.25-beta. Does it work well in v3.24?

**Comment by georgzoeller** [comment]
Yea, tested on 3.24 and it's fine. 3.25 has a bunch of batching changes that would sound like potential culprits

[image](https://user-images.githubusercontent.com/2640999/89072954-25309d00-d3ac-11ea-92e2-9fa8175f3fb7.png)

**Comment by yandeu** [comment]
I see. I suggest we wait for the next beta version or the stable 3.25 release. Maybe it will be fixed.

**Comment by georgzoeller** [comment]
In case it isn't, here's some more information

It only kicks in at certain angles - the text / icons render just find but when the camera has a certain perspective on the water, it looks like all game object textures get overwritten

**Comment by georgzoeller** [comment]
I think this is a broader issue - enable3d isn't entirely playing nice with phaser, even before 3.25.
it somehow interferes with rendering shape fills - I cannot do a graphics.fillStyle().fillEllipse() for example while I have enable3d loaded, it just renders the stroke of objects, but fill on any scene running on the same phaser instance will be blank.

**Comment by georgzoeller** [comment]
![image](https://user-images.githubusercontent.com/2640999/89128655-c6912d80-d529-11ea-9236-95357c5ab5d5.png)

**Comment by georgzoeller** [comment]
I've narrowed it down to this:
it's this.accessThirdDimension() that causes the corruption
as long as I have a blank Scene3D in the project and that scene calls 
this.accessThirdDimension() in it's create function, any graphics.fillX will not work anymore (no error)

Since phaser has a bunch of global state in graphics objects (setTexture being the best example), I assume something is getting corrupted there on a global level and it's happening in accessThirdDimension.

**Comment by yandeu** [comment]
Scene3D extends from Phaser.Scene version ~3.23.0.

Maybe this causes some issues? Can you downgrade to ~3.23.0 to test it?

**Comment by georgzoeller** [comment]
Just Tried 3.22 / 3.23 / 3.24 / 3.25b0 , all the same.

It looks like .accessThirdDimension() on a separate scene is wiping the fill. Interestingly, If I destroy and recreate the shapes after that call, their fill is rendered properly.

**Comment by yandeu** [comment]
Hi @georgzoeller 

I guess with the latest enable3d update, all these issues should be gone.

I have completely changed how 3d elements get implemented in a Phaser 3 game.

Check the [readme file](https://github.com/enable3d/enable3d#readme) to upgrade to v20.

**Comment by yandeu** [comment]
I close this issue since from version 20, enable3d does not mix the three.js and phaser.js WebGLRenderingContext anymore and therefore all these issues should be gone.
