### ISSUE TITLE
rigidbody error loading gltf model

### ISSUE THREAD

**Issue by bricknim** [enable3d/enable3d#39]
Hello, I am using phaser extension,

When I add mesh rigidbody with .gltf file rendered at blender, The rigidbody become weird.

~~~JavaScript
this.third.load.gltf('models/body.gltf').then( (gltf) => { this.third.scene.add(gltf.scene); this.third.physics.add.existing(gltf.scene, {shape:'mesh'}));
~~~

![image](https://user-images.githubusercontent.com/63555096/90526679-a610d680-e1ab-11ea-9a35-db88a5803e37.png)

**Comment by yandeu** [comment]
The rigidbody looks right to me. Looks more like a scaling issue. Do you scale the model somewhere in your code?

_Btw, for such a model, I would recommend to use a simple cylinder shape instead._

**Comment by bricknim** [comment]
I tried to work 
~~~ JavaScript
. . . . . . gltf.scene.body.scale.set(0.3, 0.3, 0.3)
~~~, 
but that's not working and I couldn't change any transform settings of rigidbody (like position, scale).

**Comment by yandeu** [comment]
Can you somehow send me your model?

**Comment by bricknim** [comment]
Yes, then Where can I send my model to you?

**Comment by yandeu** [comment]
https://wetransfer.com/upload

**Comment by bricknim** [comment]
Please write your email address

**Comment by yandeu** [comment]
You will find it here:
yandeu.github.io

**Comment by bricknim** [comment]
I did it, Please check your Email.

**Comment by yandeu** [comment]
I guess there is something wrong with the model. Also I guess it is better to add it as a binary .glb file. 
_I'm not a Blender pro at all._

Anyways, I highly recommend using a custom compound shape. It is much much faster.

```ts
this.third.load.gltf('/assets/body.gltf').then(gltf => {
  const child = gltf.scene.children[0]

  const body = new ExtendedObject3D()
  body.add(child)
  this.third.scene.add(body)

  const compound = [{ shape: 'cylinder', radiusTop: 3, height: 1.2, y: 1.6 }]
  this.third.physics.add.existing(body, { compound })
})
````
![localhost_8080_ (4)](https://user-images.githubusercontent.com/20306025/90759960-76fc8100-e2e1-11ea-80dd-f4ac906b3740.png)
