### ISSUE TITLE
No option to set WebGLRenderer params :(

### ISSUE THREAD

**Issue by psociety** [enable3d/enable3d#390]
If i want to set the `alpha` attribute there's no option for it:
https://github.com/enable3d/enable3d/blob/f42e645fc19e4c0d000bf8fd9f7c77cd420b4f94/packages/phaserExtension/src/third.ts#L54C73-L54C83

Forces me to manually hack the compiled file:
```js
config.renderer = new WebGLRenderer({ ...options, antialias: config.antialias || false, alpha: true });
```

And it has more options: https://threejs.org/docs/#api/en/renderers/WebGLRenderer

**Why would anyone want that?**
For billboard imposting for example.
Without alpha:
<img width="398" alt="image" src="https://github.com/enable3d/enable3d/assets/29523682/f2862ddd-d5b3-4886-a0ea-509d828d842c">

with alpha:
<img width="288" alt="image" src="https://github.com/enable3d/enable3d/assets/29523682/56e80b97-2608-4706-8061-80f5cf52e3bc">

**Comment by yandeu** [comment]
You can directly add your custom WebGLRenderer into `new Project()`.

Example:
```ts
PhysicsLoader('/lib', () => new Project({ scenes: [MainScene], renderer: new WebGLRenderer() }))
```
