### ISSUE TITLE
Unable to create railway wheel with Enable3d

### ISSUE THREAD

**Issue by Smithangshu** [enable3d/enable3d#42]
Hi,

I am trying to make wheel on track but its not working. Can you please check my following code on your end and provide me with a solution?

`

        var scene;
        var camera;
        var renderer;
        var clock;
        var cloud;
        var physics;
        const { AmmoPhysics, PhysicsLoader } = ENABLE3D
        function initScene() {
            scene = new THREE.Scene();
            clock = new THREE.Clock();
            var scene_width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
            var scene_height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
            camera = new THREE.PerspectiveCamera(50, scene_width / scene_height, 0.1, 30000);
            scene.add(new THREE.AmbientLight(0xffffff))
            camera.position.set(50, 10,0);
            renderer = new THREE.WebGLRenderer({ antialias: true });
            const DPR = window.devicePixelRatio
            renderer.setPixelRatio(Math.min(2, DPR))
            renderer.setSize(scene_width, scene_height);
            document.body.appendChild(renderer.domElement);
            control = new THREE.OrbitControls(camera, renderer.domElement);
            var clock = new THREE.Clock();
            function animate() {
                requestAnimationFrame(animate);
                control.update();
                if(physics)
                {
                    physics.update(clock.getDelta() * 1000)
                    physics.updateDebugger()
                }
                renderer.clear();
                renderer.render(scene, camera);
            }
            requestAnimationFrame(animate);
        }
        function initPhysics(){
            physics = new AmmoPhysics(scene,{ gravity: { x:0,y:-10,z:0 }, maxSubSteps: 1, fixedTimeStep: 1 / 60 });
            physics.debug.enable();
        }
        function addBox()
        {
            var geometry = new THREE.BoxGeometry(4,4,4);
            var material = new THREE.MeshStandardMaterial({ color:0xff0000 });
            var box = new THREE.Mesh(geometry, material);
            scene.add(box);
            box.position.y = 2;
        }
        function addPlane()
        {
            var geometry = new THREE.PlaneGeometry(100,100);
            var material = new THREE.MeshStandardMaterial({ color:0x00ff00 });
            var plane = new THREE.Mesh(geometry, material);
            scene.add(plane);
            plane.rotation.x=-Math.PI/2;
            physics.add.existing(plane,{ mass: 2000, collisionFlags:1 });
        }
        function addWheel(){
            var wheel = new THREE.Group();
            var leftwheelgeometry = new THREE.CylinderGeometry(4, 4, 2, 64);
            var leftwheelmaterial = new THREE.MeshStandardMaterial({ color:0x00ffff });
            var leftwheel = new THREE.Mesh(leftwheelgeometry, leftwheelmaterial);
            var leftwheelrimgeometry = new THREE.CylinderGeometry(5, 5, .3, 64);
            var leftwheelrimmaterial = new THREE.MeshStandardMaterial({ color:0x0ff0ff });
            var leftwheelrim = new THREE.Mesh(leftwheelrimgeometry, leftwheelrimmaterial);
            leftwheelrim.position.y=-9;
            wheel.add(leftwheelrim);
            leftwheel.position.y= 10;
            wheel.add(leftwheel);
            var rightwheelgeometry = new THREE.CylinderGeometry(4, 4, 2, 64);
            var rightwheelmaterial = new THREE.MeshStandardMaterial({ color:0x00ffff });
            var rightwheel = new THREE.Mesh(rightwheelgeometry, rightwheelmaterial);
            var rightwheelrimgeometry = new THREE.CylinderGeometry(5, 5, .3, 64);
            var rightwheelrimmaterial = new THREE.MeshStandardMaterial({ color:0x0ff0ff });
            var rightwheelrim = new THREE.Mesh(rightwheelrimgeometry, rightwheelrimmaterial);
            rightwheelrim.position.y=9;
            wheel.add(rightwheelrim);
            rightwheel.position.y= -10;
            wheel.add(rightwheel);
            var axelgeometry = new THREE.CylinderGeometry(1, 1, 20, 64);
            var axelmaterial = new THREE.MeshStandardMaterial({ color:0x0ff0ff });
            var axel = new THREE.Mesh(axelgeometry, axelmaterial);
            wheel.add(axel);
            wheel.rotation.x = Math.PI/2;
            wheel.position.y = 7;
            scene.add(wheel);
            const compound = [
                { shape: 'cylinder', radiusTop: 4, radiusBottom: 4, height:2, z: 0, y: 10, z:0 },
                { shape: 'cylinder', radiusTop: 4, radiusBottom: 4, height:2, z: 0, y: -10, z:0 },
                { shape: 'cylinder', radiusTop: 5, radiusBottom: 5, height:.3, z: 0, y: 9, z:0 },
                { shape: 'cylinder', radiusTop: 5, radiusBottom: 5, height:.3, z: 0, y: -9, z:0 },
                { shape: 'cylinder', radiusTop: 1, radiusBottom: 1, height:20, z: 0, y: 0, z:0 },
            ]
            physics.add.existing( wheel, { compound },{ mass: 2, collisionFlags:0 });
            wheel.body.setCcdMotionThreshold(1e-7)
            wheel.body.setCcdSweptSphereRadius(0.25)
        }
        function addTrack()
        {
            var lefttrackgeometry = new THREE.BoxGeometry(100,2,2);
            var lefttrackmaterial = new THREE.MeshStandardMaterial({ color:0x0000ff });
            var lefttrack = new THREE.Mesh(lefttrackgeometry, lefttrackmaterial);
            //scene.add(lefttrack);
            lefttrack.position.y = 1;
            lefttrack.position.z=-10.5;
            var righttrackgeometry = new THREE.BoxGeometry(100,2,2);
            var righttrackmaterial = new THREE.MeshStandardMaterial({ color:0x0000ff });
            var righttrack = new THREE.Mesh(righttrackgeometry, righttrackmaterial);
            //scene.add(righttrack);
            righttrack.position.y = 1;
            righttrack.position.z=10.5;
            var track = new THREE.Group();
            track.add(lefttrack);
            track.add(righttrack);
            scene.add(track);
            const compound = [
                { shape: 'box', width: 100, height: 2, depth:2, z: 0, y: 1, z:-10.5 },
                { shape: 'box', width: 100, height: 2, depth:2, z: 0, y: 1, z:10.5 }
            ]
            physics.add.existing(track,{ mass: 200, collisionFlags:1 });
            track.body.setCcdMotionThreshold(1e-7)
            track.body.setCcdSweptSphereRadius(0.25)
        }
        window.onresize = function () {
            var scene_width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
            var scene_height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
            camera.aspect = scene_width / scene_height;
            camera.updateProjectionMatrix();
            renderer.setSize(scene_width, scene_height);
            const DPR = window.devicePixelRatio
            renderer.setPixelRatio(Math.min(2, DPR))
        }
        PhysicsLoader('/js',()=>{
            initScene();
            initPhysics();
            addPlane();
            addWheel();
            addTrack();
        });`

**Comment by Smithangshu** [comment]
Please add reference of threejs v116, enable3d.ammoPhysics.0.19.1.min.js, and Threejs OrbitControl js then you can reproduce the unexpected and undesired issue I am facing.

**Comment by yandeu** [comment]
Before I test it, can you please describe the issue you're having?

**Comment by yandeu** [comment]
Is this still active?

**Comment by Smithangshu** [comment]
Yes I am sorry I could not reply you due to some health issue. I am trying to create a Enable3d Powered Railway Sim where railway wheel will roll on the track as same as it rolls in real life. But unfortunately I was not able to reproduce it with the above code. It seems wheels(cylinder) does not hit object(track). Please create a simple html page and put my code it will let you understand what I am trying to mean. And please let me know if my plan is possible with this library if yes, then how?

**Comment by yandeu** [comment]
I'm sorry to hear that. Hope you are doing better now!

Looks like the default Cylinder Physics Body is not so good.

I would either pre-build your Railway as a model or use CSG to merge your objects and add a convex mesh to it. There is a CSG module inside the enable3d framework.

_But there was a little bug in the CSG module I just fixed in https://github.com/enable3d/enable3d/commit/7566b200902665e6c68bf076e13f239a505e9148_

Here is the code of what you see in the screenshot below.

```ts
import { Project, Scene3D, PhysicsLoader, ExtendedObject3D, THREE } from 'enable3d'

class MainScene extends Scene3D {
  async create() {
    this.warpSpeed()
    this.camera.position.set(20, 20, 40)

    this.physics.debug?.enable()

    let group = []

    group.push(this.make.cylinder({ radiusSegments: 24, radiusTop: 4, radiusBottom: 4, height: 2, z: 0, y: 10 }))
    group.push(this.make.cylinder({ radiusSegments: 24, radiusTop: 4, radiusBottom: 4, height: 2, z: 0, y: -10 }))
    group.push(this.make.cylinder({ radiusSegments: 24, radiusTop: 5, radiusBottom: 5, height: 0.3, z: 0, y: 9 }))
    group.push(this.make.cylinder({ radiusSegments: 24, radiusTop: 5, radiusBottom: 5, height: 0.3, z: 0, y: -9 }))
    group.push(this.make.cylinder({ radiusSegments: 4, radiusTop: 1, radiusBottom: 1, height: 20, z: 0, y: 0 }))

    let wheel = group[0]
    for (let i = 1; i < group.length; i++) {
      wheel = this.csg.union(wheel, group[i]) as ExtendedObject3D
    }

    wheel.material = new THREE.MeshLambertMaterial({ color: 'green' })
    wheel.castShadow = wheel.receiveShadow = true
    wheel.rotateZ(Math.PI / 2)

    this.add.existing(wheel)
    this.physics.add.existing(wheel, { shape: 'convex', autoCenter: true })
  }
}

PhysicsLoader('/lib', () => new Project({ scenes: [MainScene] }))
```

![localhost_8080](https://user-images.githubusercontent.com/20306025/95918340-e8b9ee00-0dab-11eb-8274-42dae868a01e.png)

**Comment by yandeu** [comment]
I just made 2 examples. The second one seems to work better and faster.

- https://enable3d.io/examples/railway-with-csg.html
- https://enable3d.io/examples/railway-with-constraints.html

Hope it helps 😃

**Comment by Smithangshu** [comment]
Great I am going to check this out asap. And letting you know. I am a really great fan of this library and your skill. So I want bring this ever realistic Railway Sim with your Physics engine and your help. Thank you so so much 🙂

**Comment by Smithangshu** [comment]
Your examples are absolutely mind blowing. On the first one, wheel is jumping at some points but 2nd one is flawless. After seeing the second example I am now very confident that I can develop the realistic Railway Sim with Enable3d. Please keep this thread open so that I can ask you for further help regarding it without loosing the context and one more thing in this project I am going to promote your library in Railway Sim world. So that more and more people get to know about this powerful and efficient library.

**Comment by yandeu** [comment]
Thx :)

Btw. The physics engine uses the metric system. To achieve the best results, your objects should have a realistic size. So instead of a width of 20m, like in the example above, I recommend using 1.5m.

**Comment by Smithangshu** [comment]
One thing I am noticing is that if I would reduce all the parameters by 10 times like 20m has become 2m then the result I am getting is not same as 10 times larger. And if I use 10 times larger scale and trying to add bogie for wheels it some times throws out of memory error.

**Comment by Smithangshu** [comment]
I tried to follow your recommendation to use 1.5m instead of 20m, in order to do that I divided all the parameters by 0.075 but getting strange result. Following code I have used. Can you please tell me if I am doing any mistake or is this a bug in library if I use very small value?
```javascript
const { Project, Scene3D, PhysicsLoader, ExtendedObject3D, THREE } = ENABLE3D

      class MainScene extends Scene3D {
        isRolling = false
        wheel

        async create() {
          this.warpSpeed('-ground')
          this.camera.position.set(1.5, 1.5, 3)
          this.physics.debug?.enable()

          const distance = .75

          let railLeft = this.add.box({ depth: 80, width: 0.075, height:0.075 })
          railLeft.position.x -= distance
          this.physics.add.existing(railLeft, { collisionFlags: 1, mass: 0 })
          railLeft.body.setRestitution(1)

          let railRight = this.add.box({ depth: 80, width: 0.075, height:0.075 })
          railRight.position.x += distance
          this.physics.add.existing(railRight, { collisionFlags: 1, mass: 0 })
          railRight.body.setRestitution(1)

          const data = [
            { radiusSegments: 24, radiusTop: 0.3, radiusBottom: 0.3, height: 0.15, z: 0, x: -0.75 },
            { radiusSegments: 24, radiusTop: 0.4125, radiusBottom: 0.4125, height: 0.0225, z: 0, x: -0.675 },
            { radiusSegments: 4, radiusTop: 0.075, radiusBottom: 0.075, height: 1.35, z: 0, x: 0 },
            { radiusSegments: 24, radiusTop: 0.4125, radiusBottom: 0.4125, height: 0.0225, z: 0, x: 0.675 },
            { radiusSegments: 24, radiusTop: 0.3, radiusBottom: 0.3, height: 0.15, z: 0, x: 0.75 }
          ]

          this.bodies = data.map(d => {
            let cylinder = this.add.cylinder(d)
            cylinder.rotateZ(Math.PI / 2)
            cylinder.position.y += 0.375
            cylinder.position.z -= 1.5
            this.physics.add.existing(cylinder, { shape: 'convex', mass: 7.5 })
            return cylinder
          })

          for (let i = 0; i < this.bodies.length - 1; i++) {
            const constraint = this.physics.add.constraints.lock(this.bodies[i].body, this.bodies[i + 1].body)

            // [bug] it is not yet possible to choose to "disableCollisionsBetweenLinkedBodies",
            // so we remove the constraint add a new one.
            this.physics.physicsWorld.removeConstraint(constraint)
            this.physics.physicsWorld.addConstraint(constraint, true)
          }

          setTimeout(() => {
            this.isRolling = true
          }, 2000)
        }

        update() {
          // we apply the force the the middle part
          if (this.isRolling) this.bodies[2].body.setAngularVelocityX(0.15)
        }
      }
      PhysicsLoader('/lib', () => new Project({ scenes: [MainScene], antialias: true }))
```

**Comment by yandeu** [comment]
You're right. It does not look as smooth at that scale. 

I guess you can leave it to 20m then. Or try a single 3d model instead of a shape based on 5 constraint objects.

**Comment by Smithangshu** [comment]
But I need your suggestion regarding that, if import single 3d model(ex locomotive) then how can I separate 3 parts with physics, a) The Loco Body, b) Bogie, c) Wheel? And which constraints are best to use for connecting these three parts?

**Comment by yandeu** [comment]
I just want to let you know that I'm on it. I will make an example with a car using hinge constraints and a motor. 

Also I have fixed the issue with the cylinder shape. Was a simple bug.

Will release it soon.

**Comment by Smithangshu** [comment]
Ok thank you so so much. I will wait for the release.

**Comment by yandeu** [comment]
> Ok thank you so so much. I will wait for the release.

This fix is now available.
Here is the example: https://enable3d.io/examples/railway-with-compound-body.html
