### ISSUE TITLE
can I make multiplayer games with enable3djs?

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#44]
can I make multiplayer games with enable3djs?

I have tried to do the following example together with socket.io, but I don't know how to communicate when a user leaves, or when a user moves. "I really don't know if the little I've written is right."

So I wonder if anyone has been able to make any multitplayer games with enable3djs? If so, can you help me?

`    const { enable3d, Scene3D, Canvas, THREE } = ENABLE3D

    class MainScene extends Scene3D {
      constructor() {
        super({ key: 'MainScene' })
      }

      init() {
        this.requestThirdDimension()
      }

      create() {
        this.accessThirdDimension()
        this.third.warpSpeed()
        this.myio()
      }

      myio() {
        let socket = io();
        let groupPlayer = new THREE.Group()
        //this.otherPlayers = this.physics.add.group();
        socket.on('currentPlayers', (players) => {
          Object.keys(players).forEach((id) => {
            if (players[id].playerId === socket.id) {
              addOnePlayer(players[id])
            } else {
              addOtherPlayers(players[id])
            }
          });
        });

        socket.on('newPlayer', (playerInfo) => {
          addOtherPlayers(playerInfo);
        });

        socket.on('disconnect', (playerId) => {
          // i don't know how to do this step
        });

        const addOnePlayer = (playerInfo) => {
          console.log(playerInfo)
          let body
          let head
          if (playerInfo.team === 'blue') {
            body = this.third.add.box({ height: 0.8, y: 1, width: 0.4, depth: 0.4 }, { lambert: { color: 0x0000ff } })
            head = this.third.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0x0000ff } })
            //otherPlayer.setTint(0x0000ff);
          } else {
            body = this.third.add.box({ height: 0.8, y: 1, width: 0.4, depth: 0.4 }, { lambert: { color: 0xff0000 } })
            head = this.third.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0xff0000 } })
            //otherPlayer.setTint(0xff0000);
          }
          groupPlayer.add(body, head)
          groupPlayer.position.setX(3)
          this.third.add.existing(groupPlayer)
          this.third.physics.add.existing(groupPlayer)
        }

        const addOtherPlayers = (playerInfo) => {
          console.log(playerInfo)
          let group = new THREE.Group()
          let body
          let head
          if (playerInfo.team === 'blue') {
            body = this.third.add.box({ height: 0.8, y: 1, width: 0.4, depth: 0.4 }, { lambert: { color: 0x0000ff } })
            head = this.third.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0x0000ff } })
            //otherPlayer.setTint(0x0000ff);
          } else {
            body = this.third.add.box({ height: 0.8, y: 1, width: 0.4, depth: 0.4 }, { lambert: { color: 0xff0000 } })
            head = this.third.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0xff0000 } })
            //otherPlayer.setTint(0xff0000);
          }
          group.add(body, head)
          group.position.setX(3)
          this.third.add.existing(group)
          this.third.physics.add.existing(group)
        }
      }
    }

    const config = {
      type: Phaser.WEBGL,
      scale: {
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH,
        width: window.innerWidth * Math.max(1, window.devicePixelRatio / 2),
        height: window.innerHeight * Math.max(1, window.devicePixelRatio / 2)
      },
      scene: [MainScene],
      ...Canvas()
    }

    window.addEventListener('load', () => {
      enable3d(() => new Phaser.Game(config)).withPhysics('/lib')
    })`

**Comment by HadrienRivere** [comment]
Well I have solved it.
video: https://www.youtube.com/watch?v=wF_fLJG4R1o&t=2s
Source: https://github.com/HadrienRivere/enable3d-socketio

Although I have encountered some errors when I try to add some glb asset to the scene.

Description:

When I add some glb element and add physics to it like this:

`    const map = async () => {
      const object = await this.third.load.gltf('/assets/glb/mapOne.glb')
      this.scene = object.scenes[0]
      const map = new ExtendedObject3D()
      map.name = 'scene'
      map.add(scene)
      this.third.add.existing(this.scene)
      map.traverse(e => {
        if (e.isMesh) {
          e.castShadow = e.receiveShadow = false
          e.material.metalness = 0
          e.material.roughness = 1
          if (e.name) {
            this.third.physics.add.existing(e, {
              shape: 'concave',
              mass: 0,
              collisionFlags: 1,
              autoCenter: false,
            })
          }
        }
      })
    }`

player two takes the position {x: 0, y: 0, z: 0} and ignores what the socket sends.

playerTwo:

`    const playerTwo = (playerInfo) => {
      this.playertwo = new THREE.Group()
      this.playertwo.name = playerInfo.playerId
      this.playertwo.uuid = playerInfo.playerId
      this.playertwo.position.set(playerInfo.x, playerInfo.y, playerInfo.z)
      const body = this.add.box({ height: 0.8, y: 1, width: 0.4, depth: 0.4 }, { lambert: { color: 0xFF3333 } })
      const head = this.add.sphere({ radius: 0.25, y: 1.7, z: 0.05 }, { lambert: { color: 0xFF3333 } })
      this.playertwo.add(body, head)
      this.add.existing(this.playertwo)
      playersObject.push(this.playertwo)
    }
`

Socket:

`
    this.socket.on('playerMoved', function (playerInfo) {
      playersObject.forEach(p => {
        if (playerInfo.playerId === p.uuid) {
          p.position.x = playerInfo.x
          p.position.y = playerInfo.y
          p.position.z = playerInfo.z
          p.rotation.x = playerInfo.r.x
          p.rotation.y = playerInfo.r.y
          p.rotation.z = playerInfo.r.z
        }
      })
    });`

Video : 
https://www.youtube.com/watch?v=A5TFyO9qZy8

So I don't know why glb elements damage the player's position.

**Comment by yandeu** [comment]
Making a multiplayer game with enable3d is easy. In most cases you want to calculate the entire physics on the server and just update positions and rotations on the client.

If I find time today or tomorrow, I will develop a simple multiplayer game example.

**Comment by HadrienRivere** [comment]
> Making a multiplayer game with enable3d is easy. In most cases you want to calculate the entire physics on the server and just update positions and rotations on the client.
> 
> If I find time today or tomorrow, I will develop a simple multiplayer game example.

That's right, I already did it with socket io.
 link: https://github.com/HadrienRivere/enable3d-socketio

I just don't know why when adding a glb object with physics, the position of player 2 remains at {x: 0, y: 0, z: 0}, that is, it does not respond to the information sent by the socket.

**Comment by yandeu** [comment]
I'm happy to help fixing it. But it looks like you are calculating the physics on the client. Sure you want this?

Also your repo does not contain a `package.json` file. Can you add it please?

**Comment by HadrienRivere** [comment]
> I'm happy to help fixing it. But it looks like you are calculating the physics on the client. Sure you want this?

:O  is that possible to calculate from the server?

> Also your repo does not contain a `package.json` file. Can you add it please?

 Done I've uploaded the file.

**Comment by HadrienRivere** [comment]
@yandeu You can close this I have already solved it.
