### ISSUE TITLE
ReferenceError: Ammo is not defined

### ISSUE THREAD

**Issue by kyoa** [enable3d/enable3d#45]
env: ThreeJS with Vue2 in JavaScript,
I installed "@enable3d/ammo-physics": "^0.19.1", but when I initialize AmmoPhyisics as the example shows, it gave me this error.
My code of this initialization:

`    this.$nextTick(() => {
      init3D(this.htmlContext)
    })`

`export function init3D(htmlContext) {
    hc = htmlContext
    initRenderer()
    initScene()
    initCamera()
    initPhysics()
    animate()
}`

`function initPhysics() {
    const physics = new AmmoPhysics(c.scene, {usePhysics: false, useGravity: false})
    physics.debug.enable()
    c.physics = physics
}`

**Comment by yandeu** [comment]
Have you used the PhysicsLoader to load all ammo files?

---

Please take a look at [this example](https://enable3d.io/examples/native-three-with-physics.html).

Before starting the `MainScene()`, the `PhysicsLoader` loads **ammo.js**, **ammo.wasm.js** and **ammo.wasm.wasm** from the `/lib` directory.

**Comment by kyoa** [comment]
> Have you used the PhysicsLoader to load all ammo files?
> 
> Please take a look at [this example](https://enable3d.io/examples/native-three-with-physics.html).
> 
> Before starting the `MainScene()`, the `PhysicsLoader` loads **ammo.js**, **ammo.wasm.js** and **ammo.wasm.wasm** from the `/lib` directory.

Thx, but I'm a little noob at js,might need more help about this

    `PhysicsLoader('@enable3d/ammo-physics/ammo/', initAfterAmmoLoaded)`
the '/lib' path is not working,so I tried above path to load it, but still get the same error as '/lib' path:
`Uncaught SyntaxError: Unexpected token '<'`
`Uncaught ReferenceError: Ammo is not defined
    at eval (webpack-internal:///./node_modules/@enable3d/common/dist/physicsLoader.js:11)
    at eval (webpack-internal:///./node_modules/@enable3d/common/dist/wasmLoader.js:30)
    at HTMLScriptElement.tag.onload (webpack-internal:///./node_modules/@enable3d/common/dist/wasmLoader.js:18)`

**Comment by yandeu** [comment]
@kyoa Did you make it work?

**Comment by kyoa** [comment]
I simply put them into 'static' folder, loaded, but I get another error :
`three.module.js?5a89:19193 Uncaught TypeError: material.customProgramCacheKey is not a function
    at Object.getParameters (three.module.js?5a89:19193)
    at initMaterial (three.module.js?5a89:25864)
    at setProgram (three.module.js?5a89:26032)
    at WebGLRenderer.renderBufferDirect (three.module.js?5a89:25291)
    at renderObject (three.module.js?5a89:25844)
    at renderObjects (three.module.js?5a89:25816)
    at WebGLRenderer.render (three.module.js?5a89:25616)
    at render (Viewport3D.js?92b9:222)
    at animate (Viewport3D.js?92b9:209)`
But this seems like a custom shader conflicts?

**Comment by yandeu** [comment]
Yes, this does not look like a physics problem.

**Comment by HexaField** [comment]
> @yandeu I simply put them into 'static' folder, loaded, but I get another error constantly :
> `three.module.js?5a89:19193 Uncaught TypeError: material.customProgramCacheKey is not a function at Object.getParameters (three.module.js?5a89:19193) at initMaterial (three.module.js?5a89:25864) at setProgram (three.module.js?5a89:26032) at WebGLRenderer.renderBufferDirect (three.module.js?5a89:25291) at renderObject (three.module.js?5a89:25844) at renderObjects (three.module.js?5a89:25816) at WebGLRenderer.render (three.module.js?5a89:25616) at render (Viewport3D.js?92b9:222) at animate (Viewport3D.js?92b9:209)`
> But this seems like a custom shader conflicts with the ammo?

This specific error I have come across, you're using threejs@0.120 with enable3d, which uses threejs@0.117

You just need to install the older version of threejs to solve the issue.

**Comment by yandeu** [comment]
Thanks @HexaField!

---

As soon as I get home next week I will update enable3d to the latest three.js version. I will also take a look at the PR's.

**Comment by kyoa** [comment]
> > @yandeu I simply put them into 'static' folder, loaded, but I get another error constantly :
> > `three.module.js?5a89:19193 Uncaught TypeError: material.customProgramCacheKey is not a function at Object.getParameters (three.module.js?5a89:19193) at initMaterial (three.module.js?5a89:25864) at setProgram (three.module.js?5a89:26032) at WebGLRenderer.renderBufferDirect (three.module.js?5a89:25291) at renderObject (three.module.js?5a89:25844) at renderObjects (three.module.js?5a89:25816) at WebGLRenderer.render (three.module.js?5a89:25616) at render (Viewport3D.js?92b9:222) at animate (Viewport3D.js?92b9:209)`
> > But this seems like a custom shader conflicts with the ammo?
> 
> This specific error I have come across, you're using threejs@0.120 with enable3d, which uses threejs@0.117
> 
> You just need to install the older version of threejs to solve the issue.

Thx, that works .
But I keep getting this warning:
`three.module.js?5a89:21966 THREE.WebGLRenderer: Texture is not power of two. Texture.wrapS and Texture.wrapT should be set to THREE.ClampToEdgeWrapping.`
This makes the frames dropped a lot, which is quite annoying.
I think I should simply use the physics inside three for now.
THX for the help anyway

**Comment by kyoa** [comment]
> Thanks @HexaField!
> 
> As soon as I get home next week I will update enable3d to the latest three.js version. I will also take a look at the PR's.

Can't wait

**Comment by kyoa** [comment]
I still get this warning after switching back to three@0.120.1,
have to manually resize all maps to power of 2, finally get rid of it.
Then I switched to three@0.117.0, the physics works perfect!
I still don't know why this warning never showed before, quite curious.
@HexaField @yandeu 
THX, man ,really appreciate it.

**Comment by yandeu** [comment]
Enable3d version 0.20.0 is now available! It uses Three.js r121.
