### ISSUE TITLE
Fog doesn't work

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#46]
Hello,

im using enable3d as phaser extension

Some parts of Three.JS elements doesn't not work. 
im trying to add a simple fog into scene, and nothing happened.
"this" in bellow context means scene:

        this.fog = new THREE.Fog( 0x6B4D3F, 5, 30 );
        this.fog2 = new THREE.FogExp2( 0xefd1b5, 0.0025 );`

**Comment by yandeu** [comment]
I tried it in the [medieval example](https://enable3d.io/examples/medieval-fantasy-book.html) and it worked fine.

```js
this.third.scene.fog = new THREE.Fog(0x5e91cd, 5, 30)
this.third.scene.fog = new THREE.FogExp2(0x5e91cd, 0.05)
```

**Comment by Trusiak** [comment]
okay, i forgot add "third".
