### ISSUE TITLE
Physics mesh not transformed to body when loading from GLTF

### ISSUE THREAD

**Issue by tawjaw** [enable3d/enable3d#48]
Hello, 

I am loading a model using GLTFLoader

```

loader.load( 'assets/ArduinoUno.glb', function ( gltf ) {
  console.log(gltf);
  const mesh = gltf.scene;
  mesh.position.set(0,100,0);
  scene.add( mesh);
  
  //@ts-ignore
  physics.add.existing(mesh, {shape: 'concaveMesh'});

}, undefined, function ( error ) {

  console.error( error );

} );

```

the result is 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/10591561/96907660-8460f380-1469-11eb-9b51-50c6f077fb6c.png">

How can I centre the mesh with the body? 

Thanks.

**Comment by yandeu** [comment]
I think it is a similar issue like https://github.com/enable3d/enable3d/issues/47.

Did you make the model using Blender? Could it be that you have set a rotation on the scene and not the mesh itselfe? _I'm not a Blender expert_.

Do you find the strange 90deg rotation if you log `console.log(gltf.scene.children[0])`?

Can you send me the model?

**Comment by tawjaw** [comment]
@yandeu Thank you!

I reset the rotation on the object and the mesh so they sync now.

```
  gltf.scene.children[0].rotation.set(0,0,0);
  gltf.scene.children[0].children[0].rotation.set(0,0,0);
```

If I may ask for advice. How would you suggest adding wheels to a 3d concave object like this? my goal is to rotate the wheels and have the vehicle moving.

**Comment by HadrienRivere** [comment]
> @yandeu Thank you!
> 
> I reset the rotation on the object and the mesh so they sync now.
> 
> ```
>   gltf.scene.children[0].rotation.set(0,0,0);
>   gltf.scene.children[0].children[0].rotation.set(0,0,0);
> ```
> 
> If I may ask for advice. How would you suggest adding wheels to a 3d concave object like this? my goal is to rotate the wheels and have the vehicle moving.

try https://enable3d.io/examples/railway-with-csg.html

**Comment by yandeu** [comment]
I was working on a car example last week, but I got sick. I will post it here once finished.

**Comment by tawjaw** [comment]
@yandeu that would be great!
hope you feel better soon. 

My goal is to build a 2 wheel drive mobile robot. Which includes two wheels with motors and one caster wheel. Any suggestions on what kind of constraints I should be using?

**Comment by tawjaw** [comment]
> @yandeu that would be great!
> hope you feel better soon.
> 
> My goal is to build a 2 wheel drive mobile robot. Which includes two wheels with motors and one caster wheel. Any suggestions on what kind of constraints I should be using?

Hinge constraint with angular motor enabled works. [example](https://github.com/enable3d/enable3d/issues/49#issuecomment-716247029)
