### ISSUE TITLE
How to apply torque to cylinder? 

### ISSUE THREAD

**Issue by tawjaw** [enable3d/enable3d#49]
Hello, 
For some reason I am not able to apply torque to a cylinder. 

My goal is to rotate the cylinder. 

```
  physics.add.ground({ width: 200, height: 200 })

  const tire = new THREE.Mesh(new THREE.CylinderGeometry(), new THREE.MeshLambertMaterial({color: "#1a1a1a"}));
  tire.rotation.set(Math.PI/2, 0, 0);
  tire.position.set(0,3,0);
  scene.add(tire);
  physics.add.existing(tire, {shape:'concaveMesh', mass:10, collisionFlags:0});
```

I can apply force to it and it moves. And I can set the angular velocity and it rotates. But I am not able to apply torque. 
When I do, nothing happens.

**Comment by tawjaw** [comment]
It has to do with the concave shape. Without it, the torque is applied. But how to apply Torque with concave shapes?

Thanks.

**Comment by yandeu** [comment]
ConcaveMesh uses a btBvhTriangleMeshShape which does not rotate. Why don't you just use the default cylinder shape?

`physics.add.existing(tire, { mass: 10 })`

**Comment by tawjaw** [comment]
Thanks @yandeu. I did that after realizing concave was the problem. 

However, the cylinder was just a test I was doing. I am loading a 3d object (a wheel). Probably I can just create a default cylinder shape for it and map it to the object. 

Is there any example that uses hinge constraint as a motor?
A box and cylinder (wheel) with hinge constraint and use the motor to rotate the wheel.

**Comment by tawjaw** [comment]
never mind, 
Here's an example using Hinge constraint as a motor. It is based on the types of constraints example 

```
const hingeMotor = x => {
  //@ts-ignore
  let box1 = physics.add.box({ depth: 0.25, y: 2, x: x, mass: 0}, { custom: mat1 })
    //@ts-ignore
  let box2 = physics.add.box({ depth: 0.25, y: 2, x: x + 1.25 }, { custom: mat2 })

  const constraint = physics.add.constraints.hinge(box1.body, box2.body, {
    pivotA: { x: -0.65 },
    pivotB: { x: 0.65 },
    axisA: { x: 1 },
    axisB: { x: 1 }
  })

  physics.physicsWorld.removeConstraint(constraint);
  physics.physicsWorld.addConstraint(constraint, true);
  constraint.enableMotor(false);
  constraint.enableAngularMotor(true, 10,1);

  console.log(box1,box2, constraint);
}

```

As far as I can tell, to change the target speed we should call 
```
  constraint.enableAngularMotor(true, 10,1);
```
every time and changing the target speed.

**Comment by yandeu** [comment]
I just made an example of a car with constraints: https://enable3d.io/examples/car-using-physics-constraints.html
There will also soon be an example with the Raycast Vehicle class: https://enable3d.io/examples/raycast-vehicle.html
