### ISSUE TITLE
Proper way to move skeleton 

### ISSUE THREAD

**Issue by fhguarni** [enable3d/enable3d#50]
Hello, 

First I want to say THANK YOU for your amazing job!

I successfully loaded an avatar in gltf.  I added physics with shape concaveMesh, which was the best.  It is a little heavy, but I tested other shapes without success.  The avatar is attracted by gravity as expected.  The problem that I am facing now is that I want to rotate the legs of the avatar (which I can do it without problems) but physics don't act on him.  I can see physics shape is not updated to the new rotation of the bones.  I do it by becoming the avatar to a kinematic object, followed by rotating the bones, and then becoming back the avatar to dynamic.  If I rotate both legs at front, I hope that avatar falls to the floor over his buttocks, but the avatar keeps floating after I do that.  Which is the correct way to do it?

Thank you :)

**Comment by HadrienRivere** [comment]
> Hola,
> 
> Primero quiero decir GRACIAS por su increíble trabajo.
> 
> Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo?
> 
> Gracias :)

Can you show your code? by the way have you tried to guide yourself by this example?
https://enable3d.io/examples/enemy-patrols-on-platform.html

**Comment by fhguarni** [comment]
> > Hola,
> > Primero quiero decir GRACIAS por su increíble trabajo.
> > Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo?
> > Gracias :)
> 
> Can you show your code? by the way have you tried to guide yourself by this example?
> https://enable3d.io/examples/enemy-patrols-on-platform.html

Sure.  Here it is:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, avatar-scalable=no, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Native three.js with Physics</title>
    
    <script src="js/jquery.min.js"></script>
    <script src="lib/three.min.js"></script>
    <script src="js/loaders/GLTFLoader.js"></script>
    <script src="lib/enable3d.ammoPhysics.0.19.1.min.js"></script>
    <script src="js/controls/OrbitControls.js"></script>
    
  </head>

  <body>
    <div id="info-text">Using enable3d as Physics Plugin for three.js</div>
    <script>
    
        const { AmmoPhysics, PhysicsLoader } = ENABLE3D;
      
        class World
        {
            constructor ()
            {
                // scene
                this.scene = new THREE.Scene()
                this.scene.background = new THREE.Color(0xf0f0f0)

                // camera
                const camera = new THREE.PerspectiveCamera(50, window.innerWidth / window.innerHeight, 0.1, 1000)
                camera.position.set(10, 10, 20)

                // renderer
                //const renderer = new THREE.WebGLRenderer()
                let renderer = new THREE.WebGLRenderer({
                        antialias: true, 
                        alpha: true,
                        logarithmicDepthBuffer: true
                });
                
                renderer.gammaOutput = true;
                renderer.gammaFactor = 2.2;
                
                renderer.setSize(window.innerWidth, window.innerHeight)
                document.body.appendChild(renderer.domElement)

                // dpr
                const DPR = window.devicePixelRatio
                renderer.setPixelRatio(Math.min(2, DPR))

                // orbit controls
                const controls = new THREE.OrbitControls(camera, renderer.domElement)

                // light
                this.scene.add(new THREE.HemisphereLight(0xffffbb, 0x080820, 1))
                this.scene.add(new THREE.AmbientLight(0x666666))
                const light = new THREE.DirectionalLight(0xdfebff, 1)
                light.position.set(50, 200, 100)
                light.position.multiplyScalar(1.3)
                
                // physics
                const physics = new AmmoPhysics(this.scene)
                physics.debug.enable(true)
                
                // extract the object factory from physics
                // the factory will make/add object without physics
                const { factory } = physics

                // blue box
                physics.add.box({ x: 0.05, y: 10 }, { lambert: { color: 0x2194ce } })

                // static ground
                physics.add.ground({ width: 20, height: 20 })

                // add a normal sphere using the object factory
                // (NOTE: This will be factory.add.sphere() in the future)
                // first parameter is the config for the geometry
                // second parameter is for the material
                // you could also add a custom material like so { custom: new THREE.MeshLambertMaterial({ color: 0x00ff00 }) }
                let greenSphere = factory.addSphere({ y: 2, z: 5 }, { lambert: { color: 0x00ff00 } })
                // once the object is created, you can add physics to it
                physics.add.existing(greenSphere)

                // green sphere
                const geometry = new THREE.BoxBufferGeometry()
                const material = new THREE.MeshLambertMaterial({ color: 0x00ff00 })
                const cube = new THREE.Mesh(geometry, material)
                cube.position.set(0, 5, 0)
                this.scene.add(cube)
                physics.add.existing(cube)
                cube.body.setCollisionFlags(2) // make it kinematic
                
                const loader = new THREE.GLTFLoader();
                let avatar;

                /* Expert avatar */
                loader.load('models/male-black-global-Y_axis.glb', loadAvatar.bind(this), null, (e) => console.error(e));
                
                function loadAvatar(object)
                {
                    avatar = object.scene.children[0];
        
                    var mavatar = null
                    
                    avatar.traverse( function ( child ) {
                        if ( child instanceof THREE.Mesh ) {
                            child.material.alphaTest = 0.1;
                            
                            if (mavatar === null) {
                                mavatar = child;
                            }
                        }
                        
                    });
                    
                    if (mavatar !== null) {
                        avatar['skeleton'] = mavatar.skeleton;
                    }
                    
                    avatar.scale.set( 1, 1, 1 );
                    avatar.position.set(-5, 10, 0);
                    
                    this.scene.add(avatar);
                    
                    physics.add.existing( avatar, {shape:'concaveMesh'} );
                };
                
                setTimeout (rotateAvatarLegs, 5000);
                
                function rotateAvatarLegs ()
                {
                    let leftThigh = avatar.skeleton.bones[1];
                    let rightThigh = avatar.skeleton.bones[5];
                    
                    // Set avatar to be kinematic
                    avatar.body.setCollisionFlags(2);
                    console.log("avatar kinematic");
                    
                    leftThigh.rotateX (Math.PI/2);
                    rightThigh.rotateX (Math.PI/2);
                    
                    avatar.body.needUpdate = true;
                
                    // this will run only on the next update if body.needUpdate = true
                    avatar.body.once.update(() => {
                        // set avatar back to dynamic
                        avatar.body.setCollisionFlags(0);
                        console.log("avatar dynamic");
                    });
                }

                // clock
                const clock = new THREE.Clock()

                // loop
                const animate = () => {
                  cube.rotation.x += 0.01
                  cube.rotation.y += 0.01
                  cube.body.needUpdate = true // this is how you update kinematic bodies*/

                  physics.update(clock.getDelta() * 1000)
                  physics.updateDebugger()
                  renderer.render(this.scene, camera)

                  requestAnimationFrame(animate)
                }
                requestAnimationFrame(animate)
            }
        }
        
        PhysicsLoader('/lib', () => new World('#visualizer'));
        
        
        //gym = new World();
      
      
        /*const MainScene = () => {
            // scene
            const scene = new THREE.Scene()
            scene.background = new THREE.Color(0xf0f0f0)

            // camera
            const camera = new THREE.PerspectiveCamera(50, window.innerWidth / window.innerHeight, 0.1, 1000)
            camera.position.set(10, 10, 20)

            // renderer
            //const renderer = new THREE.WebGLRenderer()
            let renderer = new THREE.WebGLRenderer({
                    antialias: true, 
                    alpha: true,
                    logarithmicDepthBuffer: true
            });
            
            renderer.gammaOutput = true;
            renderer.gammaFactor = 2.2;
            
            renderer.setSize(window.innerWidth, window.innerHeight)
            document.body.appendChild(renderer.domElement)

            // dpr
            const DPR = window.devicePixelRatio
            renderer.setPixelRatio(Math.min(2, DPR))

            // orbit controls
            const controls = new THREE.OrbitControls(camera, renderer.domElement)

            // light
            scene.add(new THREE.HemisphereLight(0xffffbb, 0x080820, 1))
            scene.add(new THREE.AmbientLight(0x666666))
            const light = new THREE.DirectionalLight(0xdfebff, 1)
            light.position.set(50, 200, 100)
            light.position.multiplyScalar(1.3)

            // physics
            const physics = new AmmoPhysics(scene)
            physics.debug.enable(true)

            // extract the object factory from physics
            // the factory will make/add object without physics
            const { factory } = physics

            // blue box
            physics.add.box({ x: 0.05, y: 10 }, { lambert: { color: 0x2194ce } })

            // static ground
            physics.add.ground({ width: 20, height: 20 })

            // add a normal sphere using the object factory
            // (NOTE: This will be factory.add.sphere() in the future)
            // first parameter is the config for the geometry
            // second parameter is for the material
            // you could also add a custom material like so { custom: new THREE.MeshLambertMaterial({ color: 0x00ff00 }) }
            let greenSphere = factory.addSphere({ y: 2, z: 5 }, { lambert: { color: 0x00ff00 } })
            // once the object is created, you can add physics to it
            physics.add.existing(greenSphere)

            // green sphere
            const geometry = new THREE.BoxBufferGeometry()
            const material = new THREE.MeshLambertMaterial({ color: 0x00ff00 })
            const cube = new THREE.Mesh(geometry, material)
            cube.position.set(0, 5, 0)
            scene.add(cube)
            physics.add.existing(cube)
            cube.body.setCollisionFlags(2) // make it kinematic

            // merge children to compound shape
            const exclamationMark = () => {
              const material = new THREE.MeshLambertMaterial({ color: 0xffff00 })

              const sphere = new THREE.Mesh(new THREE.SphereBufferGeometry(0.25), material)
              sphere.position.set(0, -0.8, 0)

              const cube = new THREE.Mesh(new THREE.BoxBufferGeometry(0.4, 0.8, 0.4), material)
              cube.position.set(5, 2, 5)

              cube.add(sphere)
              scene.add(cube)

              cube.position.set(5, 5, 5)
              cube.rotation.set(0, 0.4, 0.2)

              physics.add.existing(cube)
            }
            exclamationMark()

            // clock
            const clock = new THREE.Clock()

            // loop
            const animate = () => {
              cube.rotation.x += 0.01
              cube.rotation.y += 0.01
              cube.body.needUpdate = true // this is how you update kinematic bodies

              physics.update(clock.getDelta() * 1000)
              physics.updateDebugger()
              renderer.render(scene, camera)

              requestAnimationFrame(animate)
            }
            requestAnimationFrame(animate)
        }
        PhysicsLoader('/lib', () => MainScene())*/
    </script>
  </body>
</html>

![Avatar-physics](https://user-images.githubusercontent.com/73455346/97243994-3a01bd00-1843-11eb-899e-ebd7324b0b9a.PNG)

**Comment by fhguarni** [comment]
> 
> 
> > Hola,
> > Primero quiero decir GRACIAS por su increíble trabajo.
> > Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo?
> > Gracias :)
> 
> Can you show your code? by the way have you tried to guide yourself by this example?
> https://enable3d.io/examples/enemy-patrols-on-platform.html

In regard to the example, it is a walking animation and it rotates the whole avatar (robot).  In my case I want to move any part of the body by moving the skeleton in it and physics do its job with the new pose.  Is that possible? Any ideas how can I achieve this? I am not expert on this, so probably I am asking too much...

Thanks 👍

**Comment by HadrienRivere** [comment]
> > > Hola, 
> > > Primero quiero decir GRACIAS por su increíble trabajo.
> > > Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo? 
> > > Gracias :)
> > 
> > 
> > ¿Puedes mostrar tu código? por cierto, ¿ha intentado guiarse por este ejemplo? 
> > https://enable3d.io/examples/enemy-patrols-on-platform.html
> 
> En cuanto al ejemplo, es una animación andante y rota todo el avatar (robot). En mi caso, quiero mover cualquier parte del cuerpo moviendo el esqueleto en él y la física hace su trabajo con la nueva pose. ¿Es eso posible? ¿Alguna idea de cómo puedo lograr esto? No soy un experto en esto, por lo que probablemente esté pidiendo demasiado ...
> 
> Gracias 👍

Hello unfortunately I have not been able to find the solution to this problem. I think it seems that right now it is not possible for the Physics  to move as it moves or an arm or foot of the glb object. From what I see the Physics type "concaveMesh" takes the form of the first animation. so I guess if you add different kinds of animations in glb format. I could achieve what you're looking for.

**Comment by fhguarni** [comment]
> 
> 
> > > > Hola,
> > > > Primero quiero decir GRACIAS por su increíble trabajo.
> > > > Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo?
> > > > Gracias :)
> > > 
> > > 
> > > ¿Puedes mostrar tu código? por cierto, ¿ha intentado guiarse por este ejemplo?
> > > https://enable3d.io/examples/enemy-patrols-on-platform.html
> > 
> > 
> > En cuanto al ejemplo, es una animación andante y rota todo el avatar (robot). En mi caso, quiero mover cualquier parte del cuerpo moviendo el esqueleto en él y la física hace su trabajo con la nueva pose. ¿Es eso posible? ¿Alguna idea de cómo puedo lograr esto? No soy un experto en esto, por lo que probablemente esté pidiendo demasiado ...
> > Gracias 👍
> 
> Hello unfortunately I have not been able to find the solution to this problem. I think it seems that right now it is not possible for the Physics to move as it moves or an arm or foot of the glb object. From what I see the Physics type "concaveMesh" takes the form of the first animation. so I guess if you add different kinds of animations in glb format. I could achieve what you're looking for.

Oh, I see.  I understand.

Thank you so much :)

**Comment by HadrienRivere** [comment]
> > > > > Hola,
> > > > > Primero quiero decir GRACIAS por su increíble trabajo.
> > > > > Cargué con éxito un avatar en gltf. Agregué física con forma cóncavaMesh, que fue la mejor. Es un poco pesado, pero probé otras formas sin éxito. El avatar es atraído por la gravedad como se esperaba. El problema al que me estoy enfrentando ahora es que quiero rotar las piernas del avatar (que puedo hacerlo sin problemas) pero la física no actúa sobre él. Puedo ver que la forma física no se actualiza a la nueva rotación de los huesos. Lo hago después convirtiéndome en avatar en un objeto cinemático, seguido de la rotación de los huesos y luego volviendo el avatar a la dinámica. Si giro ambas piernas al frente, espero que el avatar caiga al suelo sobre sus nalgas, pero el avatar sigue flotando después de que hago eso. ¿Cuál es la forma correcta de hacerlo?
> > > > > Gracias :)
> > > > 
> > > > 
> > > > ¿Puedes mostrar tu código? por cierto, ¿ha intentado guiarse por este ejemplo?
> > > > https://enable3d.io/examples/enemy-patrols-on-platform.html
> > > 
> > > 
> > > En cuanto al ejemplo, es una animación andante y rota todo el avatar (robot). En mi caso, quiero mover cualquier parte del cuerpo moviendo el esqueleto en él y la física hace su trabajo con la nueva pose. ¿Es eso posible? ¿Alguna idea de cómo puedo lograr esto? No soy un experto en esto, por lo que probablemente esté pidiendo demasiado ...
> > > Gracias 👍
> > 
> > 
> > Hello unfortunately I have not been able to find the solution to this problem. I think it seems that right now it is not possible for the Physics to move as it moves or an arm or foot of the glb object. From what I see the Physics type "concaveMesh" takes the form of the first animation. so I guess if you add different kinds of animations in glb format. I could achieve what you're looking for.
> 
> Oh, I see. I understand.
> 
> Thank you so much :)

Don't despair, maybe @yandeu can help.

**Comment by yandeu** [comment]
- It is not possible to modify a Rigid Body after it has been created.
- You can't rotate a concaveMesh.

Are you making a game? Or a sort of simulation?
 For a game I suggest you use a `capsule` shape:

```ts
// try something similar to this
this.physics.add.existing(avatar, { shape: 'capsule', radius: 0.2, height: 0.8, offset: { y: -0.5 } })
avatar.body.setAngularFactor(0, 1, 0)
```

**Comment by fhguarni** [comment]
> 
> 
>     * It is not possible to modify a Rigid Body after it has been created.
> 
>     * You can't rotate a concaveMesh.
> 
> 
> Are you making a game? Or a sort of simulation?
> For a game I suggest you use a `capsule` shape:
> 
> ```ts
> // try something similar to this
> this.physics.add.existing(avatar, { shape: 'capsule', radius: 0.2, height: 0.8, offset: { y: -0.5 } })
> avatar.body.setAngularFactor(0, 1, 0)
> ```

Thank you yandeu for your answer.  It is a kind of simulation with mems sensors.  Unfortunately, when I use a capsule shape, the avatar behaves similarly to a box shape.  None of the work in this case as I expected.

Thank you again 👍

**Comment by yandeu** [comment]
Hi @fhguarni and @HadrienRivere,

Check out the example below. I'm sure you find it interesting :)
https://enable3d.io/examples/fbx-loader-and-animations-hitbox.html
