### ISSUE TITLE
Working with compound bodies

### ISSUE THREAD

**Issue by tawjaw** [enable3d/enable3d#51]
Hello, 

I am having troubles working with THREE.Group and compound bodies. 

Not sure if it's a bug. 

```
  const robotBody = new THREE.Group();

  // I add multiple THREE mesh to robotBody

  const compound = [
        { shape: 'box', y:-0.0155, height:0.03, width:0.9, depth:1.5 },
       { shape: 'box',y:-0.2155, height:0.03, width:0.45, depth:1.5 },
        { shape: 'cylinder',radiusTop:0.025, height:0.2, radiusBottom: 0.025, radiusSegments: 7},
      ]

  //@ts-ignore
  physics.add.existing(robotBody, {compound:compound,collisionFlags:2, mass:1});
      
```
1. How can I set the collision flag of the body? and mass? nothing is changing. even when I set the mass to 0.

2. I need to "teleport" the body.
with normal shape I set the collision flag to 2, change the position, then call update once. Like the example.
But I am not able to change the collision flag. 

So I tried removing the full body and then adding it. 
```
        //@ts-ignore
        physics.destroy(robotBody.body);
```
This does not work.

**Comment by yandeu** [comment]
You're right! It's a bug. I have fixed it in https://github.com/enable3d/enable3d/commit/5a55289598625ff8a49c9c05b1f0fa1caa9962f5.

---

For now you can set the collisionFlags manually using `body.setCollisionFlags(2)`. Until the fix is published, the mass of compound shapes will always be 1.
```ts
const robotBody = new ExtendedGroup()

// I add multiple THREE mesh to robotBody

const compound = [
  { shape: 'box', y: -0.0155, height: 0.03, width: 0.9, depth: 1.5 },
  { shape: 'box', y: -0.2155, height: 0.03, width: 0.45, depth: 1.5 },
  { shape: 'cylinder', radiusTop: 0.025, height: 0.2, radiusBottom: 0.025, radiusSegments: 7 }
]

// @ts-ignore
this.physics.add.existing(robotBody, { compound: compound, collisionFlags: 2, mass: 1 })

console.log(robotBody.body.getCollisionFlags())

setTimeout(() => {
  robotBody.body.setCollisionFlags(2)
  robotBody.position.set(2, 4, 2)
  robotBody.body.needUpdate = true

  robotBody.body.once.update(() => {
    // set body back to dynamic
    robotBody.body.setCollisionFlags(0)

    // if you do not reset the velocity and angularVelocity, the object will keep it
    robotBody.body.setVelocity(0, 0, 0)
    robotBody.body.setAngularVelocity(0, 0, 0)
  })
}, 2000)
```

**Comment by tawjaw** [comment]
Hi @yandeu 
Thanks for the reply. That works. 

How can I set a position to one of the objects relative to another object while both are physics objects?

Let's say I have two physics boxes. Box1's position is to be set as input
Box2's position is relative to Box1, for example (1,1,1) with respect to the axis of Box1.

**Comment by tawjaw** [comment]
never mind, I am setting both to the same reset position and angle and then I am using translate. 

I didn't realize translate can work with physics objects like setting the position does.
