### ISSUE TITLE
Add cloth physical properties to GLB

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#52]
I want to add cloth physical properties to GLB, but I don't know how to do it. Can you give me some suggestions？

**Comment by yandeu** [comment]
You mean like here https://threejs.org/examples/webgl_animation_cloth.html?

I have not implemented that yet.

**Comment by xx0618** [comment]
Yes, I am working on a clothing display project and want to add such a function, but I checked a lot of information on the Internet, but it is not suitable. I don't know where there is a physical attribute package with fabric that can be added to GLB.

**Comment by yandeu** [comment]
I have never done a cloth physics before. But it should be possible with ammo.js.

Just to be sure, with glb you mean the binary version of gltf?

**Comment by xx0618** [comment]
Yes, glb -- the binary version of gltf. 
Of course, how cloth physical energy is added to GLTF is also very good.

**Comment by yandeu** [comment]
Softbody Cloth is now available in enable3d, but I don't know how to apply it to an existing gltf model.
See the example: https://enable3d.io/examples/softbody-cloth.html

**Comment by xx0618** [comment]
Thank you very much!

**Comment by BOXNYC** [comment]
I'll make a new Issue if you'd like, but since were discussing it, how do I add SoftBody to a "As Physics Extension for three.js" type of Enable3d project?

Currently I only see the ability to set: 
```{ softBodies: true }```
... when using a "Stand Alone"  (enable3d.framework.0.21.0.min.js) type of project.

My project uses 8th wall which defines the Three.js scene in which I'm adding my Enable3d to, and requires SoftBody physics, so I cant use Stand Alone.

Thanks!
Joe

**Comment by yandeu** [comment]
I guess you should be able to pass `{ softBodies: true }` to `accessThirdDimension()`.

**Comment by BOXNYC** [comment]
Interesting. What is that a method of? I assume it needs to be called before Ammo is compiled as without it, methods like Ammo.btSoftBodyHelpers don't exist.

**Comment by yandeu** [comment]
Oh no sorry. I read it wrong.

For the three.js extension you should pass it to:
`new AmmoPhysics(scene, { options } )`

**Comment by BOXNYC** [comment]
Awesome, that worked! BUT everything fails with this error:

```Ammo.btSoftBodyRigidBodyCollisionConfiguration is not a constructor ( setupPhysicsWorld physics.ts:237 )```

**Comment by yandeu** [comment]
Try the ammo files from kripken:
https://github.com/kripken/ammo.js/tree/master/builds

**Comment by BOXNYC** [comment]
In addition to your enable3d.ammoPhysics.0.21.0.min.js file? Does it matter if I add it before or after it?

**Comment by yandeu** [comment]
No, you have to add those files to a public directory and point the `PhysicsLoader()` to it.

**Comment by BOXNYC** [comment]
Ahh, so I changed the path from “lib/moz” to “lib”, and it’s no longer failing, but I now collisions aren’t working. Now has this warning:

`HACD unavailable in included build of Ammo.js`

I have a bunch of physics.add.existing( mesh, { shape: ‘hacd’ } ) lines.

I’ll try other shapes and BRB. Thanks!

**Comment by BOXNYC** [comment]
I still haven’t finished my softBody tests, but it looks like these are the caveats in using softBody physics in a Enable3d “As Physics Extension for three.js“:

1. Use kripken’s versions of Ammo.js. Ex: `new AmmoPhysics( ‘/lib’, {} )`
2. Set softBodies: true. Ex `new AmmoPhysics( path, { softBodies: true } )`
3. Don’t use any HACD shapes

Will return with a confirmation on this list once I’ve completed my tests.

Thanks for a really awesome engine. Sorry to hijack this issue.

cheers
