### ISSUE TITLE
Write documentation for this.warpSpeed()

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#53]
After canceling 'this.third.warpSpeed()' statement, customize the scene light, background, etc., if use the 'THREE.OrbitControls' statement, you cannot place the cursor in the dynamically added <input>, that is, you cannot enter information in the newly created <input>.
```js
//this.third.warpSpeed('-ground')
new THREE.OrbitControls(this.third.camera, this.scale.parent)

let show_con = document.createElement( 'div' );
show_con.setAttribute( 'onblur', 'showinput()' );
	
let input_con = document.createElement( 'input' );
input_con.setAttribute( 'type', 'text' );
input_con.setAttribute( 'id', 'input' + new_name );
	
let button_con = document.createElement( 'input' );
button_con.setAttribute( 'type', 'button' );
button_con.setAttribute( 'onclick', 'showinput()' );
button_con.setAttribute( 'value', '添加' );

show_con.append( input_con );
show_con.append( button_con );
document.body.appendChild(show_con);
```

**Comment by xx0618** [comment]
I used ‘this.third.warpSpeed()’ to load ‘OrbitControls’ and then customize other content, which solved this problem.

**Comment by yandeu** [comment]
Hope you don't mind if I reopen this issue until I wrote a proper documentation for `warpSpeed()`, since there are some advanced use cases no one knows about yet.

**Comment by xx0618** [comment]
It's ok. I don’t know many functions of ‘enable3D’ yet, so I can just learn it.
Hope to publish an example of ‘this.warpSpeed()’ soon.

**Comment by yandeu** [comment]
Done in https://github.com/enable3d/enable3d-website/commit/2899433b1da40d738a7e2f7adddef2d81160ace1
