### ISSUE TITLE
How to make the scene adapt to the screen?

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#54]
How to make the scene adapt to the screen? Currently when I change the screen size, the scene will not change with the screen.
![20201113153452](https://user-images.githubusercontent.com/71865768/99133883-b0315c80-2656-11eb-91b8-45ac8df18dea.png)

**Comment by yandeu** [comment]
With Phaser you can use the [ScaleManager](https://photonstorm.github.io/phaser3-docs/Phaser.Scale.ScaleManager.html):

```ts
const config = {
  type: Phaser.WEBGL,
  transparent: true,
  scale: {
    mode: Phaser.Scale.RESIZE, // Set this to RESIZE
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: window.innerWidth,
    height: window.innerHeight
  },
  scene: [MainScene],
  ...Canvas()
}
```
In Standalone mode you can do this:

```ts
const resize = () => {
  const newWidth = window.innerWidth
  const newHeight = window.innerHeight

  this.renderer.setSize(newWidth, newHeight)
  this.camera.aspect = newWidth / newHeight
  this.camera.updateProjectionMatrix()
}

window.onresize = resize
resize()
```

**Comment by yandeu** [comment]
Here [an example](https://enable3d.io/examples/resize-window.html).

**Comment by xx0618** [comment]
Thank you very much! ! !

**Comment by yandeu** [comment]
You're welcome 😁
