### ISSUE TITLE
Multiple canvas - tracking possitions

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#56]
Hello,

is there any possibilites, to track canvas 3d possitions, and render it on canvas 2d? 

f.e.:
i've got "magic skill", which im rendering using 2d canvas (on phaser extension). 
i'd like to render this skill on possition exaclty same than 3d object is in 3d area. 

so far, I've assigned the 2d skill a rigid cords - like x:300, y:200, but this method is tragic - e.g. I can't scale the game window because the skill then renders where it shouldn't. 

I would like the 2d element from the phaser to be taken into account for the 3d element from three, or for the 3d element to pass to the 2d element of the cord where it should be rendered in the frame buffer. 

https://i.imgur.com/iOmsu3c.png

**Comment by yandeu** [comment]
I once created a function for this, but I'm not sure if it still works. It's in [here](https://github.com/enable3d/enable3d/blob/master/packages/threeGraphics/src/plugins/transform.ts).

**Comment by Trusiak** [comment]
The functions work well, but if you go one step further and simulate 2d phaser objects, on canvas 3d three?
i mean, we have a spritesheet created directly using a phaser and now we want it to become part of the 3d scene - is there possible? This would give you an amazing opportunity to create optimization.

Although we now have functions from2dto3d, but it only returns a vector - having it i can't add a 2d element to the 3d scene, but only can I create another 3d object in place of that with 2d - unless I don't know about something? :smile:

**Comment by yandeu** [comment]
I improved the code a lot in https://github.com/enable3d/enable3d/commit/f0afaa201947b72167f5d8e27e84114ce4edae46. Now both `from2dto3d` and `from3dto2d` work great. 

```ts
// we have a 2d rectangle (rect) and a 3d box

// normalize values
const x = (this.rect.x / this.cameras.main.width) * 2 - 1
const y = -(this.rect.y / this.cameras.main.height) * 2 + 1

// get position in 3d space, 10 units away from the camera
const position = this.third.transform.from2dto3d(x, y, 10)
if (position) {
  const { x, y, z } = position
  this.box.position.set(x, y, z)
}
```

Once the new version is released, I will publish some examples. I will leave this issue open until then.

**Comment by yandeu** [comment]
This has been improved and there are two examples available: 
- https://enable3d.io/examples/sync-2d-to-3d.html
- https://enable3d.io/examples/sync-3d-to-2d.html
