### ISSUE TITLE
How to put enable3d on the server?

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#57]
I have a domain name and server, and enable3d is part of the project. How should I set it to make enable3d work?

**Comment by HadrienRivere** [comment]
If you have a server (vps). You just need to install Ngix and make a (reverse proxy). Once you have set up the (reverse proxy) along with your domain. Just look for the www folder and drop the src files from your enable3d project. Now simply go to your domain address and see your project run correctly.

**Comment by xx0618** [comment]
Thank you very much for your reply. I cannot log in to this website these days, so I will reply to you today. I will try as you said. Thanks again!

**Comment by xx0618** [comment]
@HadrienRivere Thanks again, according to your method, with the help of colleagues, it can already run normally on the server!
