### ISSUE TITLE
Use 3d in 2d phaser

### ISSUE THREAD

**Issue by koljakutschera** [enable3d/enable3d#58]
Hey,

Scanned through the docs and could not find out if the following is possible with this (awesome!) lib so iam asking here:

Is it possible to render a 3d character with animations (mixamo and stuff) in a 2d phaser world. For example i want to add the character on a platformer tilemap using the default phaser arcade physics. So it will be a general phaser game but with a 3d character in a 3d container. Something like phasers meshes but supporting animations and stuff... if possible are there any examples?

Thank you

**Comment by yandeu** [comment]
Yes, it is possible, but not documented yet. And there are no examples for now.

Please follow this issue: https://github.com/enable3d/enable3d/issues/56

**Comment by yandeu** [comment]
Closed in favor of #56
