### ISSUE TITLE
physics.js:107 Constant reassigned: obj

### ISSUE THREAD

**Issue by xf-salva** [enable3d/enable3d#59]
Hello, i'm trying test phaser-extension with shadow-cljs  and get this error.

Closure compilation failed with 1 errors
--- node_modules/@enable3d/ammo-physics/dist/physics.js:107
Constant reassigned: obj

**Comment by yandeu** [comment]
Unfortunately I don't know ClojureScript at all :/

Maybe you want to check out the [enable3d-phaser-project-template](https://github.com/enable3d/enable3d-phaser-project-template). It uses TypeScript.

**Comment by yandeu** [comment]
I have fixed this issue in https://github.com/enable3d/enable3d/commit/41b742749073fe819b737ed37eab5985d95241db.

**Comment by xf-salva** [comment]
thanks

**Comment by yandeu** [comment]
You're welcome :)
