### ISSUE TITLE
How to set default world scale?

### ISSUE THREAD

**Issue by quacrobat** [enable3d/enable3d#6]
I see the library expects geometry to be in meters. Is there a way to set that to mm for example?
the debugger objects are too small and they seem to be telling me the colliders are too small too because my meshes are scaled up.

**Comment by yandeu** [comment]
In Three, it does not matter what you use. They are just units. Could be cm, mm, inch, whatever you want.

But when you use physics, it is recommended to use meters.

From the Bullet Physics Manual: 
> **Collision Margin**
Bullet uses a small collision margin for collision shapes, to improve performance and reliability of the collision detection. It is best not to modify the default collision margin, and if you do use a positive value: zero margin might introduce problems. By default this collision margin is set to 0.04, which is 4 centimeter if your units are in meters (recommended). 

> **Avoid very small and very large collision shapes**
The minimum object size for moving objects is about 0.2 units, 20 centimeters for Earth gravity. If smaller objects or bigger gravity are manipulated, reduce the internal simulation frequency accordingly, using the third argument of btDiscreteDynamicsWorld::stepSimulation. By default it is 60Hz. For instance, simulating a dice throw (1cm-wide box with a gravity of 9.8m/s2) requires a frequency of at least 300Hz (1./300.). It is recommended to keep the maximum size of moving objects smaller then about 5 units/meters.

> **Avoid huge or degenerate triangles in a triangle mesh**
Keep the size of triangles reasonable, say below 10 units/meters. Also degenerate triangles with large size ratios between each sides or close to zero area can better be avoided.
