### ISSUE TITLE
Ammo is not a function (headless mode v20)

### ISSUE THREAD

**Issue by bricknim** [enable3d/enable3d#60]
I have installed latest Headless mode and run the example code in Headless category,
but It has been like this pics.

![image](https://user-images.githubusercontent.com/63555096/100539421-aecc7a80-3279-11eb-90df-0654b1fb879d.png)
![image](https://user-images.githubusercontent.com/63555096/100539427-bdb32d00-3279-11eb-835b-729c96a9870d.png)

**Comment by yandeu** [comment]
Can you give me access to your repository?

**Comment by bricknim** [comment]
I'm not using github well, so can I send a google drive link included my node_modules folder?

**Comment by yandeu** [comment]
Please exclude the node_modules folder.

**Comment by bricknim** [comment]
https://drive.google.com/drive/folders/1Ixss0e7sbgFMDEsbGveDssPp3sg-xMP8?usp=sharing

You can select whether to include node_modules in this drive link.

**Comment by yandeu** [comment]
I see. There is a bug in v20. Please install v19 instead:
```console
npm i @enable3d/ammo-on-nodejs@0.19.0
```

**Comment by yandeu** [comment]
It has been fixed in https://github.com/enable3d/enable3d/commit/5aaca2bce4291e574f718007c6514e2a4f9d3a48.

**Comment by 8Observer8** [comment]
I installed this version `npm i @enable3d/ammo-physics@0.19.0` But I see the error in my browser: `main.js:5 Uncaught TypeError: Ammo is not a function at window.onload (main.js:5)`

```
const Ammo = require('@enable3d/ammo-physics');

window.onload = () =>
{
    Ammo().then(start);

    function start() {
        console.log("start");
        setupPhysicsWorld();
    };

    function setupPhysicsWorld() {
        console.log("setupPhysicsWorld");
    }
};
```

**Comment by yandeu** [comment]
Please take a look at [this file](https://github.com/enable3d/enable3d/blob/master/packages/dev/src/physics.ts).

`@enable3d/ammo-physics` does not expose ammo. You can use `PhysicsLoader` to load the right ammo version (wasm or js) from a public folder.
_In the example above from the `/lib` folder._

**Comment by 8Observer8** [comment]
```js
const { PhysicsLoader } = require('@enable3d/ammo-physics');

window.onload = () =>
{
    const startPhysics = () =>
    {
        PhysicsLoader('/lib', () => { console.log("startPhysics"); });
    };

    startPhysics();
};
```

wasmLoader.js:25 GET http://localhost:8080/lib/ammo.wasm.js net::ERR_ABORTED 404 (Not Found)
loadScriptAsync @ wasmLoader.js:25
loadAmmoModule @ wasmLoader.js:30
PhysicsLoader @ physicsLoader.js:10
startPhysics @ main.js:7
window.onload @ main.js:10
load (async)
1.@enable3d/ammo-physics @ main.js:3
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
wasmLoader.js:21 Uncaught Error: failed to load /lib/ammo.wasm.js
    at HTMLScriptElement.tag.onerror (wasmLoader.js:21)

**Comment by 8Observer8** [comment]
I copped three from from here: https://github.com/enable3d/enable3d/tree/master/packages/dev/lib to my `public/lib` directory:

- ammo.js
- ammo.wasm.js
- ammo.wasm.wasm

Now I see that the PhysicsLoader callback works but I see this error:

![image](https://user-images.githubusercontent.com/3908473/102014092-af7f0980-3d6d-11eb-9479-909cb6bef0db.png)

**Comment by yandeu** [comment]
Your server does not seem to send the right response header. But, I guess, as long as it works, you can ignore these warnings for now.

**Comment by 8Observer8** [comment]
>> Your server does not seem to send the right response header.
I use http-server: https://www.npmjs.com/package/http-server

I want to use pure Ammo.js functions:
```js
function setupPhysicsWorld(){

    let collisionConfiguration  = new Ammo.btDefaultCollisionConfiguration(),
        dispatcher              = new Ammo.btCollisionDispatcher(collisionConfiguration),
        overlappingPairCache    = new Ammo.btDbvtBroadphase(),
        solver                  = new Ammo.btSequentialImpulseConstraintSolver();

    physicsWorld           = new Ammo.btDiscreteDynamicsWorld(dispatcher, overlappingPairCache, solver, collisionConfiguration);
    physicsWorld.setGravity(new Ammo.btVector3(0, -10, 0));
}
```

I created the "headless" AmmoPhysics physics object. Could you, please, show a minimum example that will print a sphere coordinates that falls on a ground. But without Three.js in "headless" mode.

```js
const { PhysicsLoader, AmmoPhysics } = require('@enable3d/ammo-physics');

window.onload = () =>
{
    const startPhysics = () =>
    {
        PhysicsLoader('/lib', () =>
        {
            console.log("startPhysics");
            const physics = new AmmoPhysics("headless");
            physics.add.ground({ width: 50, height: 50 });
        });
    };

    startPhysics();
};
```

**Comment by yandeu** [comment]
For a sphere use `physics.add.sphere()`.

There are 3 headless examples here: https://enable3d.io/examples.html

The first example prints a falling box.

**Comment by 8Observer8** [comment]
But what if I want to use another "solver", "dispatcher" and so on. Can I set up my physics world with my configurations?

I write this example for "headless" client:

```js
const { PhysicsLoader, AmmoPhysics } = require('@enable3d/ammo-physics');

window.onload = () =>
{
    const startPhysics = () =>
    {
        PhysicsLoader('/lib', () =>
        {
            console.log("startPhysics");
            const physics = new AmmoPhysics("headless");

            const ground = physics.add.box({
                name: 'ground',
                width: 40,
                depth: 40,
                collisionFlags: 2,
                mass: 0
            });

            const box = physics.add.box({ name: 'box', y: 5 });

            const timeStep = 16;
            for (let i = 0; i < 60; ++i)
            {
                physics.update(timeStep);
                console.log(box.position.x.toFixed(2), box.position.y.toFixed(2), box.position.z.toFixed(2));
            }
        
        });
    };

    startPhysics();
};
```

**Comment by yandeu** [comment]
> But what if I want to use another "solver", "dispatcher" and so on. Can I set up my physics world with my configurations?

I have not added that kind of flexibility yet. But maybe you could manually overwrite `this.physicsWorld` and `this.dispatcher` ([here](https://github.com/enable3d/enable3d/blob/8c7e797025e38fc0d2e2b96e6f52c0e2821b060f/packages/ammoPhysics/src/physics.ts#L206)) after you initialize the physics?

---

Do you wish that I add the option to provide you own confituration? I could add it to the release of v21 next week.

**Comment by 8Observer8** [comment]
I just study Bullet. Ammo has all names from Bullet. Your package allows to use Browserify. I just wanted to use Ammo.js with Browserify with same names like in Bullet/Ammo.js. Could you open all Ammo.js function like in pure Ammo.js? I want to write code like this, with names from pure Ammo.js (Bullet has this names too):

```js
let collisionConfiguration  = new Ammo.btDefaultCollisionConfiguration(),
        dispatcher              = new Ammo.btCollisionDispatcher(collisionConfiguration),
        overlappingPairCache    = new Ammo.btDbvtBroadphase(),
        solver                  = new Ammo.btSequentialImpulseConstraintSolver();

    physicsWorld           = new Ammo.btDiscreteDynamicsWorld(dispatcher, overlappingPairCache, solver, collisionConfiguration);
    physicsWorld.setGravity(new Ammo.btVector3(0, -10, 0));
```

**Comment by yandeu** [comment]
Once you use `PhysicsLoader`, Ammo is available globally. So you have access to everything. 

But the physics setup is done automatically, which I can make more flexible if you want.

---

If your only goal is to use ammo.js on node.js, you do not need enable3d.

**Comment by yandeu** [comment]
I have added support for a custom `setupPhysicsWorld()` in https://github.com/enable3d/enable3d/commit/8d665f8597320fd513121bd12013ef49e18684c4.

You can now do the following:

```js
const setupPhysicsWorld = () => {
  let collisionConfiguration = new Ammo.btDefaultCollisionConfiguration(),
    dispatcher = new Ammo.btCollisionDispatcher(collisionConfiguration),
    overlappingPairCache = new Ammo.btDbvtBroadphase(),
    solver = new Ammo.btSequentialImpulseConstraintSolver(),
    physicsWorld = new Ammo.btDiscreteDynamicsWorld(dispatcher, overlappingPairCache, solver, collisionConfiguration)

  physicsWorld.setGravity(new Ammo.btVector3(0, -10, 0))
  return physicsWorld
}

const physics = new AmmoPhysics(scene, { setupPhysicsWorld })
```

**Comment by 8Observer8** [comment]
>> If your only goal is to use ammo.js on node.js, you do not need enable3d.

What do you mean? Do you mean ammo-node? https://www.npmjs.com/package/ammo-node

**Comment by yandeu** [comment]
I simply mean [ammo.js](https://github.com/kripken/ammo.js/tree/master/builds), no npm package. It work in browsers and on node.js.

**Comment by 8Observer8** [comment]
But I cannot use pure Ammo.js because it does not have npm-packaging. I cannot use Browserify with it. I just use pure Ammo.js now for learning Ammo.js and Bullet. Maybe I will use your package for production. But I do not sure how simple or difficult will be to rewrite pure Ammo to @enable3d/ammo-physics. You hid all Bullet API. It is difficult to study Bullet and your package together. It would great if you keep all pure Bullet/Ammo API.

**Comment by 8Observer8** [comment]
I found a solution how to use Ammo.js with Browserify:

```npm install kripken/ammo.js```

```js
const Ammo = require("ammo.js");

function main()
{
    Ammo().then(start);

    function start()
    {

        //code goes here
        console.log("init");
    }
}

window.onload = main();
```

**Comment by yandeu** [comment]
With the release of v21, this has been fixed.
