### ISSUE TITLE
PointerDrag + PointerLock broken on Safari

### ISSUE THREAD

**Issue by Ithamar** [enable3d/enable3d#61]
This can be easily seen with the FantasyBook example shown on the website, no camera movement possible.

After some testing it turns out that Safari does not return movement{X,Y} values in the pointermove events. This means it will always return 0, making moving in any direction except forward impossible.

A quick hack replacing pointermove with mousemove event in PointerDrag makes it come back alive again. I'm more then happy to do more testing and create a PR for this, but I thought we might want to discuss first if this would be acceptable and/or if you see better ways of fixing this ;)

**Comment by yandeu** [comment]
Glad you noticed and reported it :)

To be honest, I have never tested it on Safari. I wrote the first version of enable3d in a very short time. I never put much attention to functions like PointerDrag and PointerLock. I guess it would help to look how other library, like Phaser for example, do it.

I personally do not know what is the best cross-browser way to do it.

**Comment by Ithamar** [comment]
Okay, I'll take a look and come up with a PR for it then.

**Comment by yandeu** [comment]
Hi @Ithamar,

I have just released the first version of an input library I made, which I plan to integrate into enable3d.

I remember you having an issue with `pointerdown` on safari.

I would help enormously if you could test it?

```console
git clone https://github.com/yandeu/tap.git

cd tap

npm install

npm run dev
```

Thanks a lot!

Regards,

Yannick
