### ISSUE TITLE
TriMesh physics offset issues

### ISSUE THREAD

**Issue by Ithamar** [enable3d/enable3d#62]
I've just started playing with enable3d, and I really like it. When going through the Fantasy Book example, I noticed the comments and code regarding "unexpected offset" in the physics concave meshes. I did a little research and I found that the offset is exactly the mesh's parent object location ;)

The problem as far as I can see, is the code in [_iterateGeometries](https://github.com/enable3d/enable3d/blob/41b742749073fe819b737ed37eab5985d95241db/packages/ammoPhysics/src/three-to-ammo.js#L681) which builds the transform assuming the "root" has the identity matrix as transform, since the body will get the local position/rotation of the "root".

However, this is not correct. If any of its parents has any transform (e.g. position/rotation set) these will not be taken into account in calculating the world transform for the physics mesh, resulting in offset/rotated physics.

My matrix math sucks, so I haven't come up with a fix for it yet, but I thought I'd share, for any other people running into weird positioning issues with this.

**Comment by yandeu** [comment]
Thanks for your research. 

Do you think this is what is causing the issue in https://github.com/enable3d/enable3d/issues/39 and https://github.com/enable3d/enable3d/issues/48? Would be nice if we would be able to fix it :smiley:

**Comment by Ithamar** [comment]
yeah, that is likely the same problem. The issue here is that all physics objects are in world space, while the ThreeJS objects are in local space, and mapping those can be somewhat troublesome. Need to look at how it is currently handled, and what is expected to work (especially for non-static physic objects).

I'll try to find some time to dig deeper and come up with a PR.

**Comment by Ithamar** [comment]
Just reproduced my suspicions in a very simple sample. The relevant code:
```typescript
    this.third.physics?.debug?.enable();

    let wrapper = new ExtendedObject3D();
    wrapper.name = 'wrapper';
    wrapper.position.set(0, 10, 0);
    wrapper.rotation.x = -Math.PI / 3;
    let geo = new THREE.BoxGeometry(10, 10, 10);
    let mesh = new THREE.Mesh(geo, new THREE.MeshNormalMaterial());
    wrapper.add(mesh);
    this.third.add.existing(wrapper);

    wrapper.traverse(child_ => {
      let child = child_ as ExtendedObject3D;
      if (child instanceof THREE.Mesh) {
        this.third.physics.add.existing(child, {
          shape: 'concave',
          mass: 0,
          collisionFlags: 1,
          autoCenter: false,
        })
      }
    })
```

Which results in this:

<img width="586" alt="Schermafbeelding 2020-11-29 om 23 17 01" src="https://user-images.githubusercontent.com/541493/100555019-383f7500-3299-11eb-84fa-23587fd720b6.png">

So yeah, it seems that currently the hierarchy "above" the object is completely ignored. This works fine for scenes built with the factory methods of third.add, but will fail horribly for any big(per) hierarchies with physics.

I'll dig in and see if I can find a good solution for this.

**Comment by yandeu** [comment]
Maybe it is easier to just adjust the enable3d code to the latest commit of [three-to-ammo](https://github.com/InfiniteLee/three-to-ammo). Hopefully, this fixes the issue.

I made some changes to the original three-to-ammo before adding it on Feb 13. But the changes are not visible in the commits.

I just created a repo where all the changes are visible: https://github.com/yandeu/threetoammo-tmp/commit/c310fdeaa1c0c8e9354123bb85b52b8c1a0fefc9

Looks like I made not that many critical changes. Should be easy to update.

**Comment by Ithamar** [comment]
Okay, I looked a little closer and I think I've finally figured out how to fix this properly. The idea of three-to-ammo is to create an **ammo shape** that is ignores position and rotation, but follows "world scale" for size (to take into account any scaling set in parent object3d's).
Then the physics system needs to set the position/rotation of the **ammo body** to the world position/rotation of the three.js object, and voila, the end result is a perfectly matching physics object with the three.js object.

Now, on physics update, if the body is Kinematic, we will take the world pos/rot of the three.js object and set those to the ammo body, and if the body is non-kinematic, we will take the world pos/rot of the body and convert them back to local three.js object coordinate system.

Currently, as far as I can see, the enable3d physics system uses local coordinates for everything, which works, since most objects are either added to the (0,0,0) scene object, or an object3d below the scene without any translation/rotation in those wrapper objects.

It fails for loaded models since most of those actually have full hierarchies with objects setting scale/pos/rot of intermediate objects, causing the coordinate systems to diverge.

So, the MR I will be creating will need to update both the three-to-ammo.js (to make scaling work for example) and the physics.ts (for the positioning fixes) to match the behaviour as described above.

Is it ok to do both in a single MR, or would you prefer to have the three-to-ammo update a seperate MR?

**Comment by yandeu** [comment]
I prefer to keep it separate. First, we need to update enable3d to the new three-to-ammo and make sure everything works as before. Then we can modify the local copy of three-to-ammo (keep track of every modified line) to fix the physics offset.

I created a [new branch](https://github.com/enable3d/enable3d/tree/update-three-to-ammo), added the latest three-to-ammo and already successfully tested the giant cube you created above. It looks like it only works with BufferGeometries since `createTriMeshShape` requires the `geometry.index`.
```ts
const createTriMeshShape: (vertices: any, matrices: any, indexes: any, matrixWorld: any, options?: {}) => Ammo.btBvhTriangleMeshShape | null
```
I guess it is possible to transform all loaded models to bufferGeometries before adding physics?

**Comment by yandeu** [comment]
I just merged the unmodified (adjusted imports and formatting) three-to-ammo into the master branch.

_I think it is easier to simply merge everything to the master branch. I rarely work in a team so I don't know what's best._

**Comment by Ithamar** [comment]
> I guess it is possible to transform all loaded models to bufferGeometries before adding physics?

When needed yeah, but in any recent version of THREE all the loaders already return BufferGeometry based models (or at least the popular ones).

The old-style Geometry class is pretty much deprecated these days.

**Comment by yandeu** [comment]
I have successfully adjusted the master branch to the three-to-ammo code.
