### ISSUE TITLE
npm `@enable3d/three-wrapper` package bundle wrong version THREE in `dist` dir

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#65]
i using enable3d with npm/yarn/typescript/angular to write a simulator.

i use it as follow :
```ts
import {
    THREE,
    PhysicsLoader,
    Project,
    Scene3D,
} from 'enable3d';
import {
    ExtendedObject3D,
    ExtendedMesh,
} from '@enable3d/common/dist/types';
import Factories from '@enable3d/common/dist/factories';
import {AmmoPhysics} from '@enable3d/ammo-physics';
```

when i run the code , it show me three is r117:

![图片](https://user-images.githubusercontent.com/6566869/101272104-1297fb80-37c4-11eb-92d3-226a6e7b44b9.png)

and i try to find why. then i get two different version in `@enable3d/three-wrapper` package.

the version r121 in `node_module`  of `@enable3d/three-wrapper` :

![图片](https://user-images.githubusercontent.com/6566869/101272137-78848300-37c4-11eb-804b-3b86776760c6.png)

and the version r117 in `dist` dir of `@enable3d/three-wrapper` :

![图片](https://user-images.githubusercontent.com/6566869/101272159-a7025e00-37c4-11eb-8082-46e1114f047d.png)

*seems like this publish version forgot update the bundle version*

---

but if i import three as follow :

```ts

import {
    // THREE,
    PhysicsLoader,
    Project,
    Scene3D,
} from 'enable3d';
import {
    ExtendedObject3D,
    ExtendedMesh,
} from '@enable3d/common/dist/types';
import Factories from '@enable3d/common/dist/factories';
import {AmmoPhysics} from '@enable3d/ammo-physics';

import {WEBGL} from '@enable3d/three-wrapper/node_modules/three/examples/jsm/WebGL';
import * as THREE from '@enable3d/three-wrapper/node_modules/three';

```

it still r117 and a error happend :

![图片](https://user-images.githubusercontent.com/6566869/101272300-ee3d1e80-37c5-11eb-99c3-0f0711ff9dec.png)

seems like it mix r121 and r117.

so, please fix this issue, thanks you very much !

**Comment by Lyoko-Jeremie** [comment]
i download this project and rebuild it. then manual replace the `dist` dir in my project's `node_module`.
after above, this issue are fixed.

![图片](https://user-images.githubusercontent.com/6566869/101274923-e472e580-37dc-11eb-97be-ce7568105224.png)

![图片](https://user-images.githubusercontent.com/6566869/101274928-ef2d7a80-37dc-11eb-9247-974b0669f67c.png)

so, i can sure that the package release in npm was forgot to rebuild.

please rebuild and release again, thank you very much ~~~

**Comment by yandeu** [comment]
Yes, you are right. I forgot to install the latest version before publishing :/

I plan to release the next version very very soon. I will also update three.js to the latest version.

I will close this issue, since it will automatically be fixed in the next release.
