### ISSUE TITLE
How to control the 3D display so that he can only turn left and right instead of up and down.

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#66]
How to control the 3D display so that he can only turn left and right instead of up and down.

**Comment by yandeu** [comment]
Do you mean the OrbitControls?

**Comment by yandeu** [comment]
Here the documentation of OrbitControls:
https://threejs.org/docs/#examples/en/controls/OrbitControls

And here an example of how you get and modify the OrbitControls:
```js
this.warpSpeed().then(({ orbitControls }) => {
  if (orbitControls) {
    // get the polarAngle
    const currentAngle = orbitControls.getPolarAngle()
    // lock polarAngle to currentPolarAngle
    orbitControls.minPolarAngle = currentAngle
    orbitControls.maxPolarAngle = currentAngle
    // update orbitControls
    orbitControls.update()
  }
})
```

**Comment by xx0618** [comment]
Thank you very much for your prompt and comprehensive answer. But in this case, warpSpeed cancelled ('-ground','-sky') all appear again, and it cannot be cancelled again. I canceled orbitControls in warpSpeed, and achieved the desired function with THREE.OrbitControls(camera, this.scale.parent). But I still want to know if there is a way to make the content cancelled by warpSpeed no longer appear in your method?

**Comment by yandeu** [comment]
I honestly don't know what you mean.

If you want all features except ground and sky, you do `this.warpSpeed('-ground', '-sky').then( ... )`.

If you only want the OrbitControls and nothing else, you do `this.warpSpeed('orbitControls').then( ... )`.

**Comment by yandeu** [comment]
Taking look at the source code is maybe easier:

https://github.com/enable3d/enable3d/blob/master/packages/threeGraphics/src/plugins/warpSpeed.ts

**Comment by xx0618** [comment]
At the beginning, the content cancelled by warpSpeed still appeared, until the desired effect was suddenly achieved. Thanks again!

**Comment by yandeu** [comment]
`this.warpSpeed` returns a promise. You can also await it:

```js
async create() {
   const { OrbitControls } = await this.warpSpeed()
}

**Comment by xx0618** [comment]
Okay, I think I will use asynchronous loading in the future, and I will try this method at that time.

**Comment by yandeu** [comment]
I still have to finish the documentation for `warpSpeed()`. I will close this issue in favor of #53.
