### ISSUE TITLE
what means of `mass` ? & the `collisionFlags` in `physics.add.existing()` not work.

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#67]
what means if the `mass` ? i dont find a explanation in document.

---

in the document : https://enable3d.io/docs.html#body-types
it tell me the `collisionFlags` 1 is a Static object, and `These object are just there but do not move at all.`
and , 2 is a Kinematic object, `These bodies do NOT react to force or gravity.`.

but when i write follow code :

```ts


        this.physics = new AmmoPhysics(this.scene, {
            gravity: {x: 0, y: -0.98, z: 0},
        });
        this.factory = this.physics.factory;
        this.physics.debug?.enable();

            {
                const a = this.factory.add.box(
                    {width: 100, height: 100, depth: 1, name: 'wall-l',},
                    {lambert: {opacity: 0.1, color: '#ffffff', transparent: true}},
                );
                a.position.z += 50.5;
                a.position.y = 50;
                this.physics.add.existing(a, {collisionFlags: 1,});   // <======= see this `collisionFlags`
            }

```
if i set collisionFlags as 1, it will not follow the gravity but will push by other object.

if i set collisionFlags as 2, it will not follow the gravity and not push by other object.

i think seems like the `1 - Static` have some thing wrong ?

**Comment by yandeu** [comment]
> what means if the `mass` ?

Well, it simply is the mass of the physical object: See https://en.wikipedia.org/wiki/Mass

---

These are the correct values for the **collisionFlags**.
- 0 - Dynamic
- 1 - Static
- 2 - Kinematic
- 4 - Ghost (aka Sensor or NO_CONTACT_RESPONSE).

You can also combine values. For example, set 6 if your objects need to be Kinematic and Ghost (2+4).

---

> if i set collisionFlags as 1, it will not follow the gravity but will push by other object.

This depends on the mass of the static object. You should set it to zero. I have just set the default mass of static objects to zero (see https://github.com/enable3d/enable3d/commit/44e48c2723c5c0f70779105eab6ca95a05e7aaf3)

---

In your case, just use `this.physics.add.existing( a, { collisionFlags: 1, mass: 0 });` for a truly static object.

**Comment by yandeu** [comment]
I also just adjusted the default mass of kinematic objects to zero.
I guess I can close this issue now.
