### ISSUE TITLE
Standalone mode with functional paradigm?

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#68]
what would be the syntax of Standalone mode for the functional paradigm?

**Comment by yandeu** [comment]
I'm sorry, I don't know what you mean.

**Comment by HadrienRivere** [comment]
> I'm sorry, I don't know what you mean.

I'm Sorry. I mean if it's possible. use functions instead of classes in stand-alone mode. Any example?

**Comment by yandeu** [comment]
I wrote this library with modern JavaScript. I don't think it is possible. 
Why don't you want to use classes?

**Comment by HadrienRivere** [comment]
> I wrote this library with modern JavaScript. I don't think it is possible.
> Why don't you want to use classes?

I thought the functions were modern code in javascript. Well it turns out that I'm writing a game along with React and hooks and it's very rare to see classes in functional code.

**Comment by yandeu** [comment]
Nope, classes are new modern features like `let` and `const` and were introduced not long ago in ES6. See https://en.wikipedia.org/wiki/ECMAScript#6th_Edition_%E2%80%93_ECMAScript_2015.

All examples on the front page of React (https://reactjs.org/) use classes. Hooks seem to be a fancy new thing if you learn React these days. But honestly, I don't like them. I personally never use hooks when I write JSX (I also never use React to write JSX).

**Comment by HadrienRivere** [comment]
> Nope, classes are new modern features like `let` and `const` and were introduced not long ago in ES6. See https://en.wikipedia.org/wiki/ECMAScript#6th_Edition_%E2%80%93_ECMAScript_2015.
> 
> All examples on the front page of React (https://reactjs.org/) use classes. Hooks seem to be a fancy new thing if you learn React these days. But honestly, I don't like them. I personally never use hooks when I write JSX (I also never use React to write JSX).

Well, it looks like I have to study more hahaha. well I'll use classes along with hooks.

**Comment by yandeu** [comment]
Let me just show you one thing. React is not the only framework using JSX. There are many. I also built one called [Nano JSX](http://nanojsx.io/) (not finished yet). It includes many cool features. One of them is, you can use JSX without a compiler and it is only 3.6kB small.

I have just updated some code of the enable3d website to use Nano JSX. There, I create small bits of JSX elements and append them to the DOM. Maybe you find it interesting. 

Here the modified code: https://github.com/enable3d/enable3d-website/blob/master/src/js/examples.js

**Comment by HadrienRivere** [comment]
I regularly use more NextJs than react. It would be amazing to see Nano SSR. I'll look at your example right now.

**Comment by HadrienRivere** [comment]
> Let me just show you one thing. React is not the only framework using JSX. There are many. I also built one called [Nano JSX](http://nanojsx.io/) (not finished yet). It includes many cool features. One of them is, you can use JSX without a compiler and it is only 3.6kB small.
> 
> I have just updated some code of the enable3d website to use Nano JSX. There, I create small bits of JSX elements and append them to the DOM. Maybe you find it interesting.
> 
> Here the modified code: https://github.com/enable3d/enable3d-website/blob/master/src/js/examples.js

😱😱😱 Right now I'm looking at his example.
