### ISSUE TITLE
Can I disable collision between some object? (Collision Filtering | Selective Collisions)

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#69]
i need place something (like a barrier or a wall) across the ground or other object. 

all those are be config as `mass: 0, collisionFlags: 1` , but when 5~6 object overlapping on same place , the performance slow down to about 10 fps. but if i move then out or dont add then to physics , i will get 60 fps like normal .

seems like those static object wast so many cpu to do useless collision calc.

can i disable collision check between those object ?

---

BTW:
i'm sorry for that i dont have any knowledge about how to use the `ammo.js` or the `bullet3` , i dont find any document from `ammo.js` project about how to use them .

**Comment by Lyoko-Jeremie** [comment]
i find the bullet3 [document ](https://github.com/bulletphysics/bullet3/blob/master/docs/Bullet_User_Manual.pdf) , 

in page 17, it tell me i can use the mask or the filter callback.

so, how can i use it ?

**Comment by yandeu** [comment]
Can you share your code? I do not notice that issue.

Yes, it is possible to disable the collision checks. It is called collisionGroup and collisionMask. I added it in October (https://github.com/enable3d/enable3d/commit/4ddc4f15c512678e08f0bf97a0f88ea4a2959408). It will be available in version 0.21.0. Once released you will find an example on enable3d.io.

**Comment by Lyoko-Jeremie** [comment]
can you add the `Filtering Collisions Using a Broadphase Filter Callback` function ?

the collisionMask only support 32 bit mask, seems like it not enough for me .

**Comment by Lyoko-Jeremie** [comment]
```ts

export class AreaTexture {
    async load(url: string) {
        const loader = new THREE.GLTFLoader();
        return loader.loadAsync(
            url,
        ).then((gltf: THREE.GLTF) => {
            const groups = gltf.scene;

            return groups.children.map((T: THREE.Mesh, i: number) => {
                // const o = new ExtendedObject3D();
                T.material =
                    new THREE.MeshLambertMaterial({color: '#ffa5a5'});
                // o.add(T);
                // return o;
                return new ExtendedMesh(
                    T.geometry,
                    T.material
                ) as unknown as ExtendedObject3D;
            });
        });
    }
}

```

```ts



        {
            const gs = new AreaTexture();
            gs.load('assets/module/area_1.glb')
                .then(G => {
                    G.forEach((T, i) => {
                        T.position.y = 0.5;

                        // switch (i) {
                        //     case 1:
                        //         T.position.x = 10;
                        //         T.position.z = 20;
                        //         break;
                        //     case 2:
                        //         T.position.x = 20;
                        //         T.position.z = -20;
                        //         break;
                        //     case 3:
                        //         T.position.x = -20;
                        //         T.position.z = -10;
                        //         break;
                        //     case 4:
                        //         T.position.x = -10;
                        //         T.position.z = 20;
                        //         break;
                        //     case 5:
                        //         T.position.x = -20;
                        //         T.position.z = 20;
                        //         break;
                        //     case 6:
                        //         T.position.x = -10;
                        //         T.position.z = -15;
                        //         break;
                        //     default:
                        //         break;
                        // }

                        this.scene.add(T);
                        this.physics.add.existing(T, {
                            mass: 0,
                            collisionFlags: 1,
                            shape: 'concaveMesh',
                        },);
                    });
                });
        }

```

the `area_1.glb` have 7 object in the (0,0,0) pos.

now i forgot how to reproduct it, so strange....

**Comment by Lyoko-Jeremie** [comment]
sorry for that, seems like `` cannot impl in other language except C++.

my first language is C++, and seems like the old document some thing out date .

i took the [doc 1](https://docs.panda3d.org/1.10/python/programming/physics/bullet/collision-filtering) and the [doc 2](https://docs.panda3d.org/1.10/python/programming/physics/bullet/collision-filtering) , seems like the `collisionGroup and collisionMask` have different work way from the document.

![图片](https://user-images.githubusercontent.com/6566869/101944117-2d84c880-3c27-11eb-8d4e-b609550942cb.png)

```c++
bool collides = (proxy0->m_collisionFilterGroup & proxy1->m_collisionFilterMask) != 0;
collides = collides && (proxy1->m_collisionFilterGroup & proxy0->m_collisionFilterMask);
```

you can see that, in the old document, the collisionGroup are AND with collisionMask to check the collision , they are work together.

but in **doc 1** , the bitMask and groupMask only work one, it control with `bullet-filter-algorithm` value .

**Comment by yandeu** [comment]
> the collisionMask only support 32 bit mask, seems like it not enough for me .

Seems a LOT to me. Sure you need more?

---

You referring a lot to the Panda3D implementation which is not the same. In the official Bullet docs are 3 ways to filter collisions:
- Filtering collisions using masks
_using collisionGroup and collisionMask_
- Filtering Collisions Using a Broadphase Filter Callback
`dynamicsWorld->getPairCache()->setOverlapFilterCallback(filterCallback)`
- Filtering Collisions Using a Custom NearCallback
`mDispatcher->setNearCallback(MyNearCallback)`

It seems that only the first one (masks)  is implemented in ammo.js. Filtering collisions using masks works really great. As mentioned above, I will shortly publish an example.

**Comment by Lyoko-Jeremie** [comment]
by the code:

```c++
bool collides = (proxy0->m_collisionFilterGroup & proxy1->m_collisionFilterMask) != 0;
collides = collides && (proxy1->m_collisionFilterGroup & proxy0->m_collisionFilterMask);
```

32 bit mask seems like only have 32 group can be use.

but i want to impl a env that have 5~500 or more airplane ( tech limit is 256*256*256-256=16,776,960 ), and no-limit number user defined barriers ( seems like will > 20 , or more than 50 ) , i can sure that all barriers will collision with groud, and many of those will collision each other.

in this design, i think the best design is that, group all airplane into group 0 , and the ground and edge wall to group 1 ,  group each barrier to a independent group 2~999 and set them only collision with group 0 , but all the barrier not collision each other.

**Comment by yandeu** [comment]
> 32 bit mask seems like only have 32 group can be use.

Yes, but with the right combination, this is a lot.

> group 0

I think there is no group 0. It starts with Group 1.

---

I think you are looking for something like this:
```js
// default is collisionGroup: 1; collisionMask: -1
const ground = { group: 1, mask: -1 } // group 1 (001), collides with every group (-1)
const barrier = { group: 2, mask: 5 } // group 2 (010), collides with group 1 and 4 (101)
const airplane = { group: 4, mask: -1 } // group 4 (100), collides with every group (-1)

// Notice that the barrier group does not collide with itself.
```

**Comment by Lyoko-Jeremie** [comment]
> Notice that the barrier group does not collide with itself.

oh, you are right !


seems like i can use this:

```ts

const ground = { group: 1, mask: -1 } // group 1 (001), collides with every group (-1)
const barrier = { group: 2, mask: 4 } // group 2 (010), collides with group 4 (100)
const airplane = { group: 4, mask: -1 } // group 4 (100), collides with every group (-1)

```

i only need barriers only need collides with airplane .

thank you very much ~~~~

**Comment by yandeu** [comment]
You're welcome :)

**Comment by Lyoko-Jeremie** [comment]
hi~ when can i use the CollisionGroup ?
seems like it not impl in the v20.

what about the v20 release date ?

**Comment by yandeu** [comment]
It will be in v21. I plan to release it at the end of this week.

**Comment by Lyoko-Jeremie** [comment]
Hi~ 12 days are gone , i still waiting alone the v21 .....

**Comment by Lyoko-Jeremie** [comment]
@yandeu Merry Christmas and Happy New Year ~
