### ISSUE TITLE
60 FPS Water Demo?

### ISSUE THREAD

**Issue by Thundros** [enable3d/enable3d#7]
Hi @yandeu : First off I would like to say : PLEASE KEEP UP THE GREAT WORK & GIVE YOURSELF A PAT ON THE BACK! You deserve it for this AWESOME piece of software!

Second, I'd like to ask if you could please fix the frame rate on your 3D water demo. I would really like it to work on my NVidia GeForce GTX 960M graphics card. I am on a gaming MSI laptop.

Thank you & once again please do keep up the GREAT work! <3

**Comment by yandeu** [comment]
Hi @Thundros 

Thank you so much. I'm very glad you like it :)

Yes there is a bug, but I already know how to fix it. I just did not have the time yet. See [this topic](https://discourse.threejs.org/t/new-physics-plugin-for-three-js-using-ammo-js/13131/4).

It will be fixed in the next version.

**Comment by Thundros** [comment]
@yandeu : the website demo still is slow with rendering the water example. Just thought I'd let you know, brother.

**Comment by yandeu** [comment]
@Thundros I know. I have committed the fix to github, but not released a new version yet.

It will be fixed, as I wrote above, in the next release.
