### ISSUE TITLE
Black or dark display problems.

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#71]
It is found that it is normal when displaying light colors, but when displaying black or dark colors, the texture will be indistinguishable. I don’t know which setting is wrong? How to deal with it?

This is a black 3D file
![heise](https://user-images.githubusercontent.com/71865768/102753017-7403c100-43a5-11eb-8c00-3748cd6edb75.png)

This is a light-colored coat with dark buttons, the buttons can no longer see the texture
![yanse](https://user-images.githubusercontent.com/71865768/102753044-7f56ec80-43a5-11eb-90af-39fcb02be5a7.png)

Original texture of buttons
![微信截图_20201221155941](https://user-images.githubusercontent.com/71865768/102753159-ac0b0400-43a5-11eb-811a-77e2981e4f21.png)

**Comment by yandeu** [comment]
In the next version, enable3d will use the default three js setting for colors.

If you then still have issues, please use the [three.js forum](https://discourse.threejs.org/) to solve it.

**Comment by xx0618** [comment]
Looking forward to version 0.21

**Comment by HadrienRivere** [comment]
when enable3d forum?

**Comment by yandeu** [comment]
> when enable3d forum?

I don't have the time to manage a forum. And most questions a related to three.js anyways.

**Comment by yandeu** [comment]
> Looking forward to version 0.21

v21 is available. Check if it helps, otherwise, consider asking in the three.js forum.

**Comment by xx0618** [comment]
Version 21 is great. The dark 3D model has been improved, but it is not ideal.
![微信截图_20210105103313](https://user-images.githubusercontent.com/71865768/103600153-bbf81b80-4f41-11eb-99c6-91981c8ac55b.png)

**Comment by xx0618** [comment]
I found it on the Internet that the gltf 2.0 model is dimmed, but I don't know how to solve it. What can I do?

**Comment by HadrienRivere** [comment]
Surely in the Three js forum you will find an answer to this.

**Comment by xx0618** [comment]
Found a way.
Need to be set in the renderer:
```
this.third.renderer.gammaOutput = true
this.third.renderer.gammaFactor = 2.2
```

**Comment by xx0618** [comment]
The above method makes the color not dark, but the color is somewhat white. Adding the following sentence can make the color return to normal.

```
const material = new THREE.MeshStandardMaterial({ color: 0xff0000 })
material.color.convertSRGBToLinear()
```

```
const texture = new THREE.TextureLoader()
texture.enccoding = THREE.sRGBEncoding
```
