### ISSUE TITLE
how to modify the size of the world?

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#72]
Is it possible to modify the size of the world or the sky?

i have the following problem:

IMG 1: 

![Image 1](https://i.imgur.com/MsvjN43.png)

IMG 2:

![Image 2](https://i.imgur.com/Q6Q2533.png)

Well, I have a map size 500 meters x 10 meters. When you reach almost 495 meters, certain objects on the map disappear, once you go beyond 495 meters the objects look but, the sky or world look dark. The question is: Is there any way to change the size of the world or the sky?

**Comment by yandeu** [comment]
WarpSpeed is for quick development.

You can disable certain features and implement your own logic.

Here is [the source](https://github.com/enable3d/enable3d/blob/master/packages/threeGraphics/src/plugins/warpSpeed.ts) of warpSpeed.

I copied the sky from [this example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_lights_hemisphere.html).

I'm sure you will find your answer in the three.js forum.

**Comment by HadrienRivere** [comment]
Well I'm not going to get into this. The best thing I did was to move the map back a little. That's how it worked out. Thank you, I close the issue.
