### ISSUE TITLE
[Request] Release 0.20.1 as bugfix

### ISSUE THREAD

**Issue by HexaField** [enable3d/enable3d#73]
A few bugs that have been solved, especially https://github.com/enable3d/enable3d/pull/63  has been plaguing me for a while. It would be wonderful to get this released while the 0.21 update is still in progress. Maybe also update three to r123 in the mean time too? Thanks a lot. Happy holidays :)

**Comment by yandeu** [comment]
I will release v21 as soon as I'm on my desk.

**Comment by yandeu** [comment]
Done
