### ISSUE TITLE
Use the geometry for collider

### ISSUE THREAD

**Issue by bricknim** [enable3d/enable3d#74]
How about add the Geometry in the Collider Types(like compound, mesh, shapes, etc)?

**Comment by yandeu** [comment]
I'm not exactly sure what you mean.  Can you give an example?

**Comment by bricknim** [comment]
In simply, Just make custom shape(for collider) using a kind of THREE.Geometry.

![image](https://user-images.githubusercontent.com/63555096/103431444-36a7fa80-4c13-11eb-9dbb-720e2f275045.png)

**Comment by yandeu** [comment]
Something like this is already possible, but still a bit limited.

See the second shape from the left:
https://enable3d.io/examples/compare-physics-body-shapes.html

But I think it would be nice to be able to use THREE.Geometry for this.
