### ISSUE TITLE
Question: how can i know a object is collision with some other things ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#76]
i knwon i can register a callback in the `body.on.collision()`  to recevie a collision event, and the event have `start` `collision` `end` types.

now i  only what to now is two object are collision now , or a object is collision with some other things now.

 can i impl it ? how to impl it ?

**Comment by HadrienRivere** [comment]
`body.on.collision((otherObject, event) => {
              if ((otherObject.name)) {
                // do something
              }
            })`

**Comment by Lyoko-Jeremie** [comment]
@HadrienRivere thank you for your example.

and i find a way to known `a object is collision with some other things now` in my dream.

only add otherObject to a list when `start` event and remove it when a `end` event like follow.

```ts

    protected nowCollisionList: Map<string, ExtendedObject3D> = new Map<string, ExtendedObject3D>();
    protected nowCollisionIdList: Map<number, ExtendedObject3D> = new Map<number, ExtendedObject3D>();


        this.g.body.on.collision((otherObject: ExtendedObject3D, event: CollisionEvent) => {
            if (event === 'start') {
                this.nowCollisionList.set(otherObject.name, otherObject);
                this.nowCollisionIdList.set(otherObject.id, otherObject);
            }
            if (event === 'end') {
                this.nowCollisionList.delete(otherObject.name);
                this.nowCollisionIdList.delete(otherObject.id);
            }

```

**Comment by Lyoko-Jeremie** [comment]
seems like this issue can be close.

**Comment by yandeu** [comment]
If someone is reading this, also check out https://github.com/enable3d/enable3d/issues/77.
