### ISSUE TITLE
Question: have a global collision event listener ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#77]
in the [doc](https://enable3d.io/docs.html#collisions) , i can listen collision between two special object .

can i have a listener can listen all the collision event like follow ?

```ts
this.physics.addCollisionListener( (a: ExtendedObject3D, b: ExtendedObject3D, event: string) => {
   console.log(`${a.id} collision  with ${b.id} at ${event}`);
})
```

**Comment by yandeu** [comment]
You can do this:
```ts
// show all collision for object that have { checkCollisions: true }
physics.collisionEvents.on('collision', data => {
  const { bodies, event } = data
  console.log(bodies[0].name, bodies[1].name, event)
})

const box = physics.add.box({ y: 10 })
box.body.checkCollisions = true // set checkCollisions to true
```
I have added it to the docs: https://enable3d.io/docs.html#collisions

Also, I just make `physics.collisionEvents` public (11e74ecdea433b8726ebf516ba1c9f669e374e4d).

**Comment by Lyoko-Jeremie** [comment]
@yandeu i think you can release more small version, like v0.21.1 v0.21.2 for something non-breakable change like this .

**Comment by yandeu** [comment]
Well, you can already use the code above. You only getting a type error if you are using Typescript. Just ignore it with `@ts-ignore`.

**Comment by Lyoko-Jeremie** [comment]
i use `as any` to covert it

```ts
        (this.physics as any).collisionEvents.on('collision', (data: any) => {
            const bodies: ExtendedObject3D[] = data.bodies;
            const event: string = data.event;
            if (event === 'start') {
                console.warn('physics collision ', bodies[0].name, bodies[1].name, event);
            }
        });
```
