### ISSUE TITLE
How to calculate clipping parameters when object is in high speed?

### ISSUE THREAD

**Issue by Smithangshu** [enable3d/enable3d#8]
Hi,
First of thank you for the amazing library. Its very easy to integrate. Only problem I am seeing is when object is in high speed it misses collision, I have seen CCD parameters in document. But is there any rule of thumb to calculate the parameters for different shapes? Moreover I have observed that same parameters sometime works and sometime doesn't. 

So can you please help me to figure out the general formula to handle this kind of situation for any shapes?

**Comment by yandeu** [comment]
> First of thank you for the amazing library. Its very easy to integrate.

Thank you very much :)
Just for curiosity, which module are you using? Phaser Extension?

---

I have never found such a formula. But I guess the best is to set it at about the size of the shape but not bigger.

It works very well in my examples. See [medieval-fantasy-book](https://github.com/enable3d/enable3d-website/blob/master/examples/medieval-fantasy-book.html) for example. There, the shape is a sphere and has a radius of 0.25. I use `setCcdSweptSphereRadius(0.25)`. 
I guess if you have a box with a width of 1, you have to use `setCcdSweptSphereRadius(0.5)`

You can also try increase the fixedTimeStep. `{ maxSubSteps: 10, fixedTimeStep: 1 / 120 }`

Also make sure you use realistic physics sizes. See https://github.com/enable3d/enable3d/issues/6#issuecomment-622410367.

Here the snippet from the example I mentioned above:
```js
/**
  * Add the player to the scene with a body
  */
this.third.add.existing(this.man)
this.third.physics.add.existing(this.man, {
  shape: 'sphere',
  radius: 0.25,
  width: 0.5,
  offset: { y: -0.25 }
})
this.man.body.setFriction(0.8)
this.man.body.setAngularFactor(0, 0, 0)

// https://docs.panda3d.org/1.10/python/programming/physics/bullet/ccd
this.man.body.setCcdMotionThreshold(1e-7)
this.man.body.setCcdSweptSphereRadius(0.25)
```
Hope this helps :)

**Comment by Smithangshu** [comment]
Great I will try this out and thank you soo much for your prompt reply, actually its not the part of the real problem, I am facing. I was looking for a Physics Engine for my scene so researching with a lot of options but found this one is the perfect fit to my scenario so I was testing it with all possible conditions so this query comes up. 

I am currently using it as Threejs extension. One thing I must say that this library is the easiest available option to integrate physics with Threejs. Highly recommended to all those who are looking for physics library for Threejs. 

One more thing I would like to ask you, is it possible to move an object with continuous motion without any acceleration to mimic the continuous airflow from one direction? Actually I am trying to make an opensource volumetric cloud plugin for Threejs since its not yet available.

Scattered:
![image](https://user-images.githubusercontent.com/30255929/81495267-cf78b700-92cc-11ea-93f9-30d59edd6c44.png)
Thunderstorm:
![image](https://user-images.githubusercontent.com/30255929/81495320-1d8dba80-92cd-11ea-85e4-6709474b548e.png)
From bellow towards stormy cloud:
![image](https://user-images.githubusercontent.com/30255929/81495362-72313580-92cd-11ea-9294-06d1067d936e.png)
Inside the cloud to feel the volume:
![image](https://user-images.githubusercontent.com/30255929/81495395-b290b380-92cd-11ea-9605-dacf1fb2908c.png)

Now kind of this I am trying to achieve with your physics engine.
https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Horu.jpg/800px-Horu.jpg

As you can see when cloud touches the peak it appears like smoke from the peak, and another thing cloud will stuck along with the high terrain like the following pic and when it will found the way to pass over the high terrain it will appear like smoke from the edges of the terrain like the above pic.

https://besthqwallpapers.com/Uploads/3-1-2018/35946/thumb2-switzerland-mountains-clouds-mountain-peak-rocks.jpg

I think it is possible with your physics library. But I am getting how to make it possible. 

Can you please help me out?

**Comment by Smithangshu** [comment]
Hi,

One more issue I have found in order to develop using it that is, its not triggering Collision related events if existing mesh is added to the Physics and its body is set to trigger the event. It reacts on collision correctly but it does not trigger the event.

Should I create a new issue for it or we can discuss it in this thread?

**Comment by yandeu** [comment]
> is it possible to move an object with continuous motion without any acceleration to mimic the continuous airflow from one direction? Actually I am trying to make an opensource volumetric cloud plugin for Threejs since its not yet available.

What exactly do you mean? Do you now have something like this?
```js
const cloud = this.third.physics.add.box({ height: 0.5, collisionFlags: 4 })
cloud.body.setGravity(0, 0, 0)
cloud.body.setVelocityX(1)
cloud.body.setVelocityZ(1)
```
> Should I create a new issue for it or we can discuss it in this thread?

Yes, please open a new issue with an example.

> I am currently using it as Threejs extension. One thing I must say that this library is the easiest available option to integrate physics with Threejs. Highly recommended to all those who are looking for physics library for Threejs.

Can I use this and your github username as testimonial on the enable3d website?

**Comment by Smithangshu** [comment]
Hi,

> What exactly do you mean? Do you now have something like this?
Yes, I have this but the problem with that is if object collides with some other object then object's axis rotates to random direction so if the force is applied as per object axis then it will start moving to random direction. That why the solution is needed to be as per physics environment's axis. As same as gravity(-ve Y axis's acceleration). But as you know since it's acceleration so it will increase the velocity with time. But I am looking for constant velocity.

> Yes, please open a new issue with an example.
Ok sure I will.

> Can I use this and your github username as testimonial on the enable3d website?
Yes off-course, I will be glad to help you to promote such a wonderful library.

One more thing, can I simulate soft mesh with it?

>

**Comment by yandeu** [comment]
I see. But normaly if you set `collisionFlags: 4` (which is ghost) the object should not collide with any other object and thus should not loose or gain velocity.

---

You could also make the object ghost and kinematic at the same time with `collisionFlags: 6`. Then you can update its position in your update loop:
```js
update() {
  object.position.x =+ 0.01
  object.position.z =+ 0.01
  object.body.needUpdate = true
}
```

---

Also if your object extends `ExtendedObject3D` and not simply `Object3D` you can call `object.world.theta` to get the theta relative to the world.

---

> Yes off-course, I will be glad to help you to promote such a wonderful library.

Thanks :smiley:

**Comment by Smithangshu** [comment]
Ok I will try to apply this and let you know.

**Comment by yandeu** [comment]
I guess this has been resolved?
