### ISSUE TITLE
problem: AmmoPhysics is not a constructor ?

### ISSUE THREAD

**Issue by salamander-mh** [enable3d/enable3d#81]
`enable3d` is installed by `npm`.

here is my code:
```
import { Project, Scene3D, PhysicsLoader, AmmoPhysics } from 'enable3d';

....
const physics = new AmmoPhysics(this.scene);
physics.debug.enable(true)
```
and I got error: 
```
Uncaught TypeError: enable3d__WEBPACK_IMPORTED_MODULE_1__.AmmoPhysics is not a constructor
```

**Comment by yandeu** [comment]
Do you want to use enable3d as a physics extension for three.js? Then you don't need to install `enable3d`. You need the package `@enable3d/ammo-physics`.

**Comment by yandeu** [comment]
_I will write a better documentation about the different npm packages._

**Comment by salamander-mh** [comment]
@yandeu  thks a lot.

**Comment by salamander-mh** [comment]
@yandeu 
```
import { AmmoPhysics } from '@enable3d/ammo-physics';
...
const physics = new AmmoPhysics(this.scene);
```
I got another error:
```
Uncaught ReferenceError: Ammo is not defined
```

**Comment by yandeu** [comment]
Don't worry. I will create a small example repo later this day.

**Comment by salamander-mh** [comment]
@yandeu  ok

**Comment by yandeu** [comment]
Voila: https://github.com/enable3d/threejs-ammojs-webpack-example

But there is an issue with the colors. Just create all your objects using THREE.something and it should be fine :)
Will fix it in the next version.

**Comment by salamander-mh** [comment]
@yandeu It seems I should add ammo.js to my src folder? I think it's redundant because `@enable3d/ammo-physics` has included it.

**Comment by yandeu** [comment]
Ammo provides a wasm version that can't be bundled. The PhysicsLoader detects if the browser supports wasm and loads the correct file. 

Yes, it is included in the bundle. But I guess I can remove it from there.

**Comment by salamander-mh** [comment]
@yandeu I have to update ammo.js manually?

**Comment by yandeu** [comment]
ammo.js does nearly never get updated.

**Comment by yandeu** [comment]
Also there are different ammo builds. Depending on what functions you need, you have to add a different build.

**Comment by salamander-mh** [comment]
@yandeu thanks a lot. And there are lines around the mesh in your demo, can I hide them?

**Comment by yandeu** [comment]
The red lines? They are for physics debugging. Just remove `physics.debug.enable()` and they will disappear.

**Comment by salamander-mh** [comment]
@yandeu  got it.

**Comment by salamander-mh** [comment]
@yandeu  I have no idea to move mesh from the document.🤣🤣

**Comment by yandeu** [comment]
I don't know what you mean. Have you looked at the awesome examples? https://enable3d.io/examples.html

**Comment by salamander-mh** [comment]
@yandeu  I mean how to let the object move.

**Comment by yandeu** [comment]
Depends, if your object has a kinematic body or a dynamic body.

See these 2 examples:
- [Kinematic Body](https://enable3d.io/examples/kinematic-body-orbiting-around-sun.html)
- [Dynamic Body](https://enable3d.io/examples/camera-lerping-and-player-controls.html)

**Comment by yandeu** [comment]
> Will fix it in the next version.

This issue is fixed if you don't install three.js but use the three.js version provided by enable3d instead.
I have [updated the example](https://github.com/enable3d/threejs-ammojs-webpack-example).
It works great. Take a look!

**Comment by Zaniyar** [comment]
I know the thread is closed, but somehow I can't make my typescript project import AmmoPhysics from '@enable3d/ammo-physics'.

`import { AmmoPhysics, ExtendedMesh, PhysicsLoader } from '@enable3d/ammo-physics'
`

It can't be resolved: 

```
[build] Module not found: Error: Can't resolve '@enable3d/ammo-physics' in '...\src'
[build] [nodemon] app crashed - waiting for file changes 
before starting...
```

I did already ``$ npm i @enable3d/ammo-physics ``  
Do I need to install more?

**Comment by yandeu** [comment]
Have you looked at the source of [this example](https://github.com/enable3d/threejs-ammojs-webpack-example)?

**Comment by Zaniyar** [comment]
yes I had a look there;
What I see is you have only "enable3d": "~0.24.1" as dependency in package.json - but you import also THREE in three.ts - is that a sub dependency of enable3d which is downloaded automatically with it?

my react app looks the same now:

added only enable3d as dependency in package.json: 
"enable3d": "~0.24.1" 

and did npm i

then 
```
 import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { AmmoPhysics, ExtendedMesh, PhysicsLoader } from '@enable3d/ammo-physics'
```

but I still get this error on the build: 

[build] Module not found: Error: Can't resolve '@enable3d/ammo-physics' in '...myReactApp/src'

**Comment by Zaniyar** [comment]
I added the compiled ammo.js from the dist into my html as script tag and now it is available - but I don't think that this is the solution. Isn't there any simple clean react example with npm and no extra hacks available? 

> they do the same: add compiled ammo.js to html https://discourse.threejs.org/t/ammo-btvector3-is-not-a-constructor/26088

Looks like this issue is the same or at least related: https://github.com/enable3d/enable3d/issues/27 

Thank you anyways for your effort!
