### ISSUE TITLE
Question: pass through detect

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [enable3d/enable3d#82]
i want to detect a object, like a ball or a box, it pass through a hole or a door, then some thing will happend, example, the scorce +1 .

what is the best way to impl it ?

**Comment by yandeu** [comment]
Use a ghost/sensor body just like in [this example](https://enable3d.io/examples/first-phaser-game-3d-version.html).

- CollisionFlags 4 is Dynamic Ghost.
- CollisionFlags 5 is Static Ghost.
- CollisionFlags 6 is Kinematic Ghost.

**Comment by Lyoko-Jeremie** [comment]
oh, i need `pass through` , only use the Collision is not enough.

example , i need to check a object pass through a Basketball hoop , if the ball hit the basket and backoff it, it not get the scorce.

---

now i have a idea about how to solve it:

make two Ghost plane between the door like a Sandwich , then listen the `end` event. if two `end` event come one-by-one, means the object pass the door .

i think above way too complex, is any one have a more simple way ?

**Comment by yandeu** [comment]
> i think above way too complex, who have a more simple way ?

I would also do it using two ghost objects.
