### ISSUE TITLE
Problem loading textures when reloading the scene.

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#86]
I have the following piece of code that works fine when starting the scene. 

![Image of water](https://i.imgur.com/d8DNx31.png)

The problem is when I restart the scene through this.restart().

![Image of error](https://i.imgur.com/08cbk3O.png)

**Comment by yandeu** [comment]
Not sure. But maybe try to preload the textures first using `this.load.preload()`. Just like in this example: https://enable3d.io/examples/project-options-and-multiple-scenes.html

**Comment by HadrienRivere** [comment]
> Not sure. But maybe try to preload the textures first using `this.load.preload()`. Just like in this example: https://enable3d.io/examples/project-options-and-multiple-scenes.html

Fixed!!!!!!
