### ISSUE TITLE
Any example to package my game in an APK?

### ISSUE THREAD

**Issue by HadrienRivere** [enable3d/enable3d#87]
Any example to package my game in an APK?

**Comment by yandeu** [comment]
I have no example. Have you tried [capacitor](https://capacitorjs.com/)?

**Comment by HadrienRivere** [comment]
I don't know. I just heard from him. I was going to try some webview in react native.

**Comment by yandeu** [comment]
I never tried webview in react native before.

**Comment by HadrienRivere** [comment]
I solved it.

**Comment by yandeu** [comment]
Did you use react native?

**Comment by HadrienRivere** [comment]
I have been testing React Native Cli and Capacitor.js. and both work correctly, only that when doing the build in RNCLI the weight of the apk rises to 40 MB and the build in Capacitor.js is 8 MB. So I decided to stick with Capacitor.js plus you don't have to configure anything else like RNCLI.

**Comment by yandeu** [comment]
Thanks for sharing your experience ☺️
