### ISSUE TITLE
game not displaying after update from 0.19.1 to 0.21.0

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#88]
Hello, 

The worst thing is that console do not throw me any error. :/

the game was staring well (i see, the assets are preloading), and then for only one seconds scene try to be build, but after that only what i see is black screen. 
Everything was fine 5 minutes ago, when i was checking all of features on 0.19.1
Code of my 3d scene:

```js
import 'phaser'
import { GAME_CONFIG } from '../index.js'
import { Player } from '../Player'
import loadSkillManager from '../SkillManager.js'
import { Scene3D, THREE } from '@enable3d/phaser-extension'

import { StateManager } from '../StateManager.js'
import Effect from '../Effect'

export default class SpaceScene extends Scene3D {
  constructor() {
    super('SpaceScene')

    this.SCENE_CONFIG = {
      CAMERA_LOOK_AT: [0, 0, -28],
      CAMERA_POSITION: [0, 3.2, 4],
      LEFT_CHARACTER_POSITION: [-3, 0, -4],
      LEFT_CHARACTER_DIRECTION: [0, 1.6, 0],
      RIGHT_CHARACTER_POSITION: [3, 0, -4],
      RIGHT_CHARACTER_DIRECTION: [0, -1.6, 0],
      CHARACTER_SCALE: 0.02,
      LEFT_CHARACTER_POSITION_2D: { x: 515, y: 615 },
      RIGHT_CHARACTER_POSITION_2D: { x: 1385, y: 615 }
    }
  }

  init() {
    this.accessThirdDimension()
  }

  create() {
    StateManager.actualTopScene = this.scene.key
    this.third.warpSpeed('sky', 'ground', 'light', 'orbitControls')
    this.third.renderer.gammaFactor = 1.5
    this.third.renderer.toneMapping = THREE.LinearToneMapping
    this.third.renderer.toneMappingExposure = 3.5
    this.third.renderer.compile(this.third.scene, this.third.camera)

    this.third.renderer.shadowMap.enabled = true
    this.cameras.main.setViewport(
      0,
      0,
      GAME_CONFIG.scale.width,
      GAME_CONFIG.scale.height
    )
    this.third.renderer.setSize(
      GAME_CONFIG.scale.width,
      GAME_CONFIG.scale.height
    )
    this.third.camera.aspect =
      GAME_CONFIG.scale.width / GAME_CONFIG.scale.height
    this.third.camera.updateProjectionMatrix()
    this.third.camera.position.set(...this.SCENE_CONFIG.CAMERA_POSITION)
    this.third.camera.lookAt(...this.SCENE_CONFIG.CAMERA_LOOK_AT)

    this.third.scene.fog = new THREE.Fog(0x7b684d, 16, 25)
    this.third.scene.background = new THREE.Color(0x000000)
    this.sceneLight = null

    loadSkillManager(this)

    this.createLight2()
    this.createPlayer()
    this.createBackgroundAnimation()

    this.movementCounter = 0
    this.kuleczka()
  }

  createClouds() {
    this.clouds = []
    this.cloud = new Effect({
      scene: this,
      x: 797,
      y: 237,
      key: 'chmury'
    }).setAlpha(0.7)

    this.cloud2 = new Effect({
      scene: this,
      x: 885,
      y: 284,
      key: 'chmury'
    })
    this.cloud3 = new Effect({
      scene: this,
      x: 890,
      y: 190,
      key: 'chmury'
    }).setAlpha(0.7)
    this.cloud.setDepth(-1).setAlpha(1)

    this.cloud.setScale(0.75, 1.25)
    this.cloud2.setScale(1.75, 2.2)
    this.cloud3.setScale(0.5, 1.25)

    this.cloud2.angle = -90
    this.cloud.angle = -90
    this.cloud3.angle = -95

    this.clouds.push(this.cloud)
    this.clouds.push(this.cloud2)
    this.clouds.push(this.cloud3)
  }

  prepareLight() {
    const thisLight2 = this.third.lights.pointLight({
      color: 0xf77c3f,
      intensity: 2,
      distance: 20
    })

    thisLight2.position.set(...this.SCENE_CONFIG.RIGHT_CHARACTER_POSITION)
    this.third.add.existing(thisLight2)

    const thisLight3 = this.third.lights.pointLight({
      color: 0xf77c3f,
      intensity: 3,
      distance: 20
    })

    thisLight3.position.set(...this.SCENE_CONFIG.LEFT_CHARACTER_POSITION)
    this.third.add.existing(thisLight3)

    setTimeout(() => {
      this.third.destroy(thisLight2)
    }, 3400)

    setTimeout(() => {
      this.third.destroy(thisLight3)
    }, 3500)
  }

  createBackgroundAnimation() {
    const dd = { width: 1, height: 30, z: -6, y: -2.8 }
    const dd2 = { width: 52, height: 12, z: -18, y: 15.25 }

    let ground2 = this.third.add.ground(dd, { lambert: { transparent: true } })
    let v8 = '/assets/sponza_v8/spenzo.gltf'
    let v5 = '/assets/sponza_edit_v5/spenzo.gltf'
    let v26 = '/assets/cave/cave.gltf'
    let v6 = '/assets/sponza_edit_v52/spenzo.gltf'

    let loader = new THREE.GLTFLoader()

    loader.load(v5, model => {
      let mesh = model.scene.children[0]
      mesh.scale.set(0.02, 0.02, 0.02)
      mesh.position.set(-2, 0, -3)
      mesh.traverse(child => {
        if (child.isMesh) {
          child.castShadow = child.receiveShadow = true
        }
      })

      this.third.add.existing(mesh)
    })
  }

  kuleczka() {
    var map = new THREE.TextureLoader().load('/assets/checkblack.png')
    var map2 = new THREE.TextureLoader().load('/assets/blackmap.png')
    var material = new THREE.SpriteMaterial({ alphaMap: map2, map: map })
    var sprite = new THREE.Sprite(material)
    sprite.position.set(-3, 3.4, -3)
    sprite.scale.set(0.3, 0.3, 0.3)
    this.third.add.existing(sprite)

    const Wu = this.input.keyboard.addKey('W')
    const Aa = this.input.keyboard.addKey('A')
    const Es = this.input.keyboard.addKey('S')
    const De = this.input.keyboard.addKey('D')
    const Zz = this.input.keyboard.addKey('Z')
    const Xx = this.input.keyboard.addKey('X')

    Wu.on('down', event => {
      sprite.position.y += 0.1
      console.log(sprite.position)
    })
    Aa.on('down', event => {
      sprite.position.x -= 0.1
      console.log(sprite.position)
    })
    Es.on('down', event => {
      sprite.position.y -= 0.1
      console.log(sprite.position)
    })
    De.on('down', event => {
      sprite.position.x += 0.1
      console.log(sprite.position)
    })
    Zz.on('down', event => {
      sprite.position.z += 0.1
      console.log(sprite.position)
    })
    Xx.on('down', event => {
      sprite.position.z -= 0.1
      console.log(sprite.position)
    })

    return sprite
  }

  createLight2() {
    this.sceneLight = new THREE.PointLight(0xffffff, 1.5)
    this.sceneLight.distance = 10
    this.sceneLight.position.set(0, 6.3, -4)
    this.sceneLight.receiveShadow = this.sceneLight.castShadow = true
    this.sceneLight.shadow.mapSize.width = 1024
    this.sceneLight.shadow.mapSize.height = 1024

    this.sceneLight.shadow.bias = -0.0005
    var ambient = new THREE.AmbientLight(0x404040, 0.3)
    this.third.add.existing(ambient)

    const light = new THREE.DirectionalLight(0xbca88f, 1)
    light.castShadow = true
    light.position.set(0, 3, 1)
    light.target.position.set(0, 0, 0)
    light.shadow.mapSize.width = 4096
    light.shadow.mapSize.height = 4096
    light.shadow.camera.top = 35
    light.shadow.camera.right = 35
    light.shadow.camera.bottom = -85
    light.shadow.camera.left = -35
    light.shadow.camera.near = -20.5
    light.shadow.camera.far = 200
    light.shadow.bias = -0.0005
    this.third.add.existing(light)
  }

  createPlayer() {
    const playerInformation = {
      model: 'sura_1',
      weapon: 'sword_anim',
      hair: 'hair_head2',
      animationIdle: 'sura_wait',
      shadow: 'shadow_wait',
      skills: [243]
    }

    const playerInformation2 = {
      model: 'sura_1',
      weapon: 'sword_anim',
      hair: 'hair_head2',
      animationIdle: 'sura_wait',
      shadow: 'shadow_wait',
      skills: [246]
    }
  }

  update() {}
}

```

**Comment by yandeu** [comment]
Please read [Upgrade to v0.20.0](https://github.com/enable3d/enable3d#upgrade-to-v0200).

**Comment by Trusiak** [comment]
jesus, im so sory for this stupid question -  I have nothing in my defense as to why I didn't see it. xD

At first glance, there are a few things after the update that really messed up the look of my game:

- renderer ignores the gamma factor, 
- the blend mode, that i was using from phaser not working anymore.

these above features are very iportant for my team. 
I realize that the lack of texture blending from phaser is probably a result of moving it to separate canvases - but it spoils a huge part of the work we've done for a year so far.

**Comment by yandeu** [comment]
> renderer ignores the gamma factor

`gammaFactor` seems to be deprecated, but it still works in r123. See the example [adjust-gamma-factor-and-shadows.html](https://enable3d.io/examples/adjust-gamma-factor-and-shadows.html).

> the blend mode, that i was using from phaser not working anymore

Maybe you just need another approach to achieve the same result. What effect were you trying to get?  
Maybe [this example](https://threejs.org/examples/#webgl_materials_blending) helps.

**Comment by Trusiak** [comment]
ehh, the problem with gamma was that you changed the API again.. :(

Because we are writing the project in pure JS (we don't use TS), we decided to download your project template from this site:
https://github.com/enable3d/enable3d-phaser-project-template
and migrate the project into your template. 

We followed the instructions you posted about changing TS to JS (about add the "checkJS" flag into tsconfig.json), and remove other files with .ts from folders - but game.ts doesn't see our js files and throws us error:

`SceneLoader.js:1 Uncaught ReferenceError: Cannot access 'SceneLoader' before initialization`

and it's just because he can't see .js files (when we change the SceneLoader.js into SceneLoader.ts, then the files becomes legible).

Why this is happening? O_O

**Comment by Trusiak** [comment]
> gammaFactor seems to be deprecated, but it still works in r123. See the example adjust-gamma-factor-and-shadows.html.

You just changed the API again and it confused us. 

> Maybe you just need another approach to achieve the same result. What effect were you trying to get?
Maybe this example helps.

this example refers to elements from the three.js page
we're talking about blending on the phaser side - we'll post you an example as soon as we get the project working properly, because we're having a little problem (more on that below)



The problem is:

We cannot use other post process effects (e.g. Bloom Effect) than the ones you put in the example - because they lose references. 
You need to put paths to them in index.ts files in three-wrapper, but we can't do that, because for some reason those .ts files don't want to compile to .js kied we want to build the application. 
What do we need to do to get these .ts files to compile to .js?
ew. can you update those paths in the enable source?

**Comment by yandeu** [comment]
> You just changed the API again and it confused us. ( ͡° ʖ̯ ͡°)

Well, the three.js API changes a lot. I just try to adapt as well as possible.

---

You do not need to import any .ts files at all. Every package has a `dist` folder with the transpiled files.
For example: If you install the package `@enable3d/ammo-physics` with npm, you will find all .js files inside `./node_modules/@enable3d/ammo-physics/dist`.

`index.js` of `@enable3d/three-wrapper` would therefore be `./node_modules/@enable3d/three-wrapper/dist/index.js`

**Comment by Trusiak** [comment]
> > You just changed the API again and it confused us. ( ͡° ʖ̯ ͡°)
> 
> Well, the three.js API changes a lot. I just try to adapt as well as possible.
> 
> You do not need to import any .ts files at all. Every package has a `dist` folder with the transpiled files.
> For example: If you install the package `@enable3d/ammo-physics` with npm, you will find all .js files inside `./node_modules/@enable3d/ammo-physics/dist`.
> 
> `index.js` of `@enable3d/three-wrapper` would therefore be `./node_modules/@enable3d/three-wrapper/dist/index.js`

im know. But if somebody will be want to use another shader / postprocess, than one of these:
https://i.imgur.com/wDUD8aJ.png

it throws error about lost reference, because only these Passes are exported. 

A beginner will not change anything in the js code in the dist folder, because in case of three-wrapper it is minified and linked to another one. 
You simply need to add an export to the index.ts file (in three-wrapper) whole of post process elements and recompile it to .js.

Of course, someone who knows webpack can handle this and recompile - because there is a file called "webpack.index.js" with instructions, but a beginner will be furious. :D

**Comment by yandeu** [comment]
I will not add more post-processing/shaders to the bundle. I think, I will even remove them completely.

If you use npm, three.js is installed as a peerDependency since the latest dev version. Means you have access to the whole three.js library.

`npm i @enable3d/phaser-extension@0.22.0-dev.0`

**Comment by Trusiak** [comment]
when i used this command, my project throws many errors like these: 

```
ERROR in ./node_modules/@enable3d/three-wrapper/dist/index.js
Module not found: Error: Can't resolve 'three' in 'F:\ETE\node_modules\@enable3d\three-wrapper\dist'
 @ ./node_modules/@enable3d/three-wrapper/dist/index.js 14:13-29
 @ ./node_modules/@enable3d/phaser-extension/dist/index.js
 @ ./src/scripts/game.ts
 @ multi ./src/scripts/game.ts ./webpack/credits.js

ERROR in ./node_modules/@enable3d/three-wrapper/dist/deprecated.face3.js
Module not found: Error: Can't resolve 'three' in 'F:\ETE\node_modules\@enable3d\three-wrapper\dist'
 @ ./node_modules/@enable3d/three-wrapper/dist/deprecated.face3.js 5:16-32
 @ ./node_modules/@enable3d/three-wrapper/dist/index.js
 @ ./node_modules/@enable3d/phaser-extension/dist/index.js
 @ ./src/scripts/game.ts
 @ multi ./src/scripts/game.ts ./webpack/credits.js

ERROR in ./node_modules/@enable3d/three-wrapper/dist/index.js
Module not found: Error: Can't resolve 'three/examples/jsm/WebGL' in 'F:\ETE\node_modules\@enable3d\three-wrapper\dist'
 @ ./node_modules/@enable3d/three-wrapper/dist/index.js 41:14-49
 @ ./node_modules/@enable3d/phaser-extension/dist/index.js
 @ ./src/scripts/game.ts
 @ multi ./src/scripts/game.ts ./webpack/credits.js

ERROR in ./node_modules/@enable3d/three-wrapper/dist/index.js
Module not found: Error: Can't resolve 'three/examples/jsm/controls/OrbitControls' in 'F:\ETE\node_modules\@enable3d\three-wrapper\dist'
 @ ./node_modules/@enable3d/three-wrapper/dist/index.js 39:22-74
 @ ./node_modules/@enable3d/phaser-extension/dist/index.js
 @ ./src/scripts/game.ts
 @ multi ./src/scripts/game.ts ./webpack/credits.js

ERROR in ./node_modules/@enable3d/three-wrapper/dist/index.js
Module not found: Error: Can't resolve 'three/examples/jsm/deprecated/Geometry' in 'F:\ETE\node_modules\@enable3d\three-wrapper\dist'
 @ ./node_modules/@enable3d/three-wrapper/dist/index.js 16:17-66
 @ ./node_modules/@enable3d/phaser-extension/dist/index.js
 @ ./src/scripts/game.ts
 @ multi ./src/scripts/game.ts ./webpack/credits.js
```

**Comment by yandeu** [comment]
Upgrade to [npm@7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) and try it again.

**Comment by Trusiak** [comment]
same thing happend after update to 7.5.4

**Comment by yandeu** [comment]
Maybe try to install threejs manually:
`npm i three@0.125.2`

**Comment by yandeu** [comment]
These should be the dependencies if you use the phaser template:

```json
  "dependencies": {
    "@enable3d/phaser-extension": "0.22.0-dev.0",
    "phaser": "3.52.0",
    "three": "0.125.2"
  },
```
