### ISSUE TITLE
DragControls has no effect

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d#91]
I set orbitControls, and at the same time I want the 3D model to be dragged freely, and I set DragControls. But DragControls has no effect. Is it something I set wrong?
The console does not print error messages.
The following is the code of the DragControls part:
```js
let transc = new THREE.TransformControls( camera, renderer.domElement )
	let drag3d = new THREE.DragControls( group, camera, renderer.domElement )
	drag3d.transformGroup = true
	
	drag3d.addEventListener( 'hoveron', function( event ) {
	
		this.third.warpSpeed('-ground', '-sky' ).then(({ orbitControls }) => {
			if( orbitControls ) {
				orbitControls.enabled = false
			
			}		  
		})
		transformControls.attach( event.object )
		event.object.material.emissive.set( 0xff6300 )
	})
	drag3d.addEventListener( 'dragstart', function( event ) {
		
		event.object.material.emissive.set( 0xf1f1f1 )
	})
	drag3d.addEventListener( 'dragend', function( event ) {
		this.third.warpSpeed('-ground', '-sky' ).then(({ orbitControls }) => {
			if( orbitControls ) {
				orbitControls.enabled = true
			
			}		  
		})
		event.object.material.emissive.set( 0xffffff )
	})
	
	drag3d.addEventListener( 'hoveroff', function( event ) {
		event.object.material.emissive.set( 0xffffff )
	})
```

No execution after `drag3d.transformGroup = true`.

**Comment by xx0618** [comment]
If write` let drag3d = new DragControls( group, camera, renderer.domElement)` , it will prompt `DragControls is not defined`

**Comment by yandeu** [comment]
To have more control over `orbitControls`, remove it from `warpSpeed()` and then add it manually from three.js as well.

OrbitControls docs: https://threejs.org/docs/#examples/en/controls/OrbitControls

---

For all other questions (clearly three.js related), please ask them in the [three.js forum](https://discourse.threejs.org/).
